### PR TITLE
fix(ui): pagination fix and tags to be shown form end

### PR DESCRIPTION
**Pull request by chirag-madlani**
### Describe your changes :

I worked on the Closes: #10446 #10544 

#
### Type of change :

- [x] Bug fix
- [x] Improvement
- [x] New feature
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation

#
### Frontend Preview (Screenshots) :

Screenshot 2023-03-17 at 5 09 10 PM
Screenshot 2023-03-17 at 5 09 04 PM

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/developers/contribute) document.
- [ ] I have commented on my code, particularly in hard-to-understand areas.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [x] All new and existing tests passed.

#

### CODE REVIEW

**Comment by harshach** [comment]
@chirag-madlani its better to leave some form of abbreviation for the nested tags/terms
test_glossary.t.t.test_term1_sub_sub

**Comment by chirag-madlani** [comment]
@harshach have updated screenshot in the description if you can check

**Comment by harshach** [comment]
@chirag-madlani if there are multiple levels to the tags it will look like this 
image

**Comment by harshach** [comment]
Glossary part looks good to me 
image

**Comment by chirag-madlani** [comment]
@harshach Fixed that, Thanks for catching

image

**Pull request merged**
