### PR TITLE
FIX: Deleted label not appearing for bigquery

### PR DESCRIPTION
**Pull request by MilanBariya**
### Describe your changes :

I worked on the Fixing Deleted label not appearing for bigquery.
Fix: #8059 

#
### Type of change :

- [x] Bug fix
- [x] Improvement

### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/developers/contribute) document.
- [ ] I have commented on my code, particularly in hard-to-understand areas.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [x] All new and existing tests passed.

#

### CODE REVIEW

**Review by TeddyCr — APPROVED** [review]
LGTM, Have you tested it with other services (besides BQ)?

**Comment by MilanBariya** [comment]
> LGTM, Have you tested it with other services (besides BQ)?

No I have only tested with BQ and it's working fine.

**Comment by TeddyCr** [comment]
> 

Cool, can you test it with at least Snowflakes and Redshift to confirm we have not introduced any regression?

**Comment by MilanBariya** [comment]
> > 
> 
> Cool, can you test it with at least Snowflakes and Redshift to confirm we have not introduced any regression?

sure let me do that.

**Comment by MilanBariya** [comment]
> > 
> 
> Cool, can you test it with at least Snowflakes and Redshift to confirm we have not introduced any regression?

Hey @TeddyCr I test out with Snowflakes and Redshift also, and it's working fine.

**Review by ulixius9 — APPROVED** [review]

**Pull request merged**
