### PR TITLE
Fixes #3722 Use entityName type from basic.json for entity names

### LINKED ISSUE #3722: Use `entityName` type from basic.json for entity names
Every entity defines a type `name` with minLength 1 and maxLength 256. Use the definition from basic.json instead of redefining these types.

### PR DESCRIPTION
**Pull request by sureshms**
### Describe your changes :

See #3722
#
### Type of change :

- [x] Improvement

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/open-source-community/developer) document.
- [x ] I have commented on my code, particularly in hard-to-understand areas.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] All new and existing tests passed.

### CODE REVIEW

**Review by harshach — APPROVED** [review]

**Comment by harshach** [comment]
@pmbrull can you check if its affecting the python bindings as well

**Comment by pmbrull** [comment]
> @pmbrull can you check if its affecting the python bindings as well

Yep, let us work on fixing the tests and we can see what breaks. Thanks

**Comment by ayush-shah** [comment]
py-checkstyle is fixed in #3724

**Comment by ayush-shah** [comment]
Hey @sureshms - so checked out this branch and tried ingesting sample data & sample usage
It fails giving us UnHashable TypeError on Python.
It expects FullyQualifiedEntityName to be a string - it gets the same value as Pydantic Model / Object - which causes an error.
Hardcoding the methods and typecasting those with str might be one way and adding `__root__` to get str.
cc: @pmbrull @harshach

**Comment by sureshms** [comment]
@pmbrull and @ayush-shah, is this okay to commit and Python code can handle this?

**Comment by pmbrull** [comment]
> 

Yep we're already handling changes related to this PR and we should be good to go. e.g., https://github.com/open-metadata/OpenMetadata/pull/3748. Thanks!

**Pull request merged**
