### PR TITLE
mysql-unittest-added

### LINKED ISSUE #3224: Create Unit Test for MySql Ingestion
**Describe the solution you'd like**
Create Unit Test for MySql Ingestion

### PR DESCRIPTION
**Pull request by codingwithabhi**
### Describe your changes :

I worked on adding mysql unit test
fix #3224 

#
### Type of change :

- [x] Improvement

### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/open-source-community/developer) document.
- [x] I have performed a self-review of my own. 
- [x] I have tagged my reviewers below.
- [x] I have commented on my code, particularly in hard-to-understand areas.
- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] All new and existing tests passed.

#
### Reviewers
@harshach @ayush-shah @pmbrull

### CODE REVIEW

**Comment by pmbrull** [comment]
Thanks for the PR! @ayush-shah do we have some guidelines on how to set up new unit tests? Some words on what is the approach we are following and why and which cases get covered by it or not.

Then, another question maybe also for @codingwithabhi, do we need this big list of tables and views? Or would we be good to go with just a few of each? I am missing the added value of having huge lists. Please let me know what I am missing!!

In terms of types, I like that we can check that we are able to convert them. Maybe one note here would be to make sure we cover all types (or as many as possible and list down which are not added in the test, for example GEO types or things like that).

**Comment by ayush-shah** [comment]
Hey @pmbrull, we currently don't have any guidelines based on the test case approach as of now.

We won't need big set of tables, small set of tables will reiterate over schema names, so I think having min 3 to max 5 should be good enough for views as well as tables.

For the column types, we should add all the column types a service / database can use.
for eg. if mysql sqlalchemy allows 5 types, we should take in account all 5 of those.

I was thinking maybe we assert the output expected by sink, mock rest apis and cover sink as well, remove the external OM API factor and make it a proper closed environment unit test.

I am not sure if we should take this approach. @pmbrull let me know if the last point sounds good, if so, we can take that approach.

cc: @codingwithabhi

**Comment by pmbrull** [comment]
> Hey @pmbrull, we currently don't have any guidelines based on the test case approach as of now.
> 
> We won't need big set of tables, small set of tables will reiterate over schema names, so I think having min 3 to max 5 should be good enough for views as well as tables.
> 
> For the column types, we should add all the column types a service / database can use. for eg. if mysql sqlalchemy allows 5 types, we should take in account all 5 of those.
> 
> I was thinking maybe we assert the output expected by sink, mock rest apis and cover sink as well, remove the external OM API factor and make it a proper closed environment unit test.
> 
> I am not sure if we should take this approach. @pmbrull let me know if the last point sounds good, if so, we can take that approach.
> 
> cc: @codingwithabhi

Makes sense. In terms of types however, let's consider what it is supported by the source db itself, not sqlalchemy. We should be based on the sources rather than our implementations. If we see any types not working as expected from SQA, let's build it.

Also agree on trying to have this process as `unit` without OM. I don't know if patching the APIs would be the best way, though. It might be easier to just write a new sink. One possibility could be having a file sink that stores the entities in a JSON array and we can then read that in the test and cast to the Entity. There might be more elegant ways of doing this, so feel free to play around a bit.

WDYT?

**Comment by ayush-shah** [comment]
Yes, @pmbrull, I stand corrected, types from source db should be a better approach.
And for the sink, the above idea for file sink sounds good.
Let's assert the data ingested in the files to check the Output.
cc: @codingwithabhi

**Comment by pmbrull** [comment]
Great, thanks folks, happy that we got the chance to discuss this :) Let me know if there's anything you need 🙏

**Pull request closed without merging**
