### PR TITLE
Added fix for Sample_Usage not being ingested in Local docker

### LINKED ISSUE #3647: Sample usage not being ingested in local docker
**Affected module**
Docker

**Describe the bug**
Sample usage not being ingested in local docker

**To Reproduce**

**Expected behavior**

**Version:**
 - OpenMetadata version: 0.9.1

**Additional context**

### PR DESCRIPTION
**Pull request by ayush-shah**
### Describe your changes :

Worked on fixing the ingestion of sample usage on local docker setup.
fix #3647 
#
### Type of change :

- [x] Bug fix
- [x] Improvement

#
### Frontend Preview (Screenshots) :
<p align="center">For frontend related change, please link screenshots of your changes preview! Optional for backend related changes.
</p>

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/open-source-community/developer) document.
- [x] I have performed a self-review of my own. 
- [x] I have tagged my reviewers below.
- [ ] I have commented on my code, particularly in hard-to-understand areas.
- [ ] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [x] All new and existing tests passed.

#
### Reviewers

@harshach @pmbrull

### CODE REVIEW

**Comment by ayush-shah** [comment]
error still persists in #3648, not sure if it's backend or UI
cc: @harshach @darth-coder00 

Steps to reproduce:
- Run run_local_docker.sh
- Start server
- Explore
- Go to one of the tables
- Change description
- Go to Explore

Expected Output:
Description Changes according to latest change

Actual Output:
Description doesn't change and stays the same whereas we see the activity feed having latest changes

**Review by harshach — CHANGES_REQUESTED** [review]
@ayush-shah why are we doing this again? We discussed this not to turn on the sample data ingestion by default in the image itself. Instead we can make curl calls as part of selenium test to enable and trigger these pipelines right?
if we do this and all the work we did for skipping ingestion pipeline will be undone

**Comment by ayush-shah** [comment]
> @ayush-shah why are we doing this again? We discussed this not to turn on the sample data ingestion by default in the image itself. Instead we can make curl calls as part of selenium test to enable and trigger these pipelines right? if we do this and all the work we did for skipping ingestion pipeline will be undone

Based on the comments by @vivekratnavel - https://github.com/open-metadata/OpenMetadata/pull/3590#discussion_r832485651 I added this

**Comment by vivekratnavel** [comment]
@ayush-shah My suggestion was only about the flag and not the implementation.

**Review by harshach — APPROVED** [review]

**Review by akash-jain-10 — APPROVED** [review]

**Pull request merged**
