### PR TITLE
Fixed streamLoading bug

### PR DESCRIPTION
**Pull request by alexbassa**
### Describe your changes :
I worked on the elastic-search-index.page.tsx file because the ElasticSearch refresh re-loads the entire panel, without greying out the areas while loading. I believe that this is due to a small bug in the code, where the initial developer misused a variable, thus meaning the panel can never be set to 'loading'. This has been rectified. Issue: https://github.com/open-metadata/OpenMetadata/issues/7948

#
### Type of change :

- [x] Bug fix

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/developers/contribute) document.
- [x] All new and existing tests passed.

#

### CODE REVIEW

**Comment by Sachin-chaurasiya** [comment]
Hello @alexbassa , Thanks for the PR, can you attach the screen recording?

**Comment by alexbassa** [comment]
Hey @Sachin-chaurasiya, I've had some major issues getting Open Metadata to run locally on my laptop. I'm pretty certain that this fix works but at this time I am unable to send the screenshots. Thanks

**Review by harshach — DISMISSED** [review]

**Comment by Sachin-chaurasiya** [comment]
Hello @alexbassa, There is a conflict, can you resolve that?

**Comment by harshach** [comment]
@chirag-madlani can we merge it in by fixing the conflict?

**Review by chirag-madlani — APPROVED** [review]

**Pull request merged**
