### PR TITLE
Multi language: add zh-cn

### PR DESCRIPTION
**Pull request by mark800**
### Describe your changes :
add zh-cn language

#
### Type of change :

- [x] Improvement

#
### Frontend Preview (Screenshots) :
<p align="center">For frontend related change, please link screenshots of your changes preview! Optional for backend related changes.
</p>

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/developers/contribute) document.
- [x] All new and existing tests passed.

#

### CODE REVIEW

**Comment by mark800** [comment]
> 

some checks were failed, but the error message is "Error: There were 0 failed tests"

**Review by harshach — APPROVED** [review]

**Comment by Sachin-chaurasiya** [comment]
Hello @mark800, Thanks for the PR.
You have only translated the labels and the messages are still in English, it would be great if you could take care of that as well.
Thanks

**Comment by mark800** [comment]
> Hello @mark800, Thanks for the PR. You have only translated the labels and the messages are still in English, it would be great if you could take care of that as well. Thanks

I will do it when I’m more familiar with OM

**Comment by mark800** [comment]
@Sachin-chaurasiya  one check failure left, seem not related with this PR
截屏2023-01-19 下午4 14 35

**Review by ShaileshParmar11 — APPROVED** [review]

**Pull request merged**
