### PR TITLE
ISSUE-16847: Extract upstreamTables for unsupported custom SQL in Tab…

### PR DESCRIPTION
**Pull request by dntjr8096**
### Describe your changes:

Fix : https://github.com/open-metadata/OpenMetadata/issues/16847

I have successfully completed testing of this solution using our company's internal Tableau instance. The LineageParser effectively extracted upstream tables from unsupported SQL queries, demonstrating the feasibility and potential benefits of this feature.

#
### Type of change:

- [ ] Bug fix
- [x] Improvement
- [ ] New feature
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/developers/contribute) document.
- [x] My PR title is `Fixes <issue-number>: <short explanation>`
- [ ] I have commented on my code, particularly in hard-to-understand areas. 
- [ ] For JSON Schema changes: I updated the migration scripts or explained why it is not needed.

### CODE REVIEW

**Review by ulixius9 — COMMENTED** [review]
Hey @dntjr8096, thanks for the pr looks good to me, can you please add some tests for this?

**Comment by dntjr8096** [comment]
@ulixius9 I conducted the tests using our company's internal Tableau setup, so providing the test cases is challenging. I will personally take some time to identify the relevant cases and share them with you as soon as possible.

Thank you for your reviews

**Comment by ulixius9** [comment]
@dntjr8096 oh maybe I did not mention it clearly, I was talking about adding unit tests for the new code that you have introduced

**Comment by dntjr8096** [comment]
@ulixius9 Aha I understand, I will write the unit test code additionally and request a review again

**Pull request closed without merging**
