### PR TITLE
Add Database and Schema on Explore Menu

### LINKED ISSUE #13276: Search on database schemas
**Is your feature request related to a problem? Please describe.**
It's impossible to search on database schemas

**Describe the solution you'd like**
Maybe a new Elasticsearch index on database schemas or include schemas to table index. The end result is to search on schemas. 

**Describe alternatives you've considered**
No alternatives 

**Additional context**
Why it's important. In DWH schema is very important part of data discovery. User should have a chance to find all tables in a particular schema.

### PR DESCRIPTION
**Pull request by karanh37**
### Describe your changes:

Fixes #13276 

I worked on ... because ...

image

#
### Type of change:

- [ ] Bug fix
- [ ] Improvement
- [ ] New feature
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/developers/contribute) document.
- [ ] My PR title is `Fixes <issue-number>: <short explanation>`
- [ ] I have commented on my code, particularly in hard-to-understand areas. 
- [ ] For JSON Schema changes: I updated the migration scripts or explained why it is not needed.

### CODE REVIEW

**Comment by mgorsk1** [comment]
This is great and very needed but explore list is becoming more and more chaotically ordered - it's neither alphabetical nor ordered by amount of matching documents. What is the rationale behind placing elements in Explore list? I think it would use some UX refinement:
- `Database`, `Schema` and `Table` entries  should be grouped into one `Database Service`  group and ordered according to hierarchy
- Other entries should be ordered alphabetically

**Comment by harshach** [comment]
@mgorsk1 thanks for your input. Yes we do have UX designers :) , we are working several different options and none of them are to our satisfaction currently. The goal is to ship the functionality and improve the design here. Will see what we can do.

**Comment by mgorsk1** [comment]
cool, very glad it's happening anyways @harshach 😍

**Review by chirag-madlani — APPROVED** [review]

**Comment by chirag-madlani** [comment]
@harshach can you review as well?

**Review by harshach — APPROVED** [review]

**Pull request merged**
