### PR TITLE
Added JSON-Schema Form Builder for connection configs

### PR DESCRIPTION
**Pull request by darth-coder00**
### Describe your changes :

I worked on the Adding JSON schema form for connection schemas

#
### Type of change :

- [x] Improvement

#
### Frontend Preview (Screenshots) :
<p align="center">
</p>

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/open-source-community/developer) document.
- [ ] I have commented on my code, particularly in hard-to-understand areas.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [x] All new and existing tests passed.

#
### Reviewers
@vivekratnavel @Sachin-chaurasiya @ShaileshParmar11 @harshach

### CODE REVIEW

**Review by vivekratnavel — APPROVED** [review]

**Comment by vivekratnavel** [comment]
@darth-coder00 I think the lock file needs to be updated. Can you do "yarn install" and commit?

**Comment by darth-coder00** [comment]
> @darth-coder00 I think the lock file needs to be updated. Can you do "yarn install" and commit?

@vivekratnavel Verified, it's already up-to-date

**Review by Sachin-chaurasiya — APPROVED** [review]
Great work @darth-coder00.

**Review by ShaileshParmar11 — APPROVED** [review]
LGTM!

**Comment by ayush-shah** [comment]
Python tests failing are being handled in #4095

**Pull request merged**
