### PR TITLE
Extra headers for metadata API

### PR DESCRIPTION
**Pull request by czuares**
### Describe your changes :

- Allows for extra headers to be provided to the ometa API client
- Adds `extraHeaders` to the `workflowConfig.openMetadataServerConfig` schema
- Supports copying existing header values using string modulo format with the header dictionary

Example usage:

```yaml
  openMetadataServerConfig:
    hostPort: ${OMD_API_HOST}
    authProvider: google
    extraHeaders:
      Proxy-Authorization: "%(Authorization)s"
      Some-Env-Header: ${MY_ENV_VAR}
      Static-Header: my-value
```

The primary use case is for Google Cloud's Identity Aware Proxy (IAP) which allows secure access to private services but removes the Authorization header in the process. The `Proxy-Authorization` header gets forwarded along to the service as the `Authorization` header for the service behind IAP. In this case, the token is valid for Google SSO as well and can be passed through and enables "nested" authorization options.

Here's a [relevant StackOverflow](https://stackoverflow.com/questions/59297161/using-nested-authentication-with-google-iap) about the header.

#
### Type of change :

- [ ] Bug fix
- [x] Improvement
- [x] New feature
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/developers/contribute) document.
- [x] I have commented on my code, particularly in hard-to-understand areas.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [x] All new and existing tests passed.

#
### Reviewers
@open-metadata/ingestion

### CODE REVIEW

**Comment by pmbrull** [comment]
hi @czuares, thanks for the proposal. I am unsure if relying on environment variables is the best way around this. Updating the [OpenMetadataConnection](https://github.com/open-metadata/OpenMetadata/blob/main/openmetadata-spec/src/main/resources/json/schema/entity/services/connections/metadata/openMetadataConnection.json) JSON Schema would help on keeping track on the different ways to build the client.

@harshach do you think we might need something similar to `connectionOptions` here to allow key-value pairs to be passed to the headers?

Thanks

**Comment by czuares** [comment]
@pmbrull Thanks for taking the time to review my PR. I would be happy to improve upon this approach. If we are considering using the JSON schema, perhaps it could look something like this:

```
workflowConfig:
  openMetadataServerConfig:
    securityConfig:
      extraApiHeaders:
      - name: SOME_HEADER
        value: ${SOMETHING_FROM_ENV}
      - name: Proxy-Authorization
        valueFrom: Authorization
```

This would allow for setting headers from the environment using the `value` key or using the `valueFrom` key to copy the value from an existing header. Thoughts?

**Comment by pmbrull** [comment]
> @pmbrull Thanks for taking the time to review my PR. I would be happy to improve upon this approach. If we are considering using the JSON schema, perhaps it could look something like this:
> 
> ```
> workflowConfig:
>   openMetadataServerConfig:
>     securityConfig:
>       extraApiHeaders:
>       - name: SOME_HEADER
>         value: ${SOMETHING_FROM_ENV}
>       - name: Proxy-Authorization
>         valueFrom: Authorization
> ```
> 
> This would allow for setting headers from the environment using the `value` key or using the `valueFrom` key to copy the value from an existing header. Thoughts?

Thanks for the ping @czuares. I believe we could replicate the [connectionOptions](https://github.com/open-metadata/OpenMetadata/blob/main/openmetadata-spec/src/main/resources/json/schema/entity/services/connections/connectionBasicType.json#L7) approach we have for connections for extra headers.

Instead of adding this information inside `securityConfig` (in there we have the SSO details as external refs), we could have a new optional property with what you propose.

If you move on with the implementation, i'd also be great if you could add the relevant information in the Python SDK docs ([here](https://github.com/open-metadata/OpenMetadata/blob/main/openmetadata-docs/content/sdk/python/index.md)) with your example use case.

We're now close to getting the 0.13.1 release out, so we'd be merging this PR in after getting that done to ensure we have enough testing time around it. This change would then be published in 0.13.2 in mid January.

Meanwhile, I am already marking your PR safe to test for you to get some CI checks running.

Thanks

**Comment by yu-iskw** [comment]
I love the feature, because we secure our OpenMetadata with Google Cloud IAP. We would like to add extra request headers to authenticate a client.

**Comment by pmbrull** [comment]
hi @czuares, let me know if you are available to get back on this or if you have any questions. Thanks!

**Comment by czuares** [comment]
@pmbrull I'll try to make some time soon and reach out if/when I have some questions, thanks!

**Comment by czuares** [comment]
@pmbrull Please re-review my changes when you get a chance. I have taken the approach you suggested and have a cleaner solution (in my opinion, at least 🙂)

**Review by pmbrull — APPROVED** [review]
Thanks for the changes! Having it in JSON schemas makes it way easier, thanks for the solution. LGTM

**Comment by pmbrull** [comment]
Oh just saw the pylint failure `Too many local variables (16/15) (too-many-locals)` in the `ingestion/src/metadata/ingestion/ometa/client.py:130:4:`. Feel free to add a pylint ignore for now. We'll need to split some of those functionalities to clean it. Thanks

**Comment by czuares** [comment]
@pmbrull could you please review again? I added the lint bypass and addressed a dictionary merge compatibility with python < 3.9.

The failing check appears to be unrelated.

**Review by pmbrull — APPROVED** [review]
Thanks! LGTM, indeed the cypress issues are not related to this. Thanks for the PR!

**Comment by yu-iskw** [comment]
@czuares Thank you very much for implementing the feature. This is what I really want so that we make OpenMetadata secure with Google Cloud IAP. I look forward to that the feature will be released. 
https://cloud.google.com/iap/docs/authentication-howto

**Pull request merged**
