### PR TITLE
Issue 6760: add new metrics using regular expression in the orm_profiler

### PR DESCRIPTION
**Pull request by Daniel53245**
### Describe your changes :
https://github.com/open-metadata/OpenMetadata/issues/6760
We created an orm function named [regex_match](https://github.com/Daniel53245/OpenMetadata/blob/ISSUE-6760/ingestion/src/metadata/orm_profiler/orm/functions/regex_match.py) to determine whether the value matches the regex because a new independent function would be helpful as a new test in metrics. In the function, we follow the syntax of BigQuery, RedShift, Snowflake

Besides, we added two new static metrics ([MATCH_REGEX_COUNT](https://github.com/Daniel53245/OpenMetadata/blob/ISSUE-6760/ingestion/src/metadata/orm_profiler/metrics/static/match_regex_count.py) and [NOT_MATCH_REGEX_COUNT](https://github.com/Daniel53245/OpenMetadata/blob/ISSUE-6760/ingestion/src/metadata/orm_profiler/metrics/static/not_match_regex_count.py)) which are implemented with this function returning the number of regex in the target column.

In the [column_values_to_match_regex.py](https://github.com/open-metadata/OpenMetadata/blob/main/ingestion/src/metadata/test_suite/validations/column/column_values_to_match_regex.py) and [column_values_to_not_match_regex.py](https://github.com/open-metadata/OpenMetadata/blob/main/ingestion/src/metadata/test_suite/validations/column/column_values_to_not_match_regex.py), we replace Metrics.NOT_LIKE_COUNT and Metrics.LIKE_COUNT with new regex metrics and remain everything else same.

#
### Type of change :

- [x] Bug fix
- [x] Improvement
- [] New feature
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation

#
### Frontend Preview (Screenshots) :
<p align="center">For frontend related change, please link screenshots of your changes preview! Optional for backend related changes.
</p>

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/developers/contribute) document.
- [x] I have commented on my code, particularly in hard-to-understand areas.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [] All new and existing tests passed.

#

### CODE REVIEW

**Comment by Daniel53245** [comment]
Hi, I am confused by the result of py-run-tests 3.7 there seems to be an error triggered by being unable t import something. I am not sure how that is triggered. Could anyone provide some suggestions

**Comment by pmbrull** [comment]
Hi @Daniel53245 , many thanks for the PR. Indeed the error you are facing is due to a version bump that changed a named. It is fixed in https://github.com/open-metadata/OpenMetadata/pull/8861.

If you could please merge main back into the branch, everything should be good.

@TeddyCr could you please take a look?

Thanks folks!

**Comment by TeddyCr** [comment]
Thank you @Daniel53245 for the contribution. Really appreciate it. Looking a bit deeper into this issue we should be able to replace the `like` and `not_like` function with [`regexp_match`](https://docs.sqlalchemy.org/en/14/core/sqlelement.html#sqlalchemy.sql.expression.ColumnOperators.regexp_match). This should simplify things a bit.

For the not like we'll just need to inverse 0 and 1 as the tests check if the sum returns is 0. In this case, if we see a match we should return 1 so we'll fail the test.

**Review by TeddyCr — CHANGES_REQUESTED** [review]
Thank you @Daniel53245 for the contribution. Really appreciate it. Looking a bit deeper into this issue we should be able to replace the `like` and `not_like` function with [`regexp_match`](https://docs.sqlalchemy.org/en/14/core/sqlelement.html#sqlalchemy.sql.expression.ColumnOperators.regexp_match). This should simplify things a bit.

For the not like we'll just need to inverse 0 and 1 as the tests check if the sum returns is 0. In this case, if we see a match we should return 1 so we'll fail the test.

**Comment by Daniel53245** [comment]
Oh, I see. I haven't noticed that there is a regexp_match in SQL alchemy. I will try to make the change.

**Comment by harshach** [comment]
@Daniel53245 would you be able to finish the PR if not let us know.
@TeddyCr or @ayush-shah lets pick this up and close it out.

**Comment by TeddyCr** [comment]
Thank @Daniel53245 for this PR. I'll be closing this as it is already supported -> https://docs.open-metadata.org/v1.1.x/connectors/ingestion/workflows/data-quality/tests#table-row-inserted-count-to-be-between.

**Pull request closed without merging**
