### PR TITLE
Fix 7278: add test connection

### LINKED ISSUE #7278: Profiler ingestion does not fail if the connection cannot be established
**Affected module**
Ingestion Framework

**Describe the bug**
Profiler ingestion does not fail if the connection cannot be established. 

**To Reproduce**
- Start OM with PostgreSQL
- Create an ingestion workflow for the airflow DB with the following configuration
```
source:
  type: postgres
  serviceName: local_postgres_airflow
  serviceConnection:
    config:
      type: Postgres
      username: airflow_user
      password: airflow_pass
      hostPort: localhost:5432
      database: airflow_db
  sourceConfig:
    config:
      type: DatabaseMetadata
sink:
  type: metadata-rest
  config: {}
workflowConfig:
  openMetadataServerConfig:
    hostPort: http://localhost:8585/api
    authProvider: no-auth
```
- Create a profile ingestion

**Expected behavior**
The ingestion should fail since the connection to `localhost:5432` is impossible.

**Version:**
 - OpenMetadata version: 0.12

cc: @TeddyCr

### PR DESCRIPTION
**Pull request by ayush-shah**
### Describe your changes :

Fix #7278 

#
### Type of change :

- [x] Bug fix
- [x] Improvement
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation

#
### Frontend Preview (Screenshots) :
<p align="center">For frontend related change, please link screenshots of your changes preview! Optional for backend related changes.
</p>

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/developers/contribute) document.
- [ ] I have commented on my code, particularly in hard-to-understand areas.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [x] All new and existing tests passed.

#
### Reviewers

@open-metadata/ingestion

### CODE REVIEW

**Comment by ayush-shah** [comment]
Added test connection to profiler

**Review by OnkarVO7 — DISMISSED** [review]

**Comment by ayush-shah** [comment]
fixing failing python test

**Comment by TeddyCr** [comment]
@ayush-shah looks like you need to fix this test -> ProfilerPartitionUnitTest.test_partition_details_ingestion_time_date.

Let's always run the test locally or open the PR as draft if we want to let the CI run the tests

**Review by pmbrull — APPROVED** [review]
Thanks!

**Pull request merged**
