### PR TITLE
ISSUE-11068: Add IAM authentication for MySQL ingestion

### PR DESCRIPTION
**Pull request by tutte**
### Describe your changes:

Fixes [ISSUE-11068](https://github.com/open-metadata/OpenMetadata/issues/11068)

I worked on MySQL IAM Authentication because users need to ingest from databases at scale without having to manage static credentials.

#
### Type of change:
- [ ] Improvement
- [x] New feature
- [ ] Documentation

#
### Checklist:
- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/developers/contribute) document.
- [x] My PR title is `Fixes <issue-number>: <short explanation>`
- [x] I have commented on my code, particularly in hard-to-understand areas. 
- [ ] For JSON Schema changes: I updated the migration scripts or explained why it is not needed.

- [x] The issue properly describes why the new feature is needed, what's the goal, and how we are building it. Any discussion
    or decision-making process is reflected in the issue.
- [x] I have updated the documentation.
- [ ] I have added tests around the new logic.

### CODE REVIEW

**Comment by pmbrull** [comment]
Thanks for popping this up @tutte. Answered you via mail, but just wanted to add here the relevant context with my thoughts on the change:

In terms of how we could shape the feature, I imagine something similar to how we handle Airflow [connections](https://github.com/open-metadata/OpenMetadata/blob/main/openmetadata-spec/src/main/resources/json/schema/entity/services/connections/pipeline/airflowConnection.json#L35). We could have a top-level `connection` property which is then referenced either by a `[Basic Auth](https://github.com/open-metadata/OpenMetadata/blob/main/openmetadata-spec/src/main/resources/json/schema/security/credentials/basicAuth.json)` with the typical user/pwd, or `awsConfig`. Then, based on the class types we receive from `connection`, we can create the connection URL one way or another. The good thing about the `oneOf` setting in the JSON Schemas, is that users can just select which type of auth they want, and they don't see all the details from other refs.

This change would then require a couple of things:
- Migration scripts update: Basically, we store the service entities as JSON in the database. If we change the shape of the connection, we need to update the stored data to reflect these changes. We use flyway for this. [Example](https://github.com/open-metadata/OpenMetadata/blob/main/bootstrap/sql/com.mysql.cj.jdbc.Driver/v009__create_db_connection_info.sql).
- Validate that the credentials are properly masked on the database. Otherwise, we might need to patch some things in the backend.

**Comment by harshach** [comment]
@tutte is this ready to be reviewed. Let us know since the PR is in draft mode. Thanks

**Comment by ayush-shah** [comment]
Hello @tutte, there are json schema changes that will be needed here..let me know if you are taking care of the same..
we have an issue https://github.com/open-metadata/OpenMetadata/issues/11068, I am starting with postgres related changes.

**Comment by ayush-shah** [comment]
cc: @open-metadata/ingestion

**Comment by ayush-shah** [comment]
Closing this PR as no response from @tutte.
we can find the similar PR that fixes #11068 here: https://github.com/open-metadata/OpenMetadata/pull/11937

**Pull request closed without merging**
