### PR TITLE
fixes #12771: Added Greenplum Ingestion Connector

### LINKED ISSUE #12771: no Support greenplum version 6
**Affected module**
Does it impact the UI, backend or Ingestion Framework?

**Describe the bug**
[2023-08-07 06:17:24,721] {test_connections.py:194} DEBUG - Traceback (most recent call last): 
 File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1802, in _execute_context 
 self.dialect.do_execute( 
 File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 719, in do_execute 
 cursor.execute(statement, parameters) 
psycopg2.errors.UndefinedColumn: column pp.polrelid does not exist 
LINE 7: JOIN pg_class AS pc ON pp.polrelid = pc.oid 
Take a look at this bug.
greenplum version 6

**To Reproduce**

Screenshots or steps to reproduce

**Expected behavior**

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: `openmetadata-ingestion[docker]==1.0.3`
 - 

**Additional context**
image

### PR DESCRIPTION
**Pull request by T01iK**
### Describe your changes:

fixes #12771  : Added Greenplum Ingestion Connector (based on Postgres connector from OpenMetadata 1.1 but queries updated to support Greenplum).
Tested on Greenplum v6

- What changes did I make?
Added Greenplum connector in Ingestion, Test Connection Service, UI, JsonSchema
- Why did you make them?
Connector was needed to support Greenplum in my project
- How did you test your changes?
Using Metadata CLI and Airflow on production Greenplum in my company

#
### Type of change:

- [x] Improvement

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/developers/contribute) document.
- [x] My PR title is `Fixes <issue-number>: <short explanation>`
- [x] I have commented on my code, particularly in hard-to-understand areas. 
- [x] For JSON Schema changes: I updated the migration scripts or explained why it is not needed.

- [ ] I have added tests around the new logic.
- [ ] For connector/ingestion changes: I updated the documentation.

### CODE REVIEW

**Review by harshach — DISMISSED** [review]

**Review by ulixius9 — COMMENTED** [review]
@T01iK Thanks for the PR ❤️, I see that we are mostly replicating the code from Postgres and (correct me if I'm wrong) the only major deference is on the queries that are used to fetch the database and table records right?? 


what if we could just either dynamically identify if the source is greenplum or add a flag from user to use understand that the source is greenplum and depending on that we use those queries? this way it would be easier to maintain.

a similar scenario we had with pg spider source as well you can take a look into this pr as reference: https://github.com/open-metadata/OpenMetadata/pull/12159.

**Comment by T01iK** [comment]
@ulixius9 Thanks for your comments. Yes, my connector is based entirely on Postgres connector, key changes are only in SQL queries to get metadata. I understand that my implementation makes it harder to maintain the connector, that is a right point.

But, I don't believe implementing it as connection schema (e.g. pgspider implementation) is going to give good user experience. Greenplum is based on Postgre but it has it's own established brand and recognition - hence I would like to see it having its own databaseService enum entry and icon in interface. AFAIK you can't have those advantages if I am going to implement it in your suggested way.
There are actually a lot of Postgre based databases - see this [link](https://wiki.postgresql.org/wiki/PostgreSQL_derived_databases), for example Redshift is also postgre derived, and has a standalone connector in your code base.
Also my Greenplum connector does not support some advanced information gathering such as tags, lineage extraction, usage (I tried to find a way to implement them as well, but my Greenplum installation supported none of those things)

IMO the ideal solution is to create some basic postgre utilities that can be shared by multiple databaseServices - PostgreSQL, Greenplum, PGSpider, RedShift - etc.
What do you think?

**Comment by harshach** [comment]
+1 for having a separate connector. However can we centralize the code in a common class that both Postgres and green plum can inherit.  @T01iK

**Comment by evmuravev** [comment]
@chirag-madlani @karanh37 Could you please also review and give an approve for this pull request? We are really looking forward to the support of Greenplum in OpenMetadata 🙏

**Comment by chirag-madlani** [comment]
@evmuravev @T01iK Can you resolve the conflicts here?

**Review by chirag-madlani — APPROVED** [review]

**Comment by T01iK** [comment]
resolved conflicts and retested the connector locally
image
@chirag-madlani @harshach

**Review by chirag-madlani — APPROVED** [review]

**Review by ulixius9 — APPROVED** [review]

**Pull request merged**
