### PR TITLE
GitBook: [#27] Adding guide for generate types from JSON Schema.

### PR DESCRIPTION
**Pull request by Sachin-chaurasiya**
### Describe your changes :

I worked on the UI docs because need to add a guide for generating types from JSON Schema.

#
### Type of change :

- [x] Documentation

#
### Frontend Preview (Screenshots) :

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/open-source-community/developer) document.
- [x] I have performed a self-review of my own. 
- [x] I have tagged my reviewers below.
- [ ] I have commented on my code, particularly in hard-to-understand areas.
- [x] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [x] All new and existing tests passed.

#
### Reviewers
@shahsank3t, @darth-coder00

### CODE REVIEW

**Comment by shahsank3t** [comment]
@Sachin-chaurasiya why do your PR have those .png and .mp4 files in it?

**Comment by Sachin-chaurasiya** [comment]
> @Sachin-chaurasiya why do your PR have those .png and .mp4 files in it?

@shahsank3t I had cherry-picked my commit from the 0.6 branches so maybe from there these files came.

**Comment by Sachin-chaurasiya** [comment]
> @Sachin-chaurasiya why do your PR have those .png and .mp4 files in it?

@shahsank3t should I remove those files from my PR?

**Review by mithmatt — APPROVED** [review]

**Review by darth-coder00 — APPROVED** [review]
LGTM!

**Pull request merged**
