### PR TITLE
Fixes : 14333 - Changed announcements startTime and endTime from seconds to milliseconds.

### LINKED ISSUE #14333: Announcement startTime and endTime should be in milliseconds instead of seconds
**Affected module**
Does it impact the UI, backend or Ingestion Framework?
backend, UI

**Describe the bug**

AnnouncementDetails `StartTime` and `EndTime` are currently stored in seconds instead milliseconds

**To Reproduce**

Screenshots or steps to reproduce

**Expected behavior**

It would be better to have all the times in milliseconds to have same time and formate in the application

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

### PR DESCRIPTION
**Pull request by Siddhanttimeline**
Fixes #14333

- Convert startTime and endTime in milliseconds for the announcements.

https://github.com/open-metadata/OpenMetadata/assets/66266464/7e5b088a-0df7-4685-af52-dd1bb7d290eb

#
### Type of change:

- [ ] Bug fix
- [x] Improvement
- [ ] New feature
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/developers/contribute) document.
- [x] My PR title is `Fixes <issue-number>: <short explanation>`
- [ ] I have commented on my code, particularly in hard-to-understand areas. 
- [ ] For JSON Schema changes: I updated the migration scripts or explained why it is not needed.

### CODE REVIEW

**Comment by mohityadav766** [comment]
@chirag-madlani can you confirm if this needs any handling on the UI?

**Review by mohityadav766 — DISMISSED** [review]
Changes looks good @Siddhanttimeline , please make sure to test the migrations

**Comment by chirag-madlani** [comment]
> @chirag-madlani can you confirm if this needs any handling on the UI?

Yes it will some ui changes. I will take a look here tomorrow

**Comment by Siddhanttimeline** [comment]
> Changes looks good @Siddhanttimeline , please make sure to test the migrations

okay, I will check and confirm.

**Comment by Ashish8689** [comment]
@mohityadav766 @Siddhanttimeline I will have a look at the UI side changes and let you all know once done!

**Comment by Siddhanttimeline** [comment]
> okay, I will check and confirm.

Migrations are confirmed to be working fine for MySQL and PostgreSQL.

**Review by mohityadav766 — APPROVED** [review]

**Review by chirag-madlani — APPROVED** [review]

**Review by mohityadav766 — APPROVED** [review]

**Pull request merged**
