### PR TITLE
Fix access control rule userRoleAttr to point to roleName

### PR DESCRIPTION
**Pull request by mithmatt**
### Describe your changes :

I worked on this to fix the schema documentation

#
### Type of change :

- [ ] Bug fix
- [ ] Improvement
- [ ] New feature
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Documentation

#
### Frontend Preview (Screenshots) :
<p align="center">For frontend related change, please link screenshots of your changes preview! Optional for backend related changes.
</p>

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/open-source-community/developer) document.
- [x] I have performed a self-review of my own. 
- [x] I have tagged my reviewers below.
- [ ] I have commented on my code, particularly in hard-to-understand areas.
- [x] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [x] All new and existing tests passed.

#
### Reviewers

Backend: @sureshms @harshach

### CODE REVIEW

**Comment by harshach** [comment]
@mithmatt these seems to be new failures
image

**Comment by mithmatt** [comment]
> @mithmatt these seems to be new failures image

#2647 2647

**Review by pmbrull — APPROVED** [review]

**Comment by pmbrull** [comment]
LGTM! Just one thing, before merging let's double-check the core package version as there are other PRs bumping it as well

**Comment by mithmatt** [comment]
> LGTM! Just one thing, before merging let's double-check the core package version as there are other PRs bumping it as well

Yes, which ever goes in after this would need to rebase...

**Pull request merged**
