### PR TITLE
Fix MLModel reference

### PR DESCRIPTION
**Pull request by kad-vijlbc**
### Describe your changes :
Fix a forgotten rename change (MLModel->Model)

#
### Type of change :

- [x] Bug fix

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/open-source-community/developer) document.
- [x ] I have tagged my reviewers below.

#
### Reviewers
@harshach @ayush-shah @pmbrull

### CODE REVIEW

**Comment by kad-vijlbc** [comment]
I see, I have a failing ingestion run:

```
Traceback (most recent call last):                                                                                        
File "/home/tom/src/OpenMetadata/ingestion/src/metadata/ingestion/ometa/ometa_api.py", line 261, in get_create_entity_type                                                                                                                        
create_class = getattr(                                                                
AttributeError: module 'metadata.generated.schema.api.data.createMLModel' has no attribute 'CreateMLModelEntityRequest' 
```

Is a file not checked in in the `main` branch?

**Comment by pmbrull** [comment]
> I see, I have a failing ingestion run:
> 
> ```
> Traceback (most recent call last):                                                                                        
> File "/home/tom/src/OpenMetadata/ingestion/src/metadata/ingestion/ometa/ometa_api.py", line 261, in get_create_entity_type                                                                                                                        
> create_class = getattr(                                                                
> AttributeError: module 'metadata.generated.schema.api.data.createMLModel' has no attribute 'CreateMLModelEntityRequest' 
> ```
> 
> Is a file not checked in in the `main` branch?

Hi @tomtor, I just tested it in a newly created branch from `main` and it is working fine for me. Moreover, looking at `metadata/generated/schema/api/data/createMLModel.py` I do find the class `CreateMLModelEntityRequest`. Have you reinstalled the python sources to your environment?

**Comment by kad-vijlbc** [comment]
Hmm

```
 python tests/integration/ometa/test_ometa_model_api.py
Traceback (most recent call last):
  File "tests/integration/ometa/test_ometa_model_api.py", line 7, in <module>
    from metadata.generated.schema.api.data.createMLModel import CreateMLModelEntityRequest
ImportError: cannot import name 'CreateMLModelEntityRequest' from 'metadata.generated.schema.api.data.createMLModel' (/home/tom/src/OpenMetadata/env38/lib/python3.8/site-packages/openmetadata_ingestion-0.4.1-py3.8.egg/metadata/generated/schema/api/data/createMLModel.py)
```

but the file is generated:

```
(env38) tom@Tom-k8s:~/src/OpenMetadata/ingestion$ ls src/metadata/generated/schema/api/data/
createChart.py      createDatabase.py  createMLModel.py  createPipeline.py  createThesaurus.py  __init__.py
createDashboard.py  createLocation.py  createModel.py    createTable.py     createTopic.py      __pycache__
```

Clearly something is broken in my build environment :-/

**Comment by kad-vijlbc** [comment]
@pmbrull Aha, in the generated file is:

`class CreateMlModelEntityRequest(BaseModel):`

Note that `Ml` has a lowercase `l`  but the import has `ML`.

This is caused by a different version of the generator?!?!

**Comment by pmbrull** [comment]
> @pmbrull Aha, in the generated file is:
> 
> `class CreateMlModelEntityRequest(BaseModel):`
> 
> Note that `Ml` has a lowercase `l` but the import has `ML`.
> 
> This is caused by a different version of the generator?!?!

Mmmmh in the main branch I see the following: https://github.com/open-metadata/OpenMetadata/blob/main/ingestion/src/metadata/generated/schema/api/data/createMLModel.py#L15

Did you locally generate the pydantic models?

**Comment by kad-vijlbc** [comment]
Yes, I did generate the files myself (`make generate` in the top directory), but I have that version installed:
```
(env38) tom@Tom-k8s:~/src/OpenMetadata/ingestion$ pip list|grep generator
datamodel-code-generator          0.11.14
```

So it is not clear what causes the mismatch

**Comment by pmbrull** [comment]
> Yes, I did generate the files myself (`make generate` in the top directory), but I have that version installed:
> 
> ```
> (env38) tom@Tom-k8s:~/src/OpenMetadata/ingestion$ pip list|grep generator
> datamodel-code-generator          0.11.14
> ```
> 
> So it is not clear what causes the mismatch

Then it is weird indeed. Could you please check with a clean branch, using the generated sources from the repo? So far we are updating the pydantic models manually when there are changes in the JSON Schemas. This is not the most sustainable approach so we're looking for ways of automating this as we have for the Java sources.

Please, let me know if from the shipped code the issue persists on your end!

**Comment by kad-vijlbc** [comment]
It persists!

```
(env38) tom@Tom-k8s:~/src/OpenMetadata/ingestion$ !py
python tests/integration/ometa/test_ometa_model_api.py
Traceback (most recent call last):
  File "tests/integration/ometa/test_ometa_model_api.py", line 7, in <module>
    from metadata.generated.schema.api.data.createMLModel import CreateMLModelEntityRequest
ImportError: cannot import name 'CreateMLModelEntityRequest' from 'metadata.generated.schema.api.data.createMLModel' (/home/tom/src/OpenMetadata/ingestion/src/metadata/generated/schema/api/data/createMLModel.py)
(env38) tom@Tom-k8s:~/src/OpenMetadata/ingestion$ git checkout main
Switched to branch 'main'
Your branch is up to date with 'origin/main'.
(env38) tom@Tom-k8s:~/src/OpenMetadata/ingestion$ !py
python tests/integration/ometa/test_ometa_model_api.py
(env38) tom@Tom-k8s:~/src/OpenMetadata/ingestion$ (cd ..; make generate > /dev/null)
/home/tom/src/OpenMetadata/env38/lib/python3.8/site-packages/datamodel_code_generator/parser/jsonschema.py:397: UserWarning: format of 'timezone' not understood for 'string' - using default
  warn(
/home/tom/src/OpenMetadata/env38/lib/python3.8/site-packages/datamodel_code_generator/parser/jsonschema.py:397: UserWarning: format of 'utc-millisec' not understood for 'string' - using default
  warn(
(env38) tom@Tom-k8s:~/src/OpenMetadata/ingestion$ !py
python tests/integration/ometa/test_ometa_model_api.py
Traceback (most recent call last):
  File "tests/integration/ometa/test_ometa_model_api.py", line 7, in <module>
    from metadata.generated.schema.api.data.createMLModel import CreateMLModelEntityRequest
ImportError: cannot import name 'CreateMLModelEntityRequest' from 'metadata.generated.schema.api.data.createMLModel' (/home/tom/src/OpenMetadata/ingestion/src/metadata/generated/schema/api/data/createMLModel.py)
```

So it works in `main`, but running `make generate` in branch `main` generates python code with an `Ml` signature, but the calling code expects `ML`.

Renaming in all the non generated files `MLModel` to `MlModel` would fix this?

**Comment by pmbrull** [comment]
Thanks for checking! Let's open an issue and I'll look into it. The codegen tool has a weird naming integration so yeah, we might need to change something to make it consistent.

**Comment by tomtor** [comment]
See https://github.com/open-metadata/OpenMetadata/issues/1268

**Pull request closed without merging**
