### PR TITLE
Fixes #12523: Airflow error with lineage ingestions from services having space chars in their names

### LINKED ISSUE #12523: Lineage ingestion not properly setup when service name contains spaces
**Affected module**
UI (fix could be here), and Ingestion Modules

**Describe the bug**
When a database service name contains space characters, the generated lineage ingestion name keeps those spaces and they appear in the underlying Airflow scripts, provoking errors and impossibility to run and check lineage ingestion DAGs

**To Reproduce**

- Create a database service name containing a space (say "**Servicewith Spacechar**")
- Create a metadate ingestion (ingestion default name is OK, all special chars replaced by _: "**Servicewith_Spacechar_metadata_xxxx**")
- Run it
- Create a lineage ingestion (ingestion name is not editable and will keep the spaces: "**Servicewith Spacechar_lineage**")
omd_lineage_ingestion_naming
- You will not be able to run the lineage ingestion or view logs, etc. due to space chars being carried on to the Airflow API calls.
openmetadata_airflow_error

**Expected behavior**
When creating a lineage ingestion within a database service, the ingestion name should have its special characters replaced.
It works fine when using "_" instead of spaces when creating the service name.

**Version:**
 - OpenMetadata version: 1.1.0

**Fix:**
I initiated #12521

### PR DESCRIPTION
**Pull request by rudydel**
### Describe your changes:

Fixes lineage ingestion names containing spaces

Added the _Lineage_ pipeline type to the utility function _getIngestionName_, so when the lineage ingestion name is generated from the service name it does not contain spaces.
I made this change after encountering an Airflow error where DAGs could not be properly set up because of a space in the name which led to a space in later Airflow API calls.

#
### Type of change:
Bug fix

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/developers/contribute) document.
- [ ] My PR title is `Fixes <issue-number>: <short explanation>`
- [ ] I have commented on my code, particularly in hard-to-understand areas. 
- [ ] For JSON Schema changes: I updated the migration scripts or explained why it is not needed.

### CODE REVIEW

**Comment by chirag-madlani** [comment]
Hi @rudydel Can you add some screenshots

**Comment by rudydel** [comment]
> Hi @rudydel Can you add some screenshots

Hello! I added them in the issue #12523

**Comment by rudydel** [comment]
> Hi @rudydel Can you add some screenshots

@chirag-madlani
To keep the discussion here: below is a screenshot of an error caused by the space characters when trying to view logs of the lineage ingestion. You can see that spaces are carried over to the API Calls:

openmetadata_airflow_error

**Comment by rudydel** [comment]
@chirag-madlani  I highlighted the issue causing the underlying Airflow errors, including the one in the previous screenshot.

lineage_ingestion_naming_issue

**Review by chirag-madlani — APPROVED** [review]

**Pull request merged**
