### PR TITLE
Add check to allow only the owner and admin to delete the post.

### LINKED ISSUE #3403: Clicking on owner in database details page redirects to blank page.
**Affected module**
UI

**Describe the bug**
Clicking on owner in database details page redirects to a blank page.

**To Reproduce**
- Assign an owner to database
- Click on assigned owner.
- Redirects to `http://localhost:8585/teams/team`

https://user-images.githubusercontent.com/83201188/158171854-c0308fbf-b02e-4c67-beda-a9ce51205284.mov

**Expected behavior**
Should redirect to the teams page

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**
NA

### PR DESCRIPTION
**Pull request by Sachin-chaurasiya**
This PR will also Fix #3403 
### Describe your changes :

I worked on issue #3160 

#
### Type of change :

- [x] Improvement
- [x] New feature

#
### Frontend Preview (Screenshots) :

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/open-source-community/developer) document.
- [x] I have performed a self-review of my own. 
- [x] I have tagged my reviewers below.
- [ ] I have commented on my code, particularly in hard-to-understand areas.
- [x] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [x] All new and existing tests passed.

#
### Reviewers
@shahsank3t, @darth-coder00 @vivekratnavel

### CODE REVIEW

**Comment by vivekratnavel** [comment]
@Sachin-chaurasiya Can we also include unit tests for this change?

**Comment by Sachin-chaurasiya** [comment]
> @Sachin-chaurasiya Can we also include unit tests for this change?

@vivekratnavel , Sure, I will add that.

**Review by darth-coder00 — APPROVED** [review]
LGTM!

**Review by ShaileshParmar11 — APPROVED** [review]
LGTM!

**Pull request merged**
