### PR TITLE
UI : Add emoji support for feed editor

### LINKED ISSUE #4678: UI: Add support for Emojis in text editors for posting messages

### PR DESCRIPTION
**Pull request by Sachin-chaurasiya**
Closes #4678 
### Describe your changes :

I worked on adding support for emojis in feed editor for posting messages.

#
### Type of change :

- [x] New feature

#
### Frontend Preview (Screenshots) :

https://user-images.githubusercontent.com/59080942/169595772-227d0fb9-b307-43e2-8ad2-6c1c9c9550f6.mov

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/open-source-community/developer) document.
- [ ] I have commented on my code, particularly in hard-to-understand areas.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [x] All new and existing tests passed.

#
### Reviewers
@open-metadata/ui

### CODE REVIEW

**Comment by harshach** [comment]
@Sachin-chaurasiya this is pretty cool. @vivekratnavel are we going to add emojis at the thread or message level?

**Review by ShaileshParmar11 — APPROVED** [review]

**Comment by Sachin-chaurasiya** [comment]
> @Sachin-chaurasiya this is pretty cool. @vivekratnavel are we going to add emojis at the thread or message level?

@harshach , This will be for all the messages that user going to post.

**Comment by harshach** [comment]
> > @Sachin-chaurasiya this is pretty cool. @vivekratnavel are we going to add emojis at the thread or message level?
> 
> @harshach , This will be for all the messages that user going to post.

@Sachin-chaurasiya makes sense but would like to have a support for reactions to threads , example heart emoji on this thread. I think we need backend API support for that @vivekratnavel 
image

**Comment by vivekratnavel** [comment]
Yes @harshach, that is our next target

**Comment by Sachin-chaurasiya** [comment]
> > > @Sachin-chaurasiya this is pretty cool. @vivekratnavel are we going to add emojis at the thread or message level?
> > 
> > 
> > @harshach , This will be for all the messages that user going to post.
> 
> @Sachin-chaurasiya makes sense but would like to have a support for reactions to threads , example heart emoji on this thread. I think we need backend API support for that @vivekratnavel image

@harshach , Yes for the reaction we will need backend support as well because we will have to keep track of user reactions of thread or post messages.

**Review by shahsank3t — APPROVED** [review]

**Pull request merged**
