### PR TITLE
chore(ui): add glossary and glossary terms count on landing page

### PR DESCRIPTION
**Pull request by Sachin-chaurasiya**
Related issue #9971 
### Describe your changes :

I worked on adding the glossaries and glossary terms count on the landing page.

#
### Type of change :

- [x] Improvement

#
### Frontend Preview (Screenshots) :
image

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/developers/contribute) document.
- [x] I have commented on my code, particularly in hard-to-understand areas.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] All new and existing tests passed.

#
### Reviewers

@open-metadata/ui

### CODE REVIEW

**Comment by harshach** [comment]
Given we are going to add storage containers this list going to be longer. Lets remove the following 
image
as these counts more useful to admins than the regular user
cc @sureshms

**Comment by Sachin-chaurasiya** [comment]
> Given we are going to add storage containers this list going to be longer. Lets remove the following image as these counts more useful to admins than the regular user cc @sureshms

@harshach , We have already added the storage containers count as containers.

image

Let me know if we want to rename it.

**Comment by harshach** [comment]
@Sachin-chaurasiya  I meant removing the following from the list
image

**Comment by Sachin-chaurasiya** [comment]
> @Sachin-chaurasiya I meant removing the following from the list image

Done @harshach .

**Review by chirag-madlani — APPROVED** [review]

**Review by harshach — APPROVED** [review]

**Pull request merged**
