### PR TITLE
Fix #9040: Remove fields such as tableQueries, tableProfile, tests, sample data as part of table fields

### LINKED ISSUE #9040: Remove fields such as tableQueries, tableProfile, tests, sample data as part of table fields
**Feature**
As part of table API, we are adding a lot of fields which can result in an unnecessary penalty on DB.
UI currently makes one big call to get all the data, which can result in heavy load times on the popular tables.
We already have extended APIs to get these additional fields. As part of this refactor we will remove unnecessary fields that can be retrieved from APIs

**Describe the task**

### PR DESCRIPTION
**Pull request by harshach**
### Describe your changes :

I worked on the ..... because ...

#
### Type of change :

- [x] Bug fix
- [x] Improvement
- [x] New feature
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation

#
### Frontend Preview (Screenshots) :
<p align="center">For frontend related change, please link screenshots of your changes preview! Optional for backend related changes.
</p>

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/developers/contribute) document.
- [ ] I have commented on my code, particularly in hard-to-understand areas.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [x] All new and existing tests passed.

#

### CODE REVIEW

**Comment by ShaileshParmar11** [comment]
Hi @harshach I have fixed the breaking changes, it seems like sampleData API is not returning sampleData, 
- I have implemented the API in UI for sampleData
- query API is working fine I have tested will push change for the same
need below details for profiler
- As we were dependent on profiler data from table API Which was returning profiler data for the table and for all the columns(latest one), need similar data via a new endpoint

**Comment by harshach** [comment]
@ShaileshParmar11 will fix these and add another api for /api/v1/table/{id}/profile/latest to get the latest results

**Comment by TeddyCr** [comment]
@harshach this will most likely require some changes on the ingestion side.

**Comment by harshach** [comment]
@TeddyCr @ayush-shah can you let me know some details on how we are using this on DQ?

**Comment by TeddyCr** [comment]
@harshach i believe it is used in python tests checking table properties have been set as expected e.g table.profile.sampleData.

**Comment by harshach** [comment]
@ShaileshParmar11 added end point for /{fqn/tableProfile/latest to get the latest profile data.

**Comment by TeddyCr** [comment]
@harshach I'll fix the python tests once the Java/Maven are green 🙂

**Comment by ShaileshParmar11** [comment]
Hi @harshach @TeddyCr I have updated UI side with new API, Whereas we are not getting data for the below endpoint
- sampleData end point is not providing data related to sample data
- profiler/latest end point is not providing any data related to profiler

**Comment by ShaileshParmar11** [comment]
Hi, I have verified after ingestion side of the change. Everything is working fine!

**Review by mohityadav766 — APPROVED** [review]

**Review by Sachin-chaurasiya — APPROVED** [review]

**Pull request merged**
