### PR TITLE
Fix #3236: Add support for secure docker compose with an env file

### LINKED ISSUE #3236: Add support for secure docker compose with an env file
**Is your feature request related to a problem? Please describe.**
We should provide an easy way for the users to bring up a secure docker compose cluster. #2807 brought in the changes required to configure secure authentication and authorization with a bunch of env variables. Now, it can be utilized fully if we add support in "metadata" cli to take an env file as input for the docker-compose project. 

**Describe the solution you'd like**
Add an option in "metadata" cli to pass env-file to docker-compose

### PR DESCRIPTION
**Pull request by vivekratnavel**
### Describe your changes :

See #3236 

To bring up a secure docker compose cluster, one can set up an env file like this and pass the env file path in command line:
```
AUTHORIZER_CLASS_NAME=org.openmetadata.catalog.security.DefaultAuthorizer
AUTHORIZER_REQUEST_FILTER=org.openmetadata.catalog.security.JwtFilter
AUTHORIZER_ADMIN_PRINCIPALS=admin
AUTHORIZER_INGESTION_PRINCIPAL=ingestion-bot
AUTHORIZER_PRINCIPAL_DOMAIN=open-metadata.org
AUTHENTICATION_PROVIDER=google
AUTHENTICATION_PUBLIC_KEY=https://www.googleapis.com/oauth2/v3/certs
AUTHENTICATION_AUTHORITY=https://accounts.google.com
AUTHENTICATION_CLIENT_ID=709849217090-n7s8oc4cvpffubraoi5vbr1s0qfboqvv.apps.googleusercontent.com
AUTHENTICATION_CALLBACK_URL=http://localhost:8585/callback
```

```
metadata docker -env-file ~/env_open_metadata -f ~/docker-compose --start
```
#
### Type of change :

- [ ] Bug fix
- [x] Improvement
- [ ] New feature
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/open-source-community/developer) document.
- [x] I have performed a self-review of my own. 
- [ ] I have tagged my reviewers below.
- [ ] I have commented on my code, particularly in hard-to-understand areas.
- [ ] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [x] All new and existing tests passed.

#

### CODE REVIEW

**Comment by harshach** [comment]
@vivekratnavel can you run the python checkstyle

**Review by akash-jain-10 — APPROVED** [review]

**Review by harshach — CHANGES_REQUESTED** [review]
Fix python checkstyle

**Comment by vivekratnavel** [comment]
@harshach @akash-jain-10 Thanks for the review. One thing to note with this patch is that when security is enabled, the initial ingestion will fail because it will not have the secret to access the secure APIs. But, if the user tries to ingest with sample-data.json with the secret key config, it will succeed.

**Comment by vivekratnavel** [comment]
I have created #3259 to add a flag to skip ingestion during startup. That should improve the user experience

**Review by harshach — APPROVED** [review]

**Pull request merged**
