### PR TITLE
Fixes #10543 : Make the modal not closable on outside click

### LINKED ISSUE #10543: UI Feedback - 1.0
Let's add here all the feedback for the 1.0 release

### PR DESCRIPTION
**Pull request by Ashish8689**
### Describe your changes:

Fix ticket comment : https://github.com/open-metadata/OpenMetadata/issues/10543#issuecomment-1482449696

I worked on making the modal not closable on the outside click across the application.

https://user-images.githubusercontent.com/66266464/227509586-ff992834-5a59-41ff-8379-2a8b790117cd.mov

#
### Type of change:

- [x] Bug fix
- [x] Improvement
- [ ] New feature
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/developers/contribute) document.
- [x] My PR title is `Fixes <issue-number>: <short explanation>`
- [ ] I have commented on my code, particularly in hard-to-understand areas. 
- [ ] For JSON Schema changes: I updated the migration scripts or explained why it is not needed.

### CODE REVIEW

**Review by chirag-madlani — APPROVED** [review]

**Review by Sachin-chaurasiya — APPROVED** [review]

**Comment by harshach** [comment]
@Ashish8689 this will be applied everywhere the description needs to be edited? like users/teams etc.. cc @chirag-madlani

**Comment by Ashish8689** [comment]
@harshach  Didn't get you on this. Like do you want to update the PR description ? or any thing else need to done.

**Comment by harshach** [comment]
@Ashish8689 this should work all the dialog boxes where we are editing text. Make sure this is not a fix for table descriptions but wherever a description needs to be edited

**Comment by Ashish8689** [comment]
@harshach yes this fix has been covered across the application for all Modal.

**Pull request merged**
