### PR TITLE
Fixes #7044 Handle database filter in ingestion pipeline when connection specifies a database from UI side  #7044

### LINKED ISSUE #7044: Handle databse filter in ingestion pipeline when connection specifies a database
When creating a new service and adding a database, database filter in the ingestion workflow will be ignore -- though nothing indicates this.

**Suggested solution**
Grey out (or remove) database filter when connection has a database value

### PR DESCRIPTION
**Pull request by ShaileshParmar11**
### Describe your changes: 

 #7044

Handle databse filter in ingestion pipeline when connection specifies a database

### When database name is not given

Screenshot 2023-03-29 at 12 14 21 AM

### When database name is given

Screenshot 2023-03-28 at 11 56 55 PM

- `ingestAllDatabases` is true
Screenshot 2023-03-29 at 12 11 10 AM

#
### Type of change:

- [ ] Bug fix
- [x] Improvement
- [ ] New feature
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/developers/contribute) document.
- [x] My PR title is `Fixes <issue-number>: <short explanation>`
- [ ] I have commented on my code, particularly in hard-to-understand areas. 
- [ ] For JSON Schema changes: I updated the migration scripts or explained why it is not needed.

- [x] I have added a test that covers the exact scenario we are fixing. For complex issues, comment the issue number in the test for future reference.

### CODE REVIEW

**Comment by harshach** [comment]
@pmbrull @ShaileshParmar11 we should show the database is configured in the database filter place. Instead of completely not showing the filter itself. Its going to be confusing for the users why the database filter suddenly disappeared

**Comment by harshach** [comment]
in redshift we ask users to enter database name as mandatory right @ulixius9 . What will happen in those cases?

**Comment by harshach** [comment]
@ShaileshParmar11 @ulixius9 
image
cc @pmbrull

**Comment by ulixius9** [comment]
@ShaileshParmar11 in case of redshift & postgres we will have to enable the database filter pattern when `ingestAllDatabases` flag is enabled

**Review by chirag-madlani — DISMISSED** [review]

**Review by harshach — APPROVED** [review]

**Pull request merged**
