### PR TITLE
Fix : Advanced search improvements

### PR DESCRIPTION
**Pull request by Sachin-chaurasiya**
### Describe your changes :

I worked on advanced search improvements
- Updated the advanced search dropdown to show the user/team display name or name.
- Updated service query field constants to show results based on the current index
- Added logic to reset the applied filter text on tab change

Test Cases:
- If the default option is present then it should be shown on click of the select box
- If no default option is present then it should not render the option menu
- Value dropdown should show related values to the current index
    - For example, if the user selects the service field and the current index is `topic_search_index`, then the value dropdown should show only service related to the topic entity.
- Applied filter text should be reset on tab change.

#
### Type of change :

- [x] Improvement

#
### Frontend Preview (Screenshots) :
image

Default Values:
image

image

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/developers/contribute) document.
- [x] I have commented on my code, particularly in hard-to-understand areas.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] All new and existing tests passed.

#
### Reviewers
@open-metadata/ui

### CODE REVIEW

**Comment by chirag-madlani** [comment]
@Sachin-chaurasiya can we add suggest changes in this one too? Initially it should show few options before start searching

**Comment by Sachin-chaurasiya** [comment]
> @Sachin-chaurasiya can we add suggest changes in this one too? Initially it should show few options before start searching

@chirag-madlani, Sure, let me check on that part.

**Comment by Sachin-chaurasiya** [comment]
> @Sachin-chaurasiya can we add suggest changes in this one too? Initially it should show few options before start searching

Done.

**Review by chirag-madlani — APPROVED** [review]
Can you mention test cases that you have covered?

**Comment by Sachin-chaurasiya** [comment]
> Can you mention test cases that you have covered?

@chirag-madlani, I have Updated the test cases, please check the PR description.

**Pull request merged**
