### PR TITLE
Fixes 18300: Get last completed job run

### PR DESCRIPTION
**Pull request by LeoLuo123**
### Describe your changes:

Fixes [18300](https://github.com/open-metadata/OpenMetadata/issues/18300)

Currently omd only ingest last successful dbt job, if there are failing dbt job due to dbt tests, the result will be never ingested by omd.

The change I am making to to let omd query last completed dbt job, either success (10) or error(20), so omd can ingest failed dbt tests and create incidents accordingly and correctly.

According to dbt official [doc](https://docs.getdbt.com/dbt-cloud/api-v2#/operations/List%20Runs), we can set `status__in` with a set of 10, 20

Filters the results to a specific set of run statuses. 1: Queued, 2: Starting, 3: Running, 10: Success, 20: Error, 30: Cancelled

I have tested the API by using Postman 

GET 
```
https://cloud.getdbt.com/api/v2/accounts/<account_id>/runs/?project_id=<project_id>&job_definition_id=<job_id>&order_by=-finished_at&limit=1&status__in=[10,20]
```

Response:

```json
{
    "status": {
        "code": 200,
        "is_success": true,
        "user_message": "Success!",
        "developer_message": ""
    },
    "data": [
        {
            "id":,
            "trigger_id": 349296538,
            "account_id":,
            "environment_id":,
            "project_id":,
            "job_definition_id":,
            "status": 20,
            "dbt_version": "versionless",
            "git_branch": "master",
            "git_sha": "33007b3127508ba1009884ca5fefe9bc3e6041eb",
            "status_message": "dbt command failed",
            "owner_thread_id": null,
            "executed_by_thread_id": "orc-dispatch-x3-1-57c87f96fb-tsnht",
            "deferring_run_id": null,
            "artifacts_saved": true,
            "artifact_s3_path": "prod/runs//artifacts/target",
            "has_docs_generated": false,
            "has_sources_generated": false,
            "notifications_sent": true,
            "blocked_by": [],
            "created_at": "2024-12-02 19:00:56.649426+00:00",
            "updated_at": "2024-12-02 19:08:39.157694+00:00",
            "dequeued_at": "2024-12-02 19:00:56.969450+00:00",
            "started_at": "2024-12-02 19:00:57.784528+00:00",
            "finished_at": "2024-12-02 19:08:39.050634+00:00",
            "last_checked_at": "2024-12-02 19:08:39.107842+00:00",
            "last_heartbeat_at": "2024-12-02 19:06:46.612584+00:00",
            "should_start_at": "2024-12-02 19:00:56.649426+00:00",
            "trigger": null,
            "job": null,
            "environment": null,
            "run_steps": [],
            "status_humanized": "Error",
            "in_progress": false,
            "is_complete": true,
            "is_success": false,
            "is_error": true,
            "is_cancelled": false,
            "duration": "00:07:42",
            "queued_duration": "00:00:01",
            "run_duration": "00:07:41",
            "duration_humanized": "7 minutes, 42 seconds",
            "queued_duration_humanized": "1 second",
            "run_duration_humanized": "7 minutes, 41 seconds",
            "created_at_humanized": "4 hours, 27 minutes ago",
            "finished_at_humanized": "4 hours, 20 minutes ago",
            "retrying_run_id": null,
            "can_retry": true,
            "retry_not_supported_reason": null,
            "job_id":,
            "is_running": null,
            "href": "https://cloud.getdbt.com/deploy//projects//runs//",
            "used_repo_cache": null
        }
    ],
    "extra": {
        "filters": {
            "limit": 1,
            "offset": 0,
            "state": "all",
            "account_id":,
            "project_id":,
            "job_definition_id":,
            "status__in": [
                10,
                20
            ]
        },
        "order_by": "-finished_at",
        "pagination": {
            "count": 1,
            "total_count": 1056
        }
    },
    "error_code": null
}
```

#
### Type of change:

- [x] Bug fix
- [ ] Improvement
- [ ] New feature
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/developers/contribute) document.
- [x] My PR title is `Fixes <issue-number>: <short explanation>`
- [ ] I have commented on my code, particularly in hard-to-understand areas. 
- [ ] For JSON Schema changes: I updated the migration scripts or explained why it is not needed.

### CODE REVIEW

**Comment by LeoLuo123** [comment]
@SumanMaharana @ulixius9 PTAL

**Review by TeddyCr — COMMENTED** [review]
PR looks good. Could you run `make py_format` and `py_format_check` so we can merge it in?

**Comment by LeoLuo123** [comment]
@TeddyCr I have applied formatting by using pre-commit, but some tests are failing. However, I am not sure whether it's due to my change since they are UI related tests. Can you take a look?

**Review by TeddyCr — APPROVED** [review]

**Comment by LeoLuo123** [comment]
@TeddyCr @SumanMaharana thanks for merging the change into main branch. Can we know when and which release version this change will be in?

**Pull request merged**
