### PR TITLE
Fix #3626 Add a config API for sandbox mode

### LINKED ISSUE #3626: Add a config API for sandbox mode
It will be good to have config support for sandbox mode to enable sandbox specific UI changes

### PR DESCRIPTION
**Pull request by harshach**
### Describe your changes :
See #3626 

#
### Type of change :

- [x] Improvement

#
### Frontend Preview (Screenshots) :
<p align="center">For frontend related change, please link screenshots of your changes preview! Optional for backend related changes.
</p>

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/open-source-community/developer) document.
- [ ] I have performed a self-review of my own. 
- [ ] I have tagged my reviewers below.
- [ ] I have commented on my code, particularly in hard-to-understand areas.
- [ ] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [x] All new and existing tests passed.

#

### CODE REVIEW

**Comment by harshach** [comment]
@vivekratnavel merging auth and authorization apis into just a single config resource which will return the following
```
{
database: null,
swagger: null,
authorizerConfiguration: {
className: "org.openmetadata.catalog.security.NoopAuthorizer",
containerRequestFilter: "org.openmetadata.catalog.security.NoopFilter",
adminPrincipals: [
"admin"
],
botPrincipals: [
"ingestion-bot"
],
principalDomain: ""
},
authenticationConfiguration: {
provider: "no-auth",
publicKey: "https://www.googleapis.com/oauth2/v3/certs",
authority: "https://accounts.google.com/",
clientId: "",
callbackUrl: "",
jwtEmail: "email"
},
elasticsearch: null,
eventHandlerConfiguration: null,
airflowConfiguration: null,
slackEventPublishers: null,
migrationConfiguration: null,
fernetConfiguration: null,
health: null,
sandboxModeEnable: false,
server: null,
logging: {},
metrics: null,
admin: null
}
```
can you double check if we really need authorization config on the UI

**Comment by vivekratnavel** [comment]
I don't think we need authorization configs for the UI. Currently, it is being used to determine if security is enabled. The UI checks if the authorization config is not pointing to Noop Authorizer 

https://github.com/open-metadata/OpenMetadata/blob/main/openmetadata-ui/src/main/resources/ui/src/auth-provider/AuthProvider.tsx#L271

@darth-coder00 Please correct me if I am wrong

**Comment by harshach** [comment]
@vivekratnavel @darth-coder00 we can figure this out by looking at authenticationConfig.provider
provider: "no-auth"

**Comment by darth-coder00** [comment]
> @vivekratnavel @darth-coder00 we can figure this out by looking at authenticationConfig.provider provider: "no-auth"

@harshach according to this comment, [#2808](https://github.com/open-metadata/OpenMetadata/pull/2808#issuecomment-1047174097), UI is fetching authentication as well as authorizer config to check for `provider: "no-auth"` or `containerRequestFilter` is empty or `containerRequestFilter: "NoopFilter"`
And consider if it is non-secure mode.

**Pull request closed without merging**
