### PR TITLE
Fixes #4664 - Introduce a type for markdown text

### LINKED ISSUE #4664: Introduce a type for markdown text
Currently, the Entity field for description uses the `string` type. Introduce a specific type called `markdown` for these fields.

### PR DESCRIPTION
**Pull request by sureshms**
### Describe your changes :

See #4664 for details

#
### Type of change :

- [x] Improvement

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/open-source-community/developer) document.
- [x] I have commented on my code, particularly in hard-to-understand areas.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [x] All new and existing tests passed.

### CODE REVIEW

**Review by vivekratnavel — APPROVED** [review]

**Comment by harshach** [comment]
@vivekratnavel @darth-coder00 does it impact UI , given in some cases we are rendering forms?

**Comment by pmbrull** [comment]
Hi @sureshms, wrapping these attributes into another object definition updates the Pydantic models. The fields are then not real strings, but a custom `Markdown` object with its own attributes. In the sample data we are then getting the following errors:
```
AttributeError: 'Markdown' object has no attribute 'strip'
```
We'll need to update quite some code on the ingestion side to address this

**Comment by sureshms** [comment]
> Hi @sureshms, wrapping these attributes into another object definition updates the Pydantic models. The fields are then not real strings, but a custom `Markdown` object with its own attributes. In the sample data we are then getting the following errors:
> 
> ```
> AttributeError: 'Markdown' object has no attribute 'strip'
> ```
> 
> We'll need to update some code on the ingestion side to address this

Hold off on this for this release?

**Comment by pmbrull** [comment]
> > Hi @sureshms, wrapping these attributes into another object definition updates the Pydantic models. The fields are then not real strings, but a custom `Markdown` object with its own attributes. In the sample data we are then getting the following errors:
> > ```
> > AttributeError: 'Markdown' object has no attribute 'strip'
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > We'll need to update some code on the ingestion side to address this
> 
> Hold off on this for this release?

Just pushed some changes. At first glance, I thought it would be more painful. Sample data and a random SQL connector both ran fine. Pinging @ayush-shah as I might be missing something, but otherwise LGTM

**Comment by vivekratnavel** [comment]
We are not generating typescript files for every change in json schema, so it currently doesn't impact UI. But, I would like to hold off on this until we make typescript generation as part of the front-end build.

@shahsank3t @darth-coder00   Can we prioritize the generation of typescript files on the fly for every build?

**Comment by sureshms** [comment]
@vivekratnavel will wait for your go ahead

**Comment by vivekratnavel** [comment]
@sureshms This patch should be good to go now. Thank you for your patience!

**Comment by sureshms** [comment]
@pmbrull and @harshach, I am going to commit this change. Hope we can take care of py-tests...

**Pull request merged**
