### PR TITLE
Fixes 18349: proper version comparison

### PR DESCRIPTION
**Pull request by imishchuk-tsgs**
### Describe your changes:

Fixes [18349](https://github.com/open-metadata/OpenMetadata/issues/18349)

I worked on `openmetadata-airflow-apis/opendata_managed_apis/api/utils.py` because reported bug prevented DAG deployment in Airflow `2.10.2`.

Changes were tested by using updated file in custom Airflow image and creating DAG from OM UI.

#
### Type of change:

- [x] Bug fix
- [ ] Improvement
- [ ] New feature
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation

#
### Checklist:
- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/developers/contribute) document.
- [x] My PR title is `Fixes <issue-number>: <short explanation>`
- [ ] I have commented on my code, particularly in hard-to-understand areas. 
- [ ] For JSON Schema changes: I updated the migration scripts or explained why it is not needed.

- [ ] I have added a test that covers the exact scenario we are fixing. For complex issues, comment the issue number in the test for future reference.

### CODE REVIEW

**Review by IceS2 — COMMENTED** [review]
Looks good. If you could fix the checkstyle I'd appreciate it (=

**Comment by imishchuk-tsgs** [comment]
Hey @IceS2 
Python checkstyle is happy now

**Comment by imishchuk-tsgs** [comment]
Hey @IceS2 
When you have time, can you take a look, please?

**Comment by imishchuk-tsgs** [comment]
@pmbrull @IceS2 @harshach 
Anyone, please?

**Comment by jgrocha** [comment]
Thanks @imishchuk-tsgs 

Found this issue when testing OM 1.6.0.rc3 with Airflow 2.10.3. I've applied this fix and it work.

This is a bug, since version strings can not be compared literally. For Python, `"2.6" > "2.10.3"`.

**Review by pmbrull — APPROVED** [review]

**Comment by pmbrull** [comment]
thanks for the PR!

**Pull request merged**
