### PR TITLE
add pt-br translation

### PR DESCRIPTION
**Pull request by luis-fnogueira**
### Describe your changes:

Add Brazilian Portuguese translation

I worked on ... because ...

#
### Type of change:

- [ ] Bug fix
- [x] Improvement
- [ ] New feature
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/developers/contribute) document.
- [ ] My PR title is `Fixes <issue-number>: <short explanation>`
- [ ] I have commented on my code, particularly in hard-to-understand areas. 
- [ ] For JSON Schema changes: I updated the migration scripts or explained why it is not needed.

### CODE REVIEW

**Comment by harshach** [comment]
hi @luis-fnogueira thanks for the PR. Are you planning on adding the rest of the translation as well?

**Comment by luis-fnogueira** [comment]
> hi @luis-fnogueira thanks for the PR. Are you planning on adding the rest of the translation as well?

Hi, Harsha! Yes, I'm slowly doing the entire work.

**Comment by sureshms** [comment]
@luis-fnogueira Chat-GPT is quite good at doing localization, if you want to try it out.
image

**Comment by luis-fnogueira** [comment]
> @luis-fnogueira Chat-GPT is quite good at doing localization, if you want to try it out. image

Ok, I'll try it!

**Comment by luis-fnogueira** [comment]
@harshach @sureshms I finished the json file! Isn't it necessary to change the `openmetadata-ui/src/main/resources/ui/src/utils/i18next/i18nextUtil.ts `anymore? This [doc ](https://docs.open-metadata.org/how-to-guides/how-to-add-language-support )has changed.

**Comment by luis-fnogueira** [comment]
> @harshach @sureshms I finished the json file! Isn't it necessary to change the `openmetadata-ui/src/main/resources/ui/src/utils/i18next/i18nextUtil.ts `anymore? This [doc ](https://docs.open-metadata.org/how-to-guides/how-to-add-language-support)has changed.

Also, is there a way for me to see the changes in the ui locally?

**Comment by harshach** [comment]
@luis-fnogueira Thanks for the quick turn around. You don't need to change the code.
To see the changes locally you need to build the code , here are the changes https://docs.open-metadata.org/developers/contribute/build-code-and-run-tests

**Comment by luis-fnogueira** [comment]
> @luis-fnogueira Thanks for the quick turn around. You don't need to change the code. To see the changes locally you need to build the code , here is the doc on how to build https://docs.open-metadata.org/developers/contribute/build-code-and-run-tests

Alright! Thanks a lot! So, I think if the tests pass you can merge it. Let me know if anything else is needed!

**Review by harshach — APPROVED** [review]

**Pull request merged**
