### PR TITLE
FIx #7477 Add logic to fetch log use react-lazylog

### LINKED ISSUE #7477: Add logic to fetch log use react-lazylog
Large logs cause the browser to crash. We should use https://www.npmjs.com/package/react-lazylog to parse the logs

### PR DESCRIPTION
**Pull request by Sachin-chaurasiya**
### Describe your changes :

I worked on issue #7477 

#
### Type of change :

- [x] Bug fix

#
### Frontend Preview (Screenshots) :

https://user-images.githubusercontent.com/59080942/195344585-91328e5f-d472-488e-bdb8-1dbcb914efb5.mov

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/developers/contribute) document.
- [x] I have commented on my code, particularly in hard-to-understand areas.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] All new and existing tests passed.

#
### Reviewers
@open-metadata/ui

### CODE REVIEW

**Review by chirag-madlani — APPROVED** [review]
Looks good @Sachin-chaurasiya 
Can you check if we can use entire space from the screen to show more upfront?

**Comment by Sachin-chaurasiya** [comment]
> Looks good @Sachin-chaurasiya Can you check if we can use the entire space from the screen to show more upfront?

Sure @chirag-madlani .

**Comment by Sachin-chaurasiya** [comment]
> Looks good @Sachin-chaurasiya Can you check if we can use entire space from the screen to show more upfront?

@chirag-madlani, Something like this?
image

**Comment by chirag-madlani** [comment]
> > Looks good @Sachin-chaurasiya Can you check if we can use entire space from the screen to show more upfront?
> 
> @chirag-madlani, Something like this? image

Looks good

**Comment by harshach** [comment]
@Sachin-chaurasiya @chirag-madlani lets not open a dialog box for logs. Lets use similar styling as we see in GitHub workflow
image
Also either we update the logs as it happens using web socket cc @mohityadav766 @nahuelverdugo or we poll periodically to fetch new logs and give an option to refresh the logs without needing to refresh the page

**Pull request merged**
