### PR TITLE
Fixes #13803 : Reduce the number of call in case of columns

### LINKED ISSUE #13803: [UI] Data Insight Layout looks broken in case of large number of assets
**Affected module**
Does it impact the UI, backend or Ingestion Framework?

**Describe the bug**
Please see the video attached.

https://github.com/open-metadata/OpenMetadata/assets/105265192/0030d260-04ae-489d-8880-ddd1d4d3de7e

**To Reproduce**

Screenshots or steps to reproduce

**Expected behavior**

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

### PR DESCRIPTION
**Pull request by mohityadav766**
### Describe your changes:

Fixes #13803
- Reduced the number of calls to one.
- Removed un-necessary tag and glossary calls on each call to specific tag based on source , 

Additional :-
- Add AppMarketPlace + AppResource Test
- Added restore + delete flow handling for Application 
- Fixed some of the issue in ApplicationFlow

#
### Type of change:

- [ ] Bug fix
- [ ] Improvement
- [ ] New feature
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/developers/contribute) document.
- [ ] My PR title is `Fixes <issue-number>: <short explanation>`
- [ ] I have commented on my code, particularly in hard-to-understand areas. 
- [ ] For JSON Schema changes: I updated the migration scripts or explained why it is not needed.

### CODE REVIEW

**Review by harshach — DISMISSED** [review]

**Comment by harshach** [comment]
@mohityadav766 lets add these changes to other places where we are fetching tags

**Comment by mohityadav766** [comment]
> @mohityadav766 lets add these changes to other places where we are fetching tags

@harshach added for other entities as well

**Comment by harshach** [comment]
@mohityadav766 there are bunch of tests failing. Can you take a look
@pmbrull we need a perf test for tables with 1000s of column and each column with 2-4 tags/terms and see if this PR improved the perf

**Review by harshach — APPROVED** [review]

**Comment by mohityadav766** [comment]
Merging this here , the failure seems to come from delete_recursiveTest() when the getContainer() returns a different Container then what we attached with , will need fixing those in a separate PR cc @harshach

**Pull request merged**
