### PR TITLE
#14134: supported retention period in table entity

### LINKED ISSUE #14134: retention period in UI
**Affected module**
Does it impact the UI, backend or Ingestion Framework?
UI

**Describe the bug**
not showing retention period in the UI when I patch retention period to a table
**To Reproduce**

Screenshots or steps to reproduce

**Expected behavior**
showing retention period in the UI when I patch retention period to a table

**Version:**
 - Python version: 
 - OpenMetadata version: [e.g. 0.8] 1.2.2
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**
https://openmetadata.slack.com/archives/C02B6955S4S/p1701132502435379

### PR DESCRIPTION
**Pull request by Ashish8689**
### Describe your changes:

Fixes #14134

- I worked on supported retention period in table entity

https://github.com/open-metadata/OpenMetadata/assets/66266464/59e53efe-89a7-45d4-927c-4cecf7a533e5

#
### Type of change:

- [ ] Bug fix
- [x] Improvement
- [ ] New feature
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/developers/contribute) document.
- [ ] My PR title is `Fixes <issue-number>: <short explanation>`
- [ ] I have commented on my code, particularly in hard-to-understand areas. 
- [ ] For JSON Schema changes: I updated the migration scripts or explained why it is not needed.

### CODE REVIEW

**Review by chirag-madlani — DISMISSED** [review]

**Comment by harshach** [comment]
@Ashish8689 "days" not the only unit, "hours" is also an option.
Here is the format ISO 8601 format in UTC. Example - `P23DT23H`.

**Comment by Ashish8689** [comment]
@harshach updated the retention period with hours too!

**Comment by chirag-madlani** [comment]
@harshach Can you review this again?

**Review by chirag-madlani — APPROVED** [review]

**Comment by chirag-madlani** [comment]
@harshach Need your approval here

**Review by chirag-madlani — APPROVED** [review]

**Review by chirag-madlani — APPROVED** [review]

**Review by mohityadav766 — APPROVED** [review]

**Review by harshach — APPROVED** [review]

**Pull request merged**
