### PR TITLE
Fix #6782: Separate TableProfile and ColumnProfile api calls

### LINKED ISSUE #6782: Separate TableProfile and ColumnProfile api calls
**Feature**
Current APIs give the entire response of TableProfile, which includes column profile details as well. With the new UI we are building per column dashboard, to get this data UI has to make a call for all the columns, which is unnecessary and can cause performance issues when the table has a lot of columns.

**Describe the task**
In this issue, we add a createTableProfile request such that the client can send a bulk of table and column profiles in a single request. During the update, we separate them out into their own extensions.
clients can use FQN of table or column to fetch the relevant profiles. This also affects the Pipeline statuses and TestCase statuses all of them needs to use FQN of Pipeline or Testcase, respectively, to get the pipeline results and test case results
cc @pmbrull (may require changes on any pipeline connectors that are inputting the pipeline status) /api/v1/pipeline/{fqn}/status (PUT, DELETE, LIST)
@TeddyCr for testcase results /api/v1/testCase/{fqn}/status (PUT, DELETE, LIST)

@ShaileshParmar11 this requires address pipeline status UI as well.

### PR DESCRIPTION
**Pull request by harshach**
### Describe your changes :

I worked on the ..... because ...

Fixes #6782

#
### Type of change :

- [x] Improvement

#
### Frontend Preview (Screenshots) :
<p align="center">For frontend related change, please link screenshots of your changes preview! Optional for backend related changes.
</p>

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/developers/contribute) document.
- [ ] I have commented on my code, particularly in hard-to-understand areas.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [x] All new and existing tests passed.

#

### CODE REVIEW

**Comment by TeddyCr** [comment]
@harshach are the changes to the profiler necessary for this release? I am thinking we should try to stabilize what we have before making another update to the profiler, wdyt?

**Comment by harshach** [comment]
@TeddyCr for UI whenever the column level dashboard is showing we are returning all the data that is there for entire table. If the table has 20 + columns this will be lot of data.
Also from profiler standpoint not much changing except for CreateTableProfile which contains tableProfile and list<columnProfiles> similar to before

**Comment by harshach** [comment]
@ShaileshParmar11 its failing on UI tests, tableProfile changed to profile in fields, please check

**Comment by ShaileshParmar11** [comment]
> @ShaileshParmar11 its failing on UI tests, tableProfile changed to profile in fields, please check

Ill have a look

**Comment by pmbrull** [comment]
pushed ingestion changes for the PipelineStatus. Thanks!

**Comment by ShaileshParmar11** [comment]
Hello @harshach I have updated UI as per the new schema and API, but I have one concern, earlier we use to get `profileSample` in the table profiler but it seems like we are not getting that information now!

**Comment by ShaileshParmar11** [comment]
@TeddyCr can you check for sample data of the profiler, it's failing!

**Comment by TeddyCr** [comment]
@ShaileshParmar11 [this](https://github.com/open-metadata/OpenMetadata/pull/6827) PR will fix it 🙂

**Comment by TeddyCr** [comment]
@harshach it looks like there is an issue with the GET protocol of this endpoint `http://localhost:8585/api/v1/tables/{fqn}/columnProfile`.

If I send a request to `http://localhost:8585/api/v1/tables/{id}/tableProfile` with the below body

```json
{
    "tableProfile": {
        "columnCount": 150,
        "timestamp": 1661154206
    },
    "columnProfile": [
        {
            "name": "completed_first_order_at",
            "valuesCount": 8076533.0,
            "nullCount": 0.0,
            "nullProportion": 0.0,
            "uniqueCount": 7076543.0,
            "uniqueProportion": 0.765432,
            "distinctCount": 7076543.0,
            "distinctProportion": 0.765432,
            "min": "2018-01-01T23:45:21Z",
            "max": "2018-04-09T01:01:54Z",
            "timestamp": 1661154206
        }
    ]
}
```

I get the following response when sending a GET request to `http://localhost:8585/api/v1/tables/{fqn}/columnProfile`

```json
{
    "data": [],
    "paging": {
        "total": 0
    }
}
```

`tableProfile` does return data

```json
{
    "data": [
        {
            "timestamp": 1661154206,
            "columnCount": 150.0
        },
}
```

**Review by TeddyCr — APPROVED** [review]

**Review by ShaileshParmar11 — APPROVED** [review]

**Pull request merged**
