### PR TITLE
Generate Code Coverage with Jacoco

### PR DESCRIPTION
**Pull request by mithmatt**
### Describe your changes :

I worked on this change to enable code coverage report to be generated by mvn

```
> mvn test
> open catalog-rest-service/target/site/jacoco/index.html
```

image

#
### Type of change :

- [ ] Bug fix
- [x] Improvement
- [ ] New feature
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation

#
### Frontend Preview (Screenshots) :
<p align="center">For frontend related change, please link screenshots of your changes preview! Optional for backend related changes.
</p>

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/open-source-community/developer) document.
- [x] I have performed a self-review of my own. 
- [x] I have tagged my reviewers below.
- [ ] I have commented on my code, particularly in hard-to-understand areas.
- [x] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [x] All new and existing tests passed.

#
### Reviewers

@sureshms @harshach @amiorin @pmbrull

### CODE REVIEW

**Comment by mithmatt** [comment]
Future enhancements:
- Report coverage on PRs with Github actions
- Coverage for python

**Review by amiorin — APPROVED** [review]

**Comment by pmbrull** [comment]
@amiorin @mithmatt Should we add SonarCloud as well? Love the tool and it is great for vulnerabilities as well

**Comment by mithmatt** [comment]
> @amiorin @mithmatt Should we add SonarCloud as well? Love the tool and it is great for vulnerabilities as well.
> 
> https://sonarcloud.io/ it is free for OpenSource

Yes, we should add in sonarcloud 

> @amiorin @mithmatt Should we add SonarCloud as well? Love the tool and it is great for vulnerabilities as well.
> 
> https://sonarcloud.io/ it is free for OpenSource

+1 to SonarCloud - this is a great tool that goes well beyond the typical code coverage metrics and vulnerability analysis 

I did look around SonarCloud and Github Labels for Coverage Report when I was enabling Jacoco reports. 
However the set up would/may require someone within the [organization](https://github.com/open-metadata) owning the repository to set it up (I'm not a member myself). The steps require some auth/secrets if I'm not mistaken.

**Comment by pmbrull** [comment]
> 
> 
> 
> 
> > @amiorin @mithmatt Should we add SonarCloud as well? Love the tool and it is great for vulnerabilities as well.
> 
> > 
> 
> > https://sonarcloud.io/ it is free for OpenSource
> 
> 
> 
> +1 to SonarCloud - this is a great tool that goes well beyond the typical code coverage metrics and vulnerability analysis 
> 
> 
> 
> I did look around SonarCloud and Github Labels for Coverage Report when I was enabling Jacoco reports. 
> 
> However the set up would/may require someone within the [organization](https://github.com/open-metadata) owning the repository to set it up (I'm not a member myself). The steps require some auth/secrets if I'm not mistaken.

Yeah, we might need to store them as secrets in git and pick them up during CI. I did use sonar plugin in mvn before so might be easy to setup

**Pull request merged**
