### PR TITLE
Fix #6917: startTs & endTs filters providing paginated data

### LINKED ISSUE #6917: startTs & endTs filters providing paginated data
## Backend

`http://localhost:3000/api/v1/testCase/sample_data.ecommerce_db.shopify.dim_address.shop_id.column_value_max_to_be_between/testCaseResult?startTs=1660197342&endTs=1661406942`

image

### Below are the some of end point where we are using startTs & endTs
- http://localhost:8585/api/v1/testCase
- http://localhost:8585/api/v1/testCase/{fqn}/testCaseResult
- http://localhost:8585/api/v1/tables/{fqn}/columnProfile
- http://localhost:8585/api/v1/tables/{fqn}/tableProfile

## UI
- Replace the max limit for API calls once this is fixed from API

### PR DESCRIPTION
**Pull request by harshach**
### Describe your changes :

I worked on the ..... because ...
Closes #6917 
#
### Type of change :

- [x] Improvement

#
### Frontend Preview (Screenshots) :
<p align="center">For frontend related change, please link screenshots of your changes preview! Optional for backend related changes.
</p>

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/developers/contribute) document.
- [ ] I have commented on my code, particularly in hard-to-understand areas.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [x] All new and existing tests passed.

#

### CODE REVIEW

**Comment by harshach** [comment]
@TeddyCr not sure if you are using these apis for python, can you take a look

**Review by vivekratnavel — APPROVED** [review]

**Comment by ShaileshParmar11** [comment]
Added UI side of changes, It's working fine with updated API support! Thanks @harshach

**Comment by TeddyCr** [comment]
> @TeddyCr not sure if you are using these apis for python, can you take a look

Looking at it

**Comment by TeddyCr** [comment]
@harshach this endpoint `/testCase/{testCaseFqn}/testCaseResult`is throwing a 500. You can check it if you spin up the server and run the below command

```zsh
curl --location --request GET 'http://localhost:8585/api/v1/testCase/sample_data.ecommerce_db.shopify.dim_address.last_name.column_values_to_match_regex/testCaseResult'
```


Screenshot 2022-09-21 at 7 32 58 AM

**Comment by harshach** [comment]
@TeddyCr startTs and endTs is a required field now. If you are not passing we will run into an error. I am adding validations to throw a better error

**Comment by TeddyCr** [comment]
> @TeddyCr startTs and endTs is a required field now. If you are not passing we will run into an error. I am adding validations to throw a better error

@harshach could we also mark it as required in swagger? 
Screenshot 2022-09-21 at 7 59 13 AM

**Pull request merged**
