### PR TITLE
Teradata Connector

### LINKED ISSUE #15756: Connector for Teradata Vantage
Hi, Having checked the [available database connectors](https://docs.open-metadata.org/v1.3.x/connectors/database), I have noticed there is no connector for Teradata. Teradata, or Teradata Vantage, is one of long-seller data warehouse for enterprise world wide. Therefore, I would like to request Teradata connctor like any other well known databases.

### PR DESCRIPTION
**Pull request by gpby**
### Supporting Teradata Vantage:

Fixes #15756

Here is a beta version of Teradata Database / Teradata Vantage Connector 
It supports only Metadata and Profiler ingestion

Known limitations:
- No columns info for Views (only ColumnName)
- Unable to parse DDL for views for some cases: REPLACE VIEW (only CREATE VIEW supported), LOCKING .. FOR ACEESS, etc. Third party library sqlparse should be adopted for Teradata specific.
- There are no schemas in Teradata only Databases but from entity point of view Teradara Database is OpenMetadata Schema. So Database for each Teradata object in OM will be default and Terdata DatabaseName used as OM Schema

### Type of change:
- [x] New feature

### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/developers/contribute) document.
- [x] My PR title is `Fixes 15756: Support Teradata Connector`
- [x] I have commented on my code, particularly in hard-to-understand areas. 
- [x] For JSON Schema changes: I updated the migration scripts or explained why it is not needed.

- [ ] The issue properly describes why the new feature is needed, what's the goal, and how we are building it. Any discussion
    or decision-making process is reflected in the issue.
- [ ] I have updated the documentation.
- [ ] I have added tests around the new logic.

### CODE REVIEW

**Comment by harshach** [comment]
hi @gpby thank you for the contribution. We will review and merge it in

**Comment by pmbrull** [comment]
hi @gpby, thanks a lot for the contribution! Appreciate the effort!

A couple of comments here:
- You might need to run `make py_format` to ensure CI passes
- We might need your help with the docs. For example, [here](https://github.com/open-metadata/OpenMetadata/blob/main/openmetadata-docs/content/v1.4.x/connectors/database/athena/index.md) you can find the documentation for Athena. Basically, we need to ensure we direct users to the proper permissions and field descriptions. This can be a followup PR.
- Re the lineage limitations, if you could please share a few queries as a comment in this issue https://github.com/open-metadata/OpenMetadata/issues/7427, it'll help us make the necessary enhancements to the lineage parsing module to add proper support for Teradata's dialect

Thanks!

**Comment by gpby** [comment]
1. I've done `make py_format`
2. I'm still working on documentattion
3. I'll add sql examples with parsing errors

**Review by pmbrull — APPROVED** [review]
Thanks @gpby, this LGTM. We can add the docs to another PR. Appreciate the effort

**Pull request merged**
