### PR TITLE
Fix bugs in semantic version

### PR DESCRIPTION
**Pull request by anhnguyenphung**
### Describe your changes :

Fix bugs in semantic version, for going from current version to next major version.

#
### Type of change :

- [x] Bug fix

#
### Frontend Preview (Screenshots) :
<p align="center">For frontend related change, please link screenshots of your changes preview! Optional for backend related changes.
</p>

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/open-source-community/developer) document.
- [x] I have commented on my code, particularly in hard-to-understand areas.
- [x] I have added tests that prove my fix is effective or that my feature works.

#

### CODE REVIEW

**Comment by harshach** [comment]
@anhnguyenphung can you provide some examples of what would be minor and major versions will look like

**Comment by anhnguyenphung** [comment]
@harshach For example, currently if a current version is 2.3 and the next version is a major version, the version will be 3.3, which does not conform to the semantic version.  I propose the fix that makes the next version will be 3.0

**Review by harshach — DISMISSED** [review]

**Comment by harshach** [comment]
@anhnguyenphung can you please add a unit test around this code. It doesn't need to be an integration test just a unit test would be good of what will happen around the boundary conditions

**Comment by anhnguyenphung** [comment]
@harshach Yes I can do that

**Comment by harshach** [comment]
@anhnguyenphung checking to see if you are interested in carrying this work?

**Comment by anhnguyenphung** [comment]
@harshach Yes, I am interested in carrying out the work if needed. As I mentioned before, the problem here is that the next major version is calculated incorrectly, and it can be fixed with some minor changes.

**Pull request closed without merging**
