### PR TITLE
Fixes 14528: skip statuses for tasks that are no longer present in Airflow DAG

### PR DESCRIPTION
**Pull request by mgorsk1**
### Describe your changes:

Fixes https://github.com/open-metadata/OpenMetadata/issues/14528

I worked on filtering out task instances which are related to tasks no longer present in serialized dag object because fetching statuses for such tasks results in errors during ingestion.

#
### Type of change:

- [x] Bug fix
- [ ] Improvement
- [ ] New feature
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/developers/contribute) document.
- [x] My PR title is `Fixes <issue-number>: <short explanation>`
- [x] I have commented on my code, particularly in hard-to-understand areas. 
- [] For JSON Schema changes: I updated the migration scripts or explained why it is not needed.

### CODE REVIEW

**Review by harshach — DISMISSED** [review]

**Comment by harshach** [comment]
@mgorsk1 thanks for the contribution.

**Comment by harshach** [comment]
@mgorsk1 can you please fix style check failures, looks like test case is also failing because of the change 
image

**Comment by mgorsk1** [comment]
Hey @harshach I've addressed whatever was brought up by CI, now `make py_format py_format_check` return issues not related to my change:

```
@mgorsk1 ➜ /workspaces/OpenMetadata (fix/do_not_fetch_old_task_statuses_from_airflow) $ make py_format py_format_check
pycln ingestion/ ./openmetadata-airflow-apis/ --config ingestion/pyproject.toml
Looks good! ✨ 🍰 ✨
1106 files left unchanged.
isort ingestion/ ./openmetadata-airflow-apis/ --settings-file ingestion/pyproject.toml
Skipped 1 files
black ingestion/ ./openmetadata-airflow-apis/ --config ingestion/pyproject.toml
All done! ✨ 🍰 ✨
1106 files left unchanged.
pycln ingestion/ ./openmetadata-airflow-apis/ --diff --config ingestion/pyproject.toml
Looks good! ✨ 🍰 ✨
1106 files would be left unchanged.
isort --check-only ingestion/ ./openmetadata-airflow-apis/ --settings-file ingestion/pyproject.toml
Skipped 1 files
black --check --diff ingestion/ ./openmetadata-airflow-apis/ --config ingestion/pyproject.toml
All done! ✨ 🍰 ✨
1106 files would be left unchanged.
PYTHONPATH=":ingestion/plugins" pylint --rcfile=ingestion/pyproject.toml --fail-under=10 ingestion/src/metadata --ignore-paths ingestion/src/metadata/generated || (echo "PyLint error code $?"; exit 1)
************* Module ingestion.source.dashboard.looker.metadata
ingestion/src/metadata/ingestion/source/dashboard/looker/metadata.py:230:0: I0021: Useless suppression of 'no-member' (useless-suppression)
************* Module antlr.split_listener
ingestion/src/metadata/antlr/split_listener.py:24:4: C0103: Method name "enterQuotedName" doesn't conform to snake_case naming style (invalid-name)
ingestion/src/metadata/antlr/split_listener.py:27:4: C0103: Method name "enterUnquotedName" doesn't conform to snake_case naming style (invalid-name)
ingestion/src/metadata/antlr/split_listener.py:38:4: C0103: Method name "enterEntityAttribute" doesn't conform to snake_case naming style (invalid-name)
ingestion/src/metadata/antlr/split_listener.py:41:4: C0103: Method name "enterEntityType" doesn't conform to snake_case naming style (invalid-name)
ingestion/src/metadata/antlr/split_listener.py:44:4: C0103: Method name "enterEntityField" doesn't conform to snake_case naming style (invalid-name)
ingestion/src/metadata/antlr/split_listener.py:47:4: C0103: Method name "enterEntityFqn" doesn't conform to snake_case naming style (invalid-name)

--------------------------------------------------------------------
Your code has been rated at 10.00/10 (previous run: 10.00/10, +0.00)

PyLint error code 16
make: *** [ingestion/Makefile:53: py_format_check] Error 1
```

**Comment by harshach** [comment]
Thanks for your contributions  @mgorsk1

**Comment by mgorsk1** [comment]
sure, always a pleasure 🤝🏼

**Pull request merged**
