### PR TITLE
Fixes #5866 -- Implement Support for Median Metric

### LINKED ISSUE #5866: Median Metric Needs to be Ran Individually for Certain Querying Engine
## Context
At least Redshift and BQ require the median function to be ran in isolation. 

## A.C.
Logic has been added to run the median metric appropriately

### PR DESCRIPTION
**Pull request by TeddyCr**
### Describe your changes :
This PR fixes #5866 and implement support for Median. It also implements the concept of window metrics as these types of metrics may require to run within a special context (i.e. executed by themselves for ease of implementation)

#
### Type of change :

- [ ] Bug fix
- [x] Improvement
- [ ] New feature
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation

#
### Frontend Preview (Screenshots) :
Screenshot 2022-07-06 at 10 54 59 AM

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/open-source-community/developer) document.
- [x] I have commented on my code, particularly in hard-to-understand areas.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] All new and existing tests passed.

#
### Reviewers
Ingestion: @open-metadata/ingestion

### CODE REVIEW

**Comment by TeddyCr** [comment]
> Hi @TeddyCr could you please expand on the definition of a WindowMetric? What is the difference functionally from a static metric?

Hey @pmbrull it will be all the metrics such as `OVER()` or `WITHIN GROUP`. Often needs to ran a specific way (i.e. group a specific field, etc.). As static metrics are ran all together, iterating over window metrics and executing them individually seems easier.

**Comment by pmbrull** [comment]
> > Hi @TeddyCr could you please expand on the definition of a WindowMetric? What is the difference functionally from a static metric?
> 
> Hey @pmbrull it will be all the metrics computed using window functions such as `OVER()` or `WITHIN GROUP`. Often needs to ran a specific way (i.e. group a specific field, etc.). As static metrics are ran all together, iterating over window metrics and executing them individually seems easier.

Is there any limitation on running them together with the static metrics? I was imagining Window Metrics as our own abstraction that could check the evolution of any given metric over any number of days (by checking our results history).

Not that we need to use Window Metrics for that, but just thinking if there is any real benefit of splitting these things out or if we can just use SQA syntax to handle whatever it is needed. If the issue is related to isolation (as the ticket you linked), maybe we can just call this "isolatedMetrics" to help us understand our technical approach on this

**Comment by TeddyCr** [comment]
> > > Hi @TeddyCr could you please expand on the definition of a WindowMetric? What is the difference functionally from a static metric?
> > 
> > 
> > Hey @pmbrull it will be all the metrics computed using window functions such as `OVER()` or `WITHIN GROUP`. Often needs to ran a specific way (i.e. group a specific field, etc.). As static metrics are ran all together, iterating over window metrics and executing them individually seems easier.
> 
> Is there any limitation on running them together with the static metrics? I was imagining Window Metrics as our own abstraction that could check the evolution of any given metric over any number of days (by checking our results history).
> 
> Not that we need to use Window Metrics for that, but just thinking if there is any real benefit of splitting these things out or if we can just use SQA syntax to handle whatever it is needed. If the issue is related to isolation (as the ticket you linked), maybe we can just call this "isolatedMetrics" to help us understand our technical approach on this

We can definitely execute them with the static metric, though it would add additional complexity. There is also, more specifically the Redshift (most likely Postgres) where `percentil_cont()` is throwing an error if ran with additional metrics.

**Comment by TeddyCr** [comment]
> Thanks @TeddyCr for the clarification. Not a direct drawback, just wanted to understand the grouping :) My counter-offer here would be to add these into `queryMetrics`, such as the `histogram`. Those are planned to be metrics that require a full query (Select ... from ... etcetc) or a series of queries. The main difference with static metrics is that `static` metrics can potentially be run all together in a single query. Query metrics are run one after each other.
> 
> Do you think that this would already handle the case of the median? Otherwise, we can keep it as is.

Yes, that was my hesitation. My rational was that window function don't necessarily require full custom query, they are supported by sqlalchemy. Something like this `func.row_number().over(order_by='x')` is a window function and is natively supported by SQA, wdyt?

**Comment by pmbrull** [comment]
oki let's leave it with window naming 👌 Should we then move the `median.py` into `window` instead of `static` module?

**Comment by TeddyCr** [comment]
> oki let's leave it with window naming 👌 Should we then move the `median.py` into `window` instead of `static` module?

Good point, let me do that. 🙂

**Comment by pmbrull** [comment]
amazing thanks for the explanations @TeddyCr

**Pull request merged**
