### PR TITLE
Fixes #10543 - Reorder Precision and Scale columns in Table Schema UI  

### LINKED ISSUE #10543: UI Feedback - 1.0
Let's add here all the feedback for the 1.0 release

### PR DESCRIPTION
**Pull request by ksirmons**
### Describe your changes:

Fixes #10543

I worked on reordering precision and schema because they are out of order compared to how you define a decimal in most sql languages.

#
### Type of change:

- [ ] Bug fix
- [x] Improvement
- [ ] New feature
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/developers/contribute) document.
- [x] My PR title is `Fixes <issue-number>: <short explanation>`
- [ ] I have commented on my code, particularly in hard-to-understand areas. 
- [ ] For JSON Schema changes: I updated the migration scripts or explained why it is not needed.

### CODE REVIEW

**Comment by ShaileshParmar11** [comment]
Hello @ksirmons Thanks for the PR, but currently We are planning to remove the column of precision and scale, as we are already showing it with dataType, please find the below screenshot for the same, would you like to update your PR with those changes?
image

**Comment by ksirmons** [comment]
Why would you updated the text to show decimal(scale, precision)?

MSSQL, MySql, Hive, Impala, Presto (any any other database that I can remember) all define the decimal datatype like decimal (precision, scale ).

To me it doesn't make sense to swap these numbers.  It just causes confusion IMHO.

Keith

**Comment by harshach** [comment]
@ksirmons our goal is to put everything under type not have 2 more columns for scale and precision.
as you said we will show datatype(precision, scale)  will that address your concerns?

**Comment by ShaileshParmar11** [comment]
Hi @ksirmons, as decided we are going to remove the ordinal position, precision and scale column, would you like to update your PR with this change? I will merge it!

**Comment by ShaileshParmar11** [comment]
It take care in https://github.com/open-metadata/OpenMetadata/pull/11141 PR

**Pull request closed without merging**
