### PR TITLE
Adds documentation about the Prefect OpenMetadata integration package

### PR DESCRIPTION
**Pull request by anna-geller**
### Changes
- Updates the `OpenMetadata & Prefect` documentation page to leverage the `prefect-openmetadata` package https://github.com/PrefectHQ/prefect-openmetadata 
- This package is a result of OpenMetadata feedback from https://github.com/open-metadata/OpenMetadata/pull/5127 - the more pluggable package setup should allow us better manage dependencies and make it easier to add new functionality such as exposing workflow execution metadata from Prefect

### Type of change
- [x] Documentation
- [x] Code changes are reflected in a separate integration package https://pypi.org/project/prefect-openmetadata/  

### Checklist:
- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/open-source-community/developer) document.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by harshach** [comment]
Thanks @anna-geller for the PR. @ShilpaVernekar can you please review

**Comment by anna-geller** [comment]
> Thanks @anna-geller
> @harshach  - I've reviewed the doc and merged the changes in GitBook.
> 
> Please take a look at this section on [7. Schedule your metadata ingestion flows](https://docs.open-metadata.org/overview/run-openmetadata-with-prefect#7.-schedule-your-metadata-ingestion-flows-with-prefect)
> "That’s where you can leverage Prefect **schedules** and deployments."
> 'Schedules' links to a **Notion** page & it cannot be accessed. Plz consider adding a different link.
> 

Thanks so much, something must have gone wrong when copy pasting markdown from Notion, well spotted! Will correct once I'm home in a couple of hours

**Comment by ShilpaVernekar** [comment]
Thanks @anna-geller 
I've updated the link from GitBook

**Comment by anna-geller** [comment]
> Thanks @anna-geller 
> I've updated the link from GitBook

Thanks! I don't know how GitBook process works but curious if you could explain what's needed to merge and close this PR and release the changes to the docs?

**Comment by ShilpaVernekar** [comment]
Thanks for all the changes @anna-geller  :)

**Pull request merged**
