### PR TITLE
Create ometa client once and pass it around & improve pycln config

### PR DESCRIPTION
**Pull request by pmbrull**
### Describe your changes:

Some housekeeping for:
- Ensuring that the `timer` in the workflow gets closed. Otherwise if there were any errors in `close` the `timer` did not close the thread and left the workflow running nonstop
- We were creating the ometa client multiple times. We are now just creating it once in the BaseWorkflow and passing it around
- `pycln` was not properly cleaning our own modules. Add the `--all` flag to be more strict on what is automated. Otherwise lint rules were crying and we needed to remove them manually

#
### Type of change:

- [ ] Bug fix
- [ ] Improvement
- [ ] New feature
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/developers/contribute) document.
- [ ] My PR title is `Fixes <issue-number>: <short explanation>`
- [ ] I have commented on my code, particularly in hard-to-understand areas. 
- [ ] For JSON Schema changes: I updated the migration scripts or explained why it is not needed.

### CODE REVIEW

**Review by harshach — APPROVED** [review]

**Comment by harshach** [comment]
@pmbrull is OmetaClient thread safe? what happens when we try add multi-thread support in future

**Review by ayush-shah — DISMISSED** [review]

**Review by ayush-shah — COMMENTED** [review]
@pmbrull we have some pytest failures for openmetadataconnection not having methods

**Comment by pmbrull** [comment]
> @pmbrull is OmetaClient thread safe? what happens when we try add multi-thread support in future

To handle more threads we should be able to manage that at the workflow level and pass different clients to each one

**Comment by pmbrull** [comment]
> @pmbrull we have some pytest failures for openmetadataconnection not having methods

ye need to review. Must have missed passing the right param in a few places. Thanks!

**Review by harshach — APPROVED** [review]

**Review by ayush-shah — APPROVED** [review]

**Pull request merged**
