### PR TITLE
update zh-cn.json, translate more

### PR DESCRIPTION
**Pull request by benyuereal**
translate more with open AI translation

### Describe your changes :

I worked on the ..... because ...
i want translate  message to chinese laguage
#
### Type of change :

- [ ] Bug fix
- [x] Improvement
- [x] New feature
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation

#
### Frontend Preview (Screenshots) :
<p align="center">For frontend related change, please link screenshots of your changes preview! Optional for backend related changes.
</p>

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/developers/contribute) document.
- [ ] I have commented on my code, particularly in hard-to-understand areas.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [x] All new and existing tests passed.

#

### CODE REVIEW

**Review by harshach — DISMISSED** [review]

**Comment by harshach** [comment]
@benyuereal Thanks for the PR. Can you please fix the merge conflicts and push the changes.
Looking forward to merge this in.

**Comment by qiangxue1206** [comment]
@benyuereal 嗨，哥们，记得处理下这个PR

**Comment by benyuereal** [comment]
@qiangxue1206 @harshach ok, copy that, i working on this pr(好的，收到 我正在处理这个pull请求)

**Comment by harshach** [comment]
Thanks @benyuereal

**Comment by chirag-madlani** [comment]
hi @benyuereal can you please address the merge conflicts, and mentioned me here. I will merge it ASAP

**Comment by benyuereal** [comment]
> hi @benyuereal can you please address the merge conflicts, and mentioned me here. I will merge it ASAP

i solved already, check and review for merge please

**Comment by benyuereal** [comment]
halo, help review this pr please @harshach

**Comment by harshach** [comment]
@chirag-madlani can we merge this in?

**Comment by chirag-madlani** [comment]
Hi @benyuereal ,
Can you resolve the conflict and ping me here? I will merge it in

**Comment by ShaileshParmar11** [comment]
Hello @benyuereal , thanks for the PR, however, We already have localization changes for zh-cn, and a lot of changes are duplicates, closing the PR.

**Pull request closed without merging**
