### PR TITLE
Fix #4768 - Add Location path

### LINKED ISSUE #4768: Glue Location ingestion
**Affected module**
Ingestion

**Describe the bug**
```
[2022-05-06 14:34:52,582] ERROR    {metadata.ingestion.source.glue:230} - 1 validation error for Location
name -> __root__ -> __root__
  ensure this value has at most 128 characters (type=value_error.any_str.max_length; limit_value=128)
Traceback (most recent call last):
  File "/Users/david.marques/Projects/openmetadata/env/lib/python3.9/site-packages/metadata/ingestion/source/glue.py", line 193, in ingest_tables
    location_entity = Location(
  File "pydantic/main.py", line 331, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for Location
name -> __root__ -> __root__
  ensure this value has at most 128 characters (type=value_error.any_str.max_length; limit_value=128)
```
**To Reproduce**

Screenshots or steps to reproduce

**Expected behavior**

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

### PR DESCRIPTION
**Pull request by pmbrull**
### Describe your changes :

We were using `name` to store the location path. That easily overflowed the 128 characters.

This PR fixes #4768 and adds the property `path` to location.

#
### Type of change :

- [x] Bug fix
- [x] Improvement
- [x] New feature
- [] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [] Documentation

#
### Frontend Preview (Screenshots) :
<p align="center">For frontend related change, please link screenshots of your changes preview! Optional for backend related changes.
</p>

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/open-source-community/developer) document.
- [ ] I have commented on my code, particularly in hard-to-understand areas.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [x] All new and existing tests passed.

#

### CODE REVIEW

**Comment by pmbrull** [comment]
@harshach I think I might be missing something on the backend side as the path is not being stored. Having a hard time with the old structure though. IDK if it makes sense to spend time in this or ignore until the refactor as we are not using this information anywhere for now.

**Comment by harshach** [comment]
@pmbrull let me take a look. however on ingestion side we shouldn't be failing on location, i.e if the location is not being able to accept we should still ingest the tables

**Comment by pmbrull** [comment]
> @pmbrull let me take a look. however on ingestion side we shouldn't be failing on location, i.e if the location is not being able to accept we should still ingest the tables

@harshach updating that

**Comment by harshach** [comment]
@pmbrull this looks good to me . I am able to create and get the location details 
image

**Comment by harshach** [comment]
pushed a minor change to enable tests on path field

**Review by harshach — APPROVED** [review]

**Pull request merged**
