### PR TITLE
Issue 3189-Add OMeta tests for PipelineService

### PR DESCRIPTION
**Pull request by ziwei-la**
### Describe your changes :

I worked on the ometa tests for PipelineService because ometa tests for the services are not complete.  

#
### Type of change :

- [ ] Bug fix
- [x] Improvement
- [ ] New feature
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/developers/contribute) document.
- [x] I have commented on my code, particularly in hard-to-understand areas.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] All new and existing tests passed.

#
### Reviewers

Ingestion: @open-metadata/ingestion
Issue opener: @pmbrull 
Member: @ulixius9

### CODE REVIEW

**Comment by pmbrull** [comment]
hi @ziwei-la thanks for the PR!

You can disregard the cypress failure, its flaky. However, can you please fix the python checkstyle? Running `make py_format` should get rid of it. Thanks!

**Review by harshach — APPROVED** [review]

**Comment by harshach** [comment]
@ziwei-la can you follow the instructions above to fix the python styling? Once you push the changes we can merge it in.

**Comment by ziwei-la** [comment]
Hi @pmbrull @harshach , thanks for the approval, but every time I run the make py_format in the make file, this error occurs.
Make_error
I downloaded different versions of make to run the command, but the error remains.

**Comment by pmbrull** [comment]
> Hi @pmbrull @harshach , thanks for the approval, but every time I run the make py_format in the make file, this error occurs. Make_error I downloaded different versions of make to run the command, but the error remains.

running `make install_dev` should install all the necessary packages. I am not really grasping the error from the log. For reference, I use python 3.9.8 and have no issues with that 🤔

**Pull request closed without merging**
