### PR TITLE
Fixes #10065 Allow Unicode characters and digits in the entityName

### LINKED ISSUE #10065: Allow Unicode characters and digits in the entityName
Earlier changes that added restrictions to entity naming used '\w' to allow word characters. Unfortunately, in Java, this translates to `[a-z][A-Z]_` and does not allow any other characters in other languages. This issue changes the current regex to allow other language characters with Unicode support.

### PR DESCRIPTION
**Pull request by sureshms**
### Describe your changes :

See #10065 
#
### Type of change :

- [x] Bug fix

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/developers/contribute) document.
- [x] I have commented on my code, particularly in hard-to-understand areas.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] All new and existing tests passed.

### CODE REVIEW

**Review by harshach — DISMISSED** [review]

**Comment by TeddyCr** [comment]
@sureshms the Python error is due to python regex not supporting unicode (e.g. `\p{P}`, checking if there is a workaround).

**Comment by harshach** [comment]
@TeddyCr I think Pydantic community was helpful to take our PRs. I would suggest to push a PR against them. I think @pmbrull worked with them before.

**Comment by harshach** [comment]
@chirag-madlani can you check if this will cause any issue on java script side

**Comment by chirag-madlani** [comment]
> @chirag-madlani can you check if this will cause any issue on java script side

Sure @harshach will check it

**Comment by TeddyCr** [comment]
@sureshms this pattern work `(?u)\w` (lowercase u)
```
pattern = re.compile(r'(?u)\w')
re.findall(pattern, 'ۿksaclБЮ̀')
['ۿ', 'k', 's', 'a', 'c', 'l', 'Б', 'Ю']
```
do you know the equivalent to p{S}

**Pull request merged**
