### PR TITLE
UI : Fix the Explore breaking issue when ES is down

### PR DESCRIPTION
**Pull request by Ashish8689**
### Describe your changes :

 - Fix the Explore breaking issue when ES is down

#
### Type of change :

- [x] Bug fix

#
### Frontend Preview (Screenshots) :
Issue : - 
image

Resolved : 
image

ErrorPlaceholder if issue with Elastic search
image

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/developers/contribute) document.
- [ ] I have commented on my code, particularly in hard-to-understand areas.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [x] All new and existing tests passed.

#
### Reviewers
@open-metadata/ui

### CODE REVIEW

**Comment by chirag-madlani** [comment]
@Ashish8689 do we have data that it's ES issue? If so we should show some other message here

**Comment by Ashish8689** [comment]
@chirag-madlani  we only have the response from the API that it's an ES issue. 
image

**Comment by Sachin-chaurasiya** [comment]
> @chirag-madlani we only have the response from the API that it's stating an ES issue. image

@Ashish8689 , if it's an elastic search issue, we should show the setup doc.

**Comment by Ashish8689** [comment]
@Sachin-chaurasiya @chirag-madlani  shown placeholder for ES issue!

**Review by chirag-madlani — APPROVED** [review]

**Pull request merged**
