### PR TITLE
fix(ui): support batchSize & flushIntervalInSec while ES re-indexing

### PR DESCRIPTION
**Pull request by chirag-madlani**
### Describe your changes :

I worked on the updating ES re-indexing UI

#
### Type of change :

- [x] Bug fix
- [x] Improvement
- [x] New feature
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation

#
### Frontend Preview (Screenshots) :
- Re-create config options:
Screenshot 2022-10-11 at 2 49 27 PM

- Card style updates:
Screenshot 2022-10-11 at 3 55 51 PM

- Web socket in action:

https://user-images.githubusercontent.com/12962843/195060424-dfd8900a-25bd-4bf3-b637-fc1050aa4c2a.mov

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/developers/contribute) document.
- [ ] I have commented on my code, particularly in hard-to-understand areas.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [x] All new and existing tests passed.

#

### CODE REVIEW

**Review by mohityadav766 — APPROVED** [review]

**Comment by mohityadav766** [comment]
@chirag-madlani we also need to have refresh button , in case websocket fails to push updates

**Comment by chirag-madlani** [comment]
> @chirag-madlani we also need to have refresh button , in case websocket fails to push updates

Done @mohityadav766

**Review by ShaileshParmar11 — APPROVED** [review]
Is there any reason for using a different naming convention for elastic search-related files?

**Comment by chirag-madlani** [comment]
> Is there any reason for using a different naming convention for elastic search-related files?

No, it's a mistake which I will cover in the next PR.
Not changing it in this since we need to cherry-pick this release branch. I will keep a note of it

**Pull request merged**
