### PR TITLE
Fixes #7072 - Remove life cycle policies

### LINKED ISSUE #7072: Remove life cycle policies
**Feature**
#4199 

**Describe the task**
Currently, life cycle policies are not used. These policies may be built in a different way from what exists today. Deleting them for now.

### PR DESCRIPTION
**Pull request by sureshms**
### Describe your changes :

See #7072 
#
### Type of change :

- [x] Improvement

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/developers/contribute) document.
- [x] I have commented on my code, particularly in hard-to-understand areas.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] All new and existing tests passed.

### CODE REVIEW

**Review by harshach — APPROVED** [review]

**Comment by sureshms** [comment]
@pmbrull do we import lifecycle policies from gcs and s3?
For example, I see in `ingestion/build/lib/metadata/ingestion/source/s3.py` and `gcs.py`, code such as this:
```
                policy = Policy(
                    id=uuid.uuid4(),
                    name=policy_name,
                    displayName=policy_name,
                    description=policy_name,
                    policyType=PolicyType.Lifecycle,
                    rules=rules,
                    enabled=True,
```

**Comment by sureshms** [comment]
@Sachin-chaurasiya and @ShaileshParmar11 need help in fixing the cypress failure. I tried :)

**Comment by pmbrull** [comment]
> policy = Policy(

Hi @sureshms, those two files had already been removed a while back as we are not ingesting location from them. Files under `build` are from previous code builds. However, I removed the policy ingestion from the `sink` as we are not sending that from any source

**Comment by ShaileshParmar11** [comment]
Hello @sureshms This is a flaky test, you can merge this PR, and we will improve this test! Thanks
cc @Sachin-chaurasiya

**Review by ShaileshParmar11 — APPROVED** [review]

**Pull request merged**
