### PR TITLE
Fixes #15499: Change the ApiClient init call.

### LINKED ISSUE #15499: OMD 1.3.0 Java client(gateway)'s constructor bug.
**Affected module**
OMD-client, JAVA SDK

**Describe the bug**
There is an error in the OMD constructor of the Java client regarding the apiClient invocation. The initClient invocation is split into two, and one of them calls the apiClient object without any initialization work.

**To Reproduce**
- [omd 1.3.x omd gateway](https://github.com/open-metadata/OpenMetadata/blob/1.3.1-release/openmetadata-clients/openmetadata-java-client/src/main/java/org/openmetadata/client/gateway/OpenMetadata.java#L42-L70)
```java
  public OpenMetadata(OpenMetadataConnection config) {
    initClient(config);
    validateVersion();
  }

  public OpenMetadata(OpenMetadataConnection config, boolean validateVersion) {
    initClient(config);
    if (validateVersion) validateVersion();
  }

  public void initClient(OpenMetadataConnection config) {
    Feign.Builder builder =
        Feign.builder()
            .encoder(new FormEncoder(new JacksonEncoder(apiClient.getObjectMapper())))
            .decoder(new JacksonDecoder(apiClient.getObjectMapper()))  // <-- the edge point
            .logger(new Slf4jLogger())
            .client(new OkHttpClient());
    initClient(config, builder);
  }

  public void initClient(OpenMetadataConnection config, Feign.Builder builder) {
    apiClient = new ApiClient();
    apiClient.setFeignBuilder(builder);
    AuthenticationProviderFactory factory = new AuthenticationProviderFactory();
    apiClient.addAuthorization("oauth", factory.getAuthProvider(config));
    String basePath = config.getHostPort() + "/";
    apiClient.setBasePath(basePath);
    apiClient.getObjectMapper().setSerializationInclusion(JsonInclude.Include.NON_NULL);
  }
```

**Expected behavior**
The initializing apiClient has move `initClient(OpenMetadataConnection config, Feign.Builder builder)` to `initClient(OpenMetadataConnection config)`
```java
  public void initClient(OpenMetadataConnection config) {
    apiClient = new ApiClient();
    Feign.Builder builder =
        Feign.builder()
            .encoder(new FormEncoder(new JacksonEncoder(apiClient.getObjectMapper())))
            .decoder(new JacksonDecoder(apiClient.getObjectMapper()))
            .logger(new Slf4jLogger())
            .client(new OkHttpClient());
    initClient(config, builder);
  }

  public void initClient(OpenMetadataConnection config, Feign.Builder builder) {
    apiClient.setFeignBuilder(builder);
    AuthenticationProviderFactory factory = new AuthenticationProviderFactory();
    apiClient.addAuthorization("oauth", factory.getAuthProvider(config));
    String basePath = config.getHostPort() + "/";
    apiClient.setBasePath(basePath);
    apiClient.getObjectMapper().setSerializationInclusion(JsonInclude.Include.NON_NULL);
  }
```

**Version:**
 - OS: -
 - Python version: - 
 - OpenMetadata version: [e.g. 0.8] 1.3.x (1.3.0, 1.3.1)
 - OpenMetadata Ingestion package version: -

**Additional context**
- Related Issue: #15065
- Slack Discussion: https://openmetadata.slack.com/archives/C02B6955S4S/p1709779501286299

### PR DESCRIPTION
**Pull request by oringnam**
### Describe your changes:

Fixes #15499
Alter the Initializing position `initClient(OpenMetadataConnection config, Feign.Builder builder)` to `initClient(OpenMetadataConnection config)`

#
### Type of change:

- [x] Bug fix
- [ ] Improvement
- [ ] New feature
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/developers/contribute) document.
- [x] My PR title is `Fixes <issue-number>: <short explanation>`
- [x] I have commented on my code, particularly in hard-to-understand areas. 
- [x] I have added a test that covers the exact scenario we are fixing. For complex issues, comment the issue number in the test for future reference. (Based on https://docs.open-metadata.org/v1.3.x/sdk/java)

### CODE REVIEW

**Comment by oringnam** [comment]
**Additional Question**
I would like to inquire whether the functions `initClient(OpenMetadataConnection config)` and `initClient(OpenMetadataConnection config, Feign.Builder builder)` need to be provided as `public`.

Since these two functions are being called in the constructor of OpenMetadata, I believe that providing them as `private` would not cause significant inconvenience for SDK users.

**Review by harshach — APPROVED** [review]

**Comment by harshach** [comment]
@oringnam that sounds good. Feel free to make them public

**Comment by harshach** [comment]
@oringnam are you planning adding further changes?

**Comment by oringnam** [comment]
@harshach Sorry for the late reply. There are no further changes to PR now, and switching to the private method mentioned above will be opened as another issue.

**Comment by harshach** [comment]
Thanks for the PR @oringnam

**Pull request merged**
