### PR TITLE
Corrected null checks

### PR DESCRIPTION
**Pull request by MaheshGPai**
### Describe your changes :

I worked on the ..... because ...

#
### Type of change :

- [ ] Bug fix
- [x] Improvement
- [ ] New feature
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation

#
### Frontend Preview (Screenshots) :
<p align="center">For frontend related change, please link screenshots of your changes preview! Optional for backend related changes.
</p>

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/developers/contribute) document.
- [ ] I have commented on my code, particularly in hard-to-understand areas.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [x] All new and existing tests passed.

#

### CODE REVIEW

**Comment by MaheshGPai** [comment]
Addresses #8319

**Review by sureshms — APPROVED** [review]

**Comment by MaheshGPai** [comment]
@sureshms I do not seem to have access to merge the change.

**Comment by sureshms** [comment]
@MaheshGPai merge permission is only for the committers of the project. Thank you for your contribution 👍. I will merge it, when all the tests are complete.

**Comment by MaheshGPai** [comment]
> @MaheshGPai merge permission is only for the committers of the project. Thank you for your contribution 👍. I will merge it, when all the tests are complete.

Cool. Thanks!

**Pull request merged**
