### PR TITLE
ISSUE-960: 

### LINKED ISSUE #960: Integration tests for Hive is broken
Sub-issue of #798
When following the instructions on this page https://docs.open-metadata.org/open-source-community/developer/run-integration-tests for Hive Integration tests, you get errors:
`FAILED tests/integration/hive/test_hive_crud.py::test_check_table - TypeError: __init__() takes 2 positional arguments but 4 were given`

### PR DESCRIPTION
**Pull request by vijaypm**
### Describe your changes :
Fixed Integration test for Hive and updated documented with list of pip packages. This PR closes #960 

#
### Type of change :

- [x] Bug fix
- [x] Documentation

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/open-source-community/developer) document.
- [x] I have performed a self-review of my own. 
- [x] I have tagged my reviewers below.
- [x] I have commented on my code, particularly in hard-to-understand areas.
- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] All new and existing tests passed.

#
### Reviewers
Ingestion: @harshach @ayush-shah @pmbrull

### CODE REVIEW

**Comment by pmbrull** [comment]
Hi @vijaypm, thanks for tackling this.

Regarding the `is_responsive` function, it is interesting to first check that the endpoint works before trying to run the tests. However, instead of trying to connect through a socket, it might be cleaner to use the healthcheck endpoint that comes with the API at `http://localhost:8585/api/v1/health-check`.

Wdyt? This way you can directly use python requests and check for a 200.

**Comment by vijaypm** [comment]
@pmbrull good point. I think we need two separate mechanisms - using 'requests' to test whether the metadata service http port is responsive or not, and 'socket' to test whether the hive2 port is open or not. 
I'll revert the 'is_responsive' method to use requests to test for http responsiveness, and I'll add a new method 'is_port_open' to use socket to test whether a port is open or not.

**Comment by vijaypm** [comment]
Btw, I looked into doing a GET on the healthcheck api instead of just the service endpoint. The challenge with using the healthcheck is that the healthcheck fails even if ingestion is working perfectly fine. Since these integration tests are exercising the ingestion api, I assume they are sufficient for now.

**Comment by pmbrull** [comment]
> Btw, I looked into doing a GET on the healthcheck api instead of just the service endpoint. The challenge with using the healthcheck is that the healthcheck fails even if ingestion is working perfectly fine. Since these integration tests are exercising the ingestion api, I assume they are sufficient for now.

Yep thats a good point. Yesterday I noticed some issues with the healthcheck although the REST was working correctly. Maybe @harshach can give us a hint here on might be wrong. If needed I can open an issue, but would be interesting to have a small troubleshooting guide on what to check if the API reports to be unhealthy.

Thanks!

**Comment by harshach** [comment]
Thanks @pmbrull . @vijaypm can you please use the health check api. We can merge it in after

**Comment by harshach** [comment]
Thanks for handling this @vijaypm . Looks Great!

**Pull request merged**
