### PR TITLE
Fixes 9875: supporting gcp secret manager

### PR DESCRIPTION
**Pull request by nakaken-churadata**
### Describe your changes:

Fixes 9875

I worked on support the gcp secret manager.

#
### Type of change:

- [x] New feature

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/developers/contribute) document.
- [x] My PR title is `Fixes <issue-number>: <short explanation>`
- [x] I have commented on my code, particularly in hard-to-understand areas. 
- [x] For JSON Schema changes: I updated the migration scripts or explained why it is not needed.

- [x] The issue properly describes why the new feature is needed, what's the goal, and how we are building it. Any discussion
    or decision-making process is reflected in the issue.
- [x] I have updated the documentation.
- [x] I have added tests around the new logic.

### CODE REVIEW

**Comment by harshach** [comment]
Thanks @nakaken-churadata for the PR

**Comment by nakaken-churadata** [comment]
I'm fixing some errors in pytest. Wait a moment, please.

**Comment by nakaken-churadata** [comment]
I'm investigating errors in pytest. Wait a moment, please.

**Comment by nakaken-churadata** [comment]
@harshach @akash-jain-10 
I have fixed some errors. Could you review this PR?

**Review by harshach — APPROVED** [review]

**Pull request merged**
