### PR TITLE
[Issue-998] - Deprecate OpenMetadataAPIClient

### LINKED ISSUE #998: High Level API - Migrate openmetadata_rest
After #954 & #999, we'll need to review the missing functionalities to migrate and have the whole `ingestion` code depend only on the new `OpenMetadata` API.

With this issue, we should completely deprecate `OpenMetadataAPIClient`

### PR DESCRIPTION
**Pull request by pmbrull**
### Describe your changes :
This PR fixes #998.

After working on the implementation of the new High-level API `OpenMetadata`, we are in a safe spot for deprecating the old interface `OpenMetadataAPIClient`.

This PR has refactored all the `ingestion` code to use `OpenMetadata`.

We have tested the refactoring by running the three provided sample pipelines (`sample_data`, `sample_usage` and `metadata_to_es`), refactoring and running the MySQL and Hive integration tests and refactoring and running the unit tests.

It is quite a big change, so please let me know if I missed something, I'll be happy to fix it.

Thanks!

#
### Type of change :

- [ ] Bug fix
- [x] Improvement
- [ ] New feature
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/open-source-community/developer) document.
- [x] I have performed a self-review of my own. 
- [x] I have tagged my reviewers below.
- [x] I have commented on my code, particularly in hard-to-understand areas.
- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] All new and existing tests passed.

#
### Reviewers
@harshach @ayush-shah

### CODE REVIEW

**Comment by harshach** [comment]
Thanks @pmbrull . This is just great. Code looks clean and nice :)

**Comment by pmbrull** [comment]
Thanks, @harshach! I opened a few issues during the refactor for small details that can be improved. Some of them might be good first issues for anyone getting started with the ingestion framework.

I'd add the tag to: #1048, #1049 & #1051

Thanks!

**Comment by harshach** [comment]
That's awesome!!! Thanks. Can you post it in slack once you tag them. Will be helpful for others in the community.

**Comment by pmbrull** [comment]
> That's awesome!!! Thanks. Can you post it in slack once you tag them. Will be helpful for others in the community.

Thanks, @harshach, happy to do so. Could you please check the permissions on the issues? I am not sure I can modify the tags!

Thany 🙏

**Pull request merged**
