### PR TITLE
Add testcontainers to support Apple Silicon with native JVM

### PR DESCRIPTION
**Pull request by amiorin**
### Describe your changes :

See #2919
I worked on adding `testcontainers` because `wix` doesn't work on Apple Silicon native JVM. There is a workaround that is running the JVM x86_64 in rosetta but this could discourage new developers that don't know it yet.

#### Implementation details
We check the JVM architecture to choose between `wix` and `testcontainers`. Now the user is not anymore `test` but `root`. `mysql/mysql` container doesn't allow to create `test@%` with environment variables.

`testcontainers` try to force you to use random ports. We run MySQL on port 3307 for the tests and I find it useful so that I can use IntelliJ SQL client to browse the test database without reconfiguring it. `testcontainers` starts a [sidekick](https://github.com/testcontainers/moby-ryuk) that cleans up things if the test fails before running the `teardown` methods. I had to define a custom `setup` and `teardown` to override the random port with a fixed port.

#### Todo
- [ ] [Discarded, it makes things too complex] Test if it is possible to use a MySQL custom image that includes our database with the migrations already executed to make the tests faster.

#### References
 * https://wiredverse.com/posts/2021/05/java-m1-mac/

#
### Type of change :

- [x] Improvement

### CODE REVIEW

**Comment by harshach** [comment]
@amiorin this PR is doubling the test runtime
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  18:35 min
[INFO] Finished at: 2022-03-24T20:07:02-07:00

Pre-running migrations are not the right thing. We are going to make changes in the migrations those needs to be tested and not pre-built

**Comment by harshach** [comment]
Running without Rosetta enabled on M1 Max laptop
[INFO] Total time:  15:37 min
[INFO] Finished at: 2022-03-24T20:24:00-07:00

Still pretty bad

**Comment by amiorin** [comment]
The performance issue is fixed. If the JVM is x86_64 (with or without rosetta), it will use `wix`. If the JVM is not, it will use `testcontainers`. This will make sure that new developers will have an easier first experience because they will not get an error when trying to test OM in an Apple Silicon with a native JVM.

**Review by harshach — CHANGES_REQUESTED** [review]
@amiorin Thats not really a fix though right. Now we have 2 things to check and keep it updated.  Calling it a performance fix is not a right thing.
The tests will throw an error if the docker server is not working and it doesn't tell why clearly. 
Lets keep the PR around but its not mergable state.

**Comment by amiorin** [comment]
Ok, but let's also repeat here that this is a problem of OSX problem when running Linux containers.
`testcontainers` and `wix` perform the same under Linux. Maybe we should all switch to a Linux Desktop. ;-)
Back in the day, the common approach was to start MySQL locally, run the migrations one time, run the tests inside an SQL transaction with rollback and everything was super fast ([Ruby on Rails](https://guides.rubyonrails.org/testing.html#testing-parallel-transactions)).

**Pull request closed without merging**
