### PR TITLE
[WIP] [issue-1976] - Fix ingestion lint

### PR DESCRIPTION
**Pull request by pmbrull**
### Describe your changes :

Checking sonar integration 
#
### Type of change :

- [x] Bug fix
- [x] Improvement
- [x] New feature
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Documentation

#
### Frontend Preview (Screenshots) :
<p align="center">For frontend related change, please link screenshots of your changes preview! Optional for backend related changes.
</p>

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/open-source-community/developer) document.
- [ ] I have performed a self-review of my own. 
- [ ] I have tagged my reviewers below.
- [ ] I have commented on my code, particularly in hard-to-understand areas.
- [ ] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [x] All new and existing tests passed.

#

### CODE REVIEW

**Comment by pmbrull** [comment]
hi @harshach, I was testing the sonarcloud integration + bot feedback after updating the actions to `pull_request_target` to pick up secrets during forks.

I see that the `catalog` project is returning something, but not the `openmetadata-ingestion`. Here we might be missing the project integrated with the github repo as we did for the `catalog`. First time I test multiple sonar projects for the same repo though.

Also, I see that the main branch setting for `openmetadata-ingestion` is `master`. We might need to change that to `main`.

Thanks! Let me know if I can help with anything here.

**Comment by harshach** [comment]
Thanks @pmbrull . Appreciate all your help on setting this up.
I change the master branch to main https://sonarcloud.io/project/overview?id=openmetadata-ingestion . 
Am I missing anything else to configure. Thanks.

**Comment by pmbrull** [comment]
Thanks, @harshach!

I see that the `catalog` is properly configured, as we have the `bound to github` tag.
image

I am not seeing that for the `openmetadata-ingestion` project though 🤔

**Comment by pmbrull** [comment]
Hi @harshach, I played around a bit in sonarcloud and found the following:

image


image

This should let us configure multiple sonar projects from a single github repo

**Comment by pmbrull** [comment]
Closing this PR as we already figured out sonarcloud. Thanks 🙏

**Pull request closed without merging**
