### PR TITLE
[TASK-6241] Cache ES ingestion when ingesting usage

### PR DESCRIPTION
**Pull request by Beetelbrox**
### Describe your changes :
As explained on #6241, we've identified that the database usage ingestion does a very large amount of repeated requests to elastisearch and the backend tables for every query/table processed. This PR is a first effort to improve usage ingestion performance by implementing caches/checks in three stages of the process:
 * `metadata_usage` & `table_mixin`: For each table, avoid ingesting the same query more than once as it will add no new information and most of the repetaed queries are created by previous stages in the process. 
 * `sql_usage` cache the result of `search_table_entities` that does one query to ES and potentially many to backend and was one of the main sources of the slowdown. I wasn't able to find a nice place to put the cache due to the way the code is structured so I ended up creating it as a module-level variable. This is far from ideal but for a nicer setup we'll need to do some restructuring.

We did some experiments to evaluate the impact in performance and obtained the results below. Note that to reduce variability we extracted an entire day's worth of queries (~52.5k queries, 57 MB)  from RS into a csv file and loaded them from there. All runs below include the sql parsing step which was not optimized:

**Not optimized**
 - 1000 records, no optimization -> 88.63s user 5.92s system 32% cpu 4:53.97 total
 - 5000 records, no optimization -> 676.88s user 12.21s system 59% cpu 19:25.03 total
 - 10000 records, no optimization -> 1276.32s user 21.37s system 60% cpu 35:47.41 total
**Optimized**
 - 1000 records, optimized -> 33.79s user 1.01s system 54% cpu 1:03.41 total
 - 5000 records, optimized -> 357.55s user 2.50s system 79% cpu 7:32.33 total
 - 10000 record, optimized -> 566.22s user 4.54s system 75% cpu 12:34.00 total

image

The chart above suggests that the imroved version has a lower complexity, although due to the many parts involved in the execution of each iteration of the ingestion this might be difficult to measure.

There's still plenty of room for improvement as the ones propoed are quite hamfisted and we could greatly reduce the amount of records we generate ourselves but it's a good indicator of how things can improve.

#
### Type of change :

- [] Bug fix
- [x] Improvement
- [] New feature
- [] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [] Documentation

#
### Frontend Preview (Screenshots) :
N/A

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/open-source-community/developer) document.
- [x] I have commented on my code, particularly in hard-to-understand areas.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] All new and existing tests passed.

#
### Reviewers
 @open-metadata/ingestion

### CODE REVIEW

**Comment by pmbrull** [comment]
Many thanks for this @Beetelbrox, really enjoying our conversations around this and we truly appreciate the time and effort you're investing ❤️ 

The PR looks great, let's merge it in after adding the LRU cache as discussed 🚀

**Comment by harshach** [comment]
Thanks a lot @Beetelbrox this is great!!

**Comment by TeddyCr** [comment]
@Beetelbrox thank you for the awesome PR 🙏. Would you be able to fix the code smell. After that we can merge it. 🚀

**Review by TeddyCr — APPROVED** [review]
LGTM 🚀

**Pull request merged**
