### PR TITLE
Fixed abstract init issue

### PR DESCRIPTION
**Pull request by OnkarVO7**
### Describe your changes :

PowerBi source was failing with below error 
image

#
### Type of change :

- [x] Bug fix

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/developers/contribute) document.
- [ ] I have commented on my code, particularly in hard-to-understand areas.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [x] All new and existing tests passed.

#
### Reviewers

@open-metadata/ingestion

### CODE REVIEW

**Review by ayush-shah — DISMISSED** [review]

**Comment by ayush-shah** [comment]
@OnkarVO7 can we check if we have added abstractmethod to any other init?

**Comment by OnkarVO7** [comment]
> @OnkarVO7 can we check if we have added abstractmethod to any other init to avoid similar error conflicts?

@ayush-shah yes checking

**Comment by OnkarVO7** [comment]
@ayush-shah made changes to messaging service please review

**Review by ayush-shah — DISMISSED** [review]

**Comment by ayush-shah** [comment]
> @ayush-shah made changes to messaging service please review

Approved

**Review by ulixius9 — APPROVED** [review]

**Pull request merged**
