### PR TITLE
Feat : UI - Filter by database name.

### LINKED ISSUE #1563: [Feature Request] Filter by database name
Hello Guys,

I think would be good on explorer page a way to filter by database, for example in my case we use Glue(Hive) our tables are organized by database.

Captura de Tela 2021-12-05 às 20 07 15

On the middle, would be good to know which database the tables belongs.

Thank you

### PR DESCRIPTION
**Pull request by Sachin-chaurasiya**
Close #1563 
### Describe your changes :

I worked on the Explore page because need to add a Database filter.

#
### Type of change :

- [x] Improvement
- [x] New feature

#
### Frontend Preview (Screenshots) :
image

image

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/open-source-community/developer) document.
- [x] I have performed a self-review of my own. 
- [x] I have tagged my reviewers below.
- [ ] I have commented on my code, particularly in hard-to-understand areas.
- [x] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [x] All new and existing tests passed.

#
### Reviewers
@shahsank3t, @darth-coder00

### CODE REVIEW

**Comment by mithmatt** [comment]
For larger use cases, wouldn't there be a lot of databases, where what we need would be a text based search bar instead?

Or some kind of query language similar to sourcegraph keyword search
https://docs.sourcegraph.com/code_search/reference/queries#keywords-all-searches


`database:shopify`

**Comment by Sachin-chaurasiya** [comment]
> For larger use cases, wouldn't there be a lot of databases, where what we need would be a text based search bar instead?
> 
> Or some kind of query language similar to sourcegraph keyword search https://docs.sourcegraph.com/code_search/reference/queries#keywords-all-searches
> 
> `database:shopify`

@mithmatt In next we are going to add advance search In the UI. so users can perform advance searches like
`database:Shopify , columns_name:data_id`

**Comment by harshach** [comment]
@Sachin-chaurasiya we are going to add "More" option right if there are lot of databases?

**Comment by Sachin-chaurasiya** [comment]
> @Sachin-chaurasiya we are going to add "More" option right if there are lot of databases?

@harshach Yes same as we have for existing filters.

**Review by shahsank3t — APPROVED** [review]

**Pull request merged**
