### PR TITLE
sample data for object store service and containers

### PR DESCRIPTION
**Pull request by cristiancalugaru**
### Describe your changes :
Sample data for the new object store service and containers.

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/developers/contribute) document.
- [x] All new and existing tests passed.

#
### Reviewers

@pmbrull @harshach

### CODE REVIEW

**Review by pmbrull — COMMENTED** [review]
Thanks @cristiancalugaru it LGTM. We'll just need to fix the checkstyle and we'll be good.

@chirag-madlani FYI, we can start with the UI once this gets in.

Thanks

**Comment by pmbrull** [comment]
hi @cristiancalugaru we still have some pylint failures:
```
************* Module metadata.ingestion.ometa.ometa_api
ingestion/src/metadata/ingestion/ometa/ometa_api.py:33:0: C0412: Imports from package metadata are not grouped (ungrouped-imports)
************* Module metadata.ingestion.source.database.sample_data
ingestion/src/metadata/ingestion/source/database/sample_data.py:1:0: C0302: Too many lines in module (1061/1000) (too-many-lines)
ingestion/src/metadata/ingestion/source/database/sample_data.py:197:4: R0915: Too many statements (52/50) (too-many-statements)
```

For the `sample_data` ones, feel free to just add a `# pylint: disable=too-many-lines` and `# pylint: disable=too-many-statements`. Organising the imports in `ometa_api` will be enough.

Thanks

**Comment by harshach** [comment]
@cristiancalugaru I recommend adding more examples of sample data with varying options and adding a container with schema and children. Not sure I noticed one like that. This will help us test the UI

**Comment by cristiancalugaru** [comment]
@harshach The sample does contain quite a few with schemas and children. Here is a summary of the containers in the sample data:

1. "transactions" - container with a partitioned data model and 3 columns: transaction_id, merchant, transaction_time. No children
2. "departments" - container without a schema
3. "engineering" - child container of "departments" without a schema
4. "finance" - child container of "departments" with a data model that's not partitioned but which has 4 columns: department_id, budget_total_value, notes, budget_executor
5. "media" - child container of "departments" without a schema
6. "movies" - child container of "media" without a schema
7. "expenditures" - child container of "finance" with 4 columns: department_id, approved, fraudulent_claims, total_value_for_current_month

This should cover most cases - we have 3 levels deep containers: s3:/departments/finance/expenditures, container with no children (transactions), containers with/without a data model, and with/without a partitioned data model

**Review by harshach — APPROVED** [review]

**Pull request merged**
