### PR TITLE
ISSUE-206: fixed description icon position

### PR DESCRIPTION
**Pull request by ShaileshParmar-WebDeveloper**
### Describe your changes :

Fixed description icon position in Schema tab & Tags page.

#
### Type of change :

- [x] Bug fix
- [ ] New feature
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation

#
### Frontend Preview (Screenshots) :
image
image
image

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/open-source-community/developer) document.
- [x] I have performed a self-review of my own. 
- [x] I have tagged my reviewers below.
- [ ] I have commented on my code, particularly in hard-to-understand areas.
- [x] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [x] All new and existing tests passed.

#

### CODE REVIEW

**Comment by darth-coder00** [comment]
@ShaileshParmar-WebDeveloper Can you add below text in a column description and attach screenshots here?

Unique numeric identifier for the order across Shopify stores. In your Shopify admin, this ID is used internally. Most merchants are familiar with the other ID that appears on orders in the Shopify admin. This ID can be found in the Name column.
New line dummy test2

**Review by darth-coder00 — APPROVED** [review]
LGTM

**Comment by darth-coder00** [comment]
@shahsank3t @Sachin-chaurasiya Please approve

**Review by Sachin-chaurasiya — APPROVED** [review]

**Review by shahsank3t — APPROVED** [review]

**Comment by ShaileshParmar-WebDeveloper** [comment]
image
image
Preview for different description size.

**Pull request merged**
