### PR TITLE
[Sonar Lint Issue Fix] Remove unnecessary Exceptions flagged by SonarLint

### LINKED ISSUE #7845: Remove unnecessary exception declared as thrown
See for details - https://sonarcloud.io/project/issues?resolved=false&rules=java%3AS1130&severities=MINOR&id=open-metadata_OpenMetadata

### PR DESCRIPTION
**Pull request by AM1TB**
### Describe your changes :
Remove unnecessary exception declared as thrown. Resolves #7845

https://sonarcloud.io/project/issues?resolved=false&rules=java%3AS1130&severities=MINOR&id=open-metadata_OpenMetadata

#
### Type of change :

- [x] Improvement

#
### Checklist:
- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/developers/contribute) document.
- [ ] I have commented on my code, particularly in hard-to-understand areas.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] All new and existing tests passed.

#
### Reviewers
Backend: @open-metadata/backend

### CODE REVIEW

**Comment by harshach** [comment]
@AM1TB thanks for the pr. Can you run googleformatter to get our stylecheck passing

**Comment by AM1TB** [comment]
> @AM1TB thanks for the pr. Can you run googleformatter to get our stylecheck passing

@harshach I got the stylecheck to pass. Pl review this PR whenever you can.

image

**Comment by sureshms** [comment]
There are UI test failures that are unrelated to this change. @Sachin-chaurasiya and @ShaileshParmar11, I am going to commit this change.

**Review by sureshms — APPROVED** [review]

**Comment by sureshms** [comment]
@AM1TB thank you for your code contribution 🙌

**Pull request merged**
