### PR TITLE
ISSUE-15426 increase the server response rate GET /v1/dataQuality/testCases

### PR DESCRIPTION
**Pull request by Alexandr-Nedomets**
[Increase the server response rate for endpoint GET /v1/dataQuality/testCases](https://github.com/open-metadata/OpenMetadata/issues/15426)

### Describe your changes:
Improved server response for "GET /v1/dataQuality/testCases"
on pages (/data-quality/test-cases, /table/RedshiftProd.dev.demo_dbt_jaffle.customers/profiler?activeTab=Data%20Quality)

It was 2 seconds, now it's 200-400 milliseconds. 
https://sandbox.open-metadata.org/data-quality/test-cases
image

There is a noticeable increase here, because the table for test cases is the same.
https://sandbox.open-metadata.org/table/RedshiftProd.dev.demo_dbt_jaffle.customers/profiler?activeTab=Data%20Quality
image

Fixes <issue-number>

I worked on ... because ...

#
### Type of change:

- [ ] Bug fix
- [ ] Improvement
- [ ] New feature
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/developers/contribute) document.
- [ ] My PR title is `Fixes <issue-number>: <short explanation>`
- [ ] I have commented on my code, particularly in hard-to-understand areas. 
- [ ] For JSON Schema changes: I updated the migration scripts or explained why it is not needed.

### CODE REVIEW

**Comment by Alexandr-Nedomets** [comment]
Hello @TeddyCr 
Please see the changes

**Comment by harshach** [comment]
@TeddyCr @pmbrull why is this call even going to PIIMasker.java?

**Comment by TeddyCr** [comment]
@Alexandr-Nedomets thanks for the PR can you check the tests failures 😊

**Comment by TeddyCr** [comment]
@Alexandr-Nedomets can you take a look at the failing tests?

**Comment by pmbrull** [comment]
> > @TeddyCr @pmbrull why is this call even going to PIIMasker.java?
> 
> I believe we'll be masking sensitive data from the test result if a test is set against a PII sensitive column @pmbrull to confirm.

@harshach @TeddyCr that's correct. We mask the test info to avoid showing any possible sensitive info

**Comment by TeddyCr** [comment]
@Alexandr-Nedomets can you take a look at the failing tests?

**Comment by Alexandr-Nedomets** [comment]
@TeddyCr 
Sorry, missed the first message.
Need to correct the test (see picture)?

image

**Comment by TeddyCr** [comment]
> @TeddyCr Sorry, missed the first message. Need to correct the test (see picture)?
> 
> image

this one is ok. We'll be deprecating this part of the code in the 1.4.0 release

**Comment by TeddyCr** [comment]
@Alexandr-Nedomets can you run `mvn spotless:apply` though to fix the checkstyle please? Then we should be good.

**Comment by Alexandr-Nedomets** [comment]
> mvn spotless:apply

**Comment by Alexandr-Nedomets** [comment]
@TeddyCr 
run in root project and get exception 
image

**Comment by Alexandr-Nedomets** [comment]
Hi @TeddyCr
I fixed code style use comand mvn spotless:apply

image

**Comment by Alexandr-Nedomets** [comment]
Done

**Pull request merged**
