### PR TITLE
WIP Bug fix for Storage/Location entities

### PR DESCRIPTION
**Pull request by amiorin**
### Describe your changes :

Location doesn't use the '.' but the './' and every location SHOULD start with
a '/'.  To implement the Data Mesh governance we need to provide all locations
containing a location including the location itself.

While trying to implement the Operation library on top of OpenMetadata I have
encountered the Jersey client timeout. I have changed the
CatalogApplicationTest to have no timeout so that I can use the debugger. The
flow is Test -(http)> OperationAPI -(http)> OpenMetadataAPI -(reso/repo)> MySQL
and the timeout is between Test and OperationAPI. I've tried to modify the test
Dropwizard Configuration yaml file without success.

#
### Type of change :

- [x] Bug fix

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/open-source-community/developer) document.
- [x] I have performed a self-review of my own. 
- [x] I have tagged my reviewers below.
- [x] I have commented on my code, particularly in hard-to-understand areas.
- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] All new and existing tests passed.

#
### Reviewers

@sureshms @harshach

### CODE REVIEW

**Comment by sureshms** [comment]
I am not sure I understand the data mesh reference. Could you add more details?

".%" includes the delimiter to avoid service1 matching say service12 when done without the delimiter. We should handle that.

**Comment by amiorin** [comment]
@sureshms , you are right.

Requirements:
1. As a Data Producer, I want to be allowed to define external tables on my data on S3.
2. As a Data Platform, I want to stop Data Producer from defining external tables on data that doesn't belong to them.
3. As a Data Platform, I want to split the ownership of all the data on S3 using prefixes to have fewer policies and to group tables inside the same prefix and with the same ownership.

To achieve this I plan to create an API GET /v1/locations/prefixes?fqn=<urlencode(fqn) that returns all the locations matching this SQL condition. This method will have the usual parameters like ``fields``, ``limit``, ``before``, and ``after`` but it will not have ``service``. I will also revert the list operation to the default behavior.
```sql
-- fqn could be something like hdfs_prod://marketing/dwh/catalog/schema/table
-- service would be hdfs_prod://

SELECT ... WHERE LEFT(<fqn>, LENGTH(fullyQualifiedName)) = fullyQualifiedName
  AND fullyQualifiedName >= <service>
  AND fullyQualifiedName <= <fqn>
```

An Operation API that orchestrates the creation of an external table will check the ownership of these locations to allow/forbid the action.

**Comment by harshach** [comment]
@amiorin do we want to use the entire URL with the prefix as the FQN. 
example: 
```create external table spectrum.orc_example(
int_col int,
float_col float,
nested_col struct<
  "int_col" : int,
  "map_col" : map<int, array<float >>
   >
) stored as orc
location 's3://example/orc/files/'; ```

In this case location is s3://example/orc/files
so far all entities have been prefixed with service.name. In this case we can add a s3 service similar to all the other services each service should have a unique name in s3 configuration we can capture s3://example as its root dir and that service points to all the files under that bucket_name.
so the location becomes 
```
name: "location_name"
uri: "s3://example/orc/files/"
service: EntityRef("s3")
"
This way we can continue to refer using location_name, wdyt?

**Comment by amiorin** [comment]
@harshach Right now the FQN is ``"service.name" + ":/" + "location.name"`` and every location.name should start with ``"/"``
StorageService contains StorateType to address the property of file systems like HDFS that are not globally unique like S3. In the ingestion configuration of Glue, we will have to allow the user to provide the rules to match hive location and hive schema.table with OM service.name.

```
(regex(hive.location), regex(schema.table)) -> service.name = hdfs_marketing
(regex(hive.location), regex(schema.table)) -> service.name = hdfs_personalization
```

The same glue catalog could be used by two ``AWS EMR`` using ``HDFS``. Same requirement with ``Minio`` and ``S3``.

**Comment by harshach** [comment]
@amiorin question is why introduce ":/" instead of using "." as rest of the entities. We can keep the entire URI in another field to refer to it. But having "." will be consistent with everything else. Location.name and location.URI can be 2 separate fields

**Comment by amiorin** [comment]
> @amiorin question is why introduce ":/" instead of using "." as rest of the entities. We can keep the entire URI in another field to refer to it. But having "." will be consistent with everything else. Location.name and location.URI can be 2 separate fields

```
name: "location_name"
uri: "s3://example/orc/files/"
service: EntityRef("s3")
```
``service.name`` must be unique. Therefore name must be like uri. For example: ``marketing.hdfs://dwh/schema/table`` but hdfs is also in the ``storage_type`` and I thought to simplify everything with just ``marketing://dwh/schema/table``. In both cases I need to urlencode the call to the endpoint ``/v1/location/name/<urlencode(fqn)>`` on the client side.

Most of the time users will call the service s3 ``s3`` and ``s3://dwh/schema/table`` looks nicer than ``s3.s3//dwh/schema/table`` IMO.

**Comment by amiorin** [comment]
@harshach and I decided to stick to the convention ``service_name.data_asset_name`` where ``service_name`` can be anything that doesn't contain a dot and ``data_asset_name`` is the expected name of the object starting with the protocol like ``hdfs://namenode/user/hive/warehouse`` and ``s3://bucket/user/hive/warehouse``. The final result could be something like ``marketing_lake.s3://bucket/user/hive/warehouse``. We will keep the API to find the list of locations of a location:
```
marketing_lake.s3://bucket/user/hive/warehouse
marketing_lake.s3://bucket/user/hive
marketing_lake.s3://bucket/user
marketing_lake.s3://bucket
```

**Comment by harshach** [comment]
Thanks @amiorin . This looks great.

**Review by harshach — APPROVED** [review]

**Pull request merged**
