### PR TITLE
MINOR: CI: added doctest

### PR DESCRIPTION
**Pull request by sushi30**
### Describe your changes:

Fixes <issue-number>

I worked on ... because ...

#
### Type of change:

- [ ] Bug fix
- [ ] Improvement
- [ ] New feature
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/developers/contribute) document.
- [ ] My PR title is `Fixes <issue-number>: <short explanation>`
- [ ] I have commented on my code, particularly in hard-to-understand areas. 
- [ ] For JSON Schema changes: I updated the migration scripts or explained why it is not needed.

### CODE REVIEW

**Comment by TeddyCr** [comment]
What would be the benefit (vs using unit test)

**Comment by sushi30** [comment]
@TeddyCr doctest execution in CI

**Comment by sushi30** [comment]
The examples in the docs are tested so you get 2:1 documentation and testing. Its very useful for util functions with very defined scopes.

**Comment by sushi30** [comment]
Widely used in python ecosystem (for example [pandas](https://github.com/pandas-dev/pandas/blob/d96646219618e007f64ee49e0a6e20f4aea761b5/ci/code_checks.sh#L60))

**Comment by pmbrull** [comment]
> @sushi30 adding an example to the doc is a good use case. I think we should keep 1 testing strategy though so we can easily align as a team.
> 
> cc @pmbrull if you have any thoughts.

+1 on keeping it simple. Agree that we have room for improvement on the docstrings, but we should make it simpler for us to write the tests. Having too many options at this point will add too much noise both for us and the community

**Pull request closed without merging**
