### PR TITLE
UI (#6189) | PR 1 |  Extends Search api to support custom Elasticsearch filters

### PR DESCRIPTION
**Pull request by mosiac1**
### Describe your changes :
This is the first PR for the query builder feature tracked by #6189.

API changes:

###  - `/search` now accepts `query_filter` and `post_filter` parameters

These accept Elasticsearch queries in JSON format (e.g: Boolean query https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-bool-query.html). These are used to filter and post filter the results and aim to replace the functionality currently achieved through string queries (EQL),

`query_filter` is used as a filter on top of the string search query creator from the `q` parameter.  This the how most searches should filter their results. These filters affect the scoring of hits. (more info: https://www.elastic.co/guide/en/elasticsearch/reference/current/query-filter-context.html)

`post_filter` is used as a final filter, its functionality is closely tied with Elasticseach-specific functionality (https://www.elastic.co/guide/en/elasticsearch/reference/current/filter-search-results.html#post-filter). This is slower than `query_filter`, but it does not affect scoring and __aggregations__. The main use case is the facet filter used on the Explore page. (this is not implemented in this PR).

### - UI calls to `/seach` and `/suggest` consolidated to 2 function in `searchAPI.ts`

Calls to the search API were spread out to various functions. `searchQuery` and `suggestQuery` are now the 2 points of contact with the API. These include functionality to adapt the results to a format well suited to the UI.

Added types to correctly represent the data returned. Cleaned up `Formatted*` types, now using generated types.

### - Added `fetch_source` and `include_fields` to `/search` and `/suggest`

With these parameters, callers can control if they need the body of objects and how much of that body they need. In many cases in the UI, there is no need to pull entire objects from Elasticsearch, this should decrease load times.

This is also fully supported by the type system in the UI.

#
### Type of change :

- [x] Improvement
- [x] New feature

#
### Frontend Preview (Screenshots) :
query builder

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/developers/contribute) document.
- [x] I have commented on my code, particularly in hard-to-understand areas.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] All new and existing tests passed.

#
### Reviewers

Frontend: @open-metadata/ui
Backend: @open-metadata/backend

### CODE REVIEW

**Comment by harshach** [comment]
Thanks @mosiac1 . We are a week away from 0.12.0 release. Will review and merge but will make it part of 0.12.1 as we need to do Advanced Search UX.
cc @chirag-madlani @devyani-kaushik  we need to look at the mocks for the advanced search design.

**Comment by mosiac1** [comment]
I think this could go in 0.12.0 - it doesn't change functionality and its well tested

On the UX part, yeah we'll probably not get it done in one week.

**Comment by harshach** [comment]
@mosiac1 mostly the UI part is what stopping getting this into the 0.12.0 release. If you want to separate this into backend and UI PRs we can get the search backend changes in for 0.12

**Comment by harshach** [comment]
one help would be great from @mosiac1 is to add integration tests similar to what we are doing with mysql/postgres and om . It can be a separate PR all together but we are missing similar coverage that we have else where in search

**Comment by mosiac1** [comment]
I've split the feature into multiple PRs. This one functionally is just backend changes, with small refactoring and typescript changes to the UI.

The next PR will have the bulk of the changes - this is just a setup.

I split it up because it was ~10k lines long, which is impossible to review effectively.

**Comment by mosiac1** [comment]
I agree with the tests, they are very needed. I think they should go to another PR.

**Comment by mosiac1** [comment]
@harshach @ShaileshParmar11 

Could we get some 👀 on this, please? I would really appreciate if we could get this moving since most new changes to the UI cause conflicts and I have to keep rebasing. Thank you!

**Comment by harshach** [comment]
@mosiac1 can you do one last merge with latest main. We will merge it in

**Review by Sachin-chaurasiya — APPROVED** [review]

**Comment by harshach** [comment]
@mosiac1 can you please help us why the advanced search that you have in the image is not available here.

**Comment by mosiac1** [comment]
> @mosiac1 can you please help us why the advanced search that you have in the image is not available here.

I had to split the feature into a few PRs because of the size, i tried to outline it here: https://github.com/open-metadata/OpenMetadata/issues/6189#issuecomment-1228407492

This is the first one and doesn't have the query builder, it is a preparation step. As soon as we are done with this one I can open the next PR

**Comment by mosiac1** [comment]
@harshach @Sachin-chaurasiya Rebased on the changes on main and tested locally. Would really appreciate a review.

**Comment by mosiac1** [comment]
Closing PR, will reopen another one. Reasoning:  https://github.com/open-metadata/OpenMetadata/issues/6189#issuecomment-1271571158

**Pull request closed without merging**
