### PR TITLE
Style : Changing App-bar Layout.

### PR DESCRIPTION
**Pull request by Sachin-chaurasiya**
see #1453 
### Describe your changes :

I worked on the App bar because of the need to change the layout of the app bar. to know more see the attached screenshot.

#
### Type of change :

- [x] Improvement

#
### Frontend Preview (Screenshots) :
image

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/open-source-community/developer) document.
- [x] I have performed a self-review of my own. 
- [x] I have tagged my reviewers below.
- [ ] I have commented on my code, particularly in hard-to-understand areas.
- [x] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [x] All new and existing tests passed.

#
### Reviewers
@shahsank3t, @darth-coder00

### CODE REVIEW

**Review by shahsank3t — CHANGES_REQUESTED** [review]
@Sachin-chaurasiya 
In the header, we should only show user image with a dropdown icon and on clicking, we can show something as:
image
And below that, the version and Logout options.

**Comment by Sachin-chaurasiya** [comment]
> @Sachin-chaurasiya In the header, we should only show user image with a dropdown icon and on clicking, we can show something as: image And below that, the version and Logout options.

@shahsank3t sure will make the changes.

**Review by shahsank3t — APPROVED** [review]
Thanks @Sachin-chaurasiya.
Looks good to me.
@darth-coder00 please review once.

**Review by darth-coder00 — APPROVED** [review]
LGTM!

**Pull request merged**
