### PR TITLE
Fix #1356: Add new entities to ES index from OpenMetadata server

### LINKED ISSUE #1356: Add new entities to ES index from OpenMetadata server
Currently, once we run ingestion to fetch data from data sources into OM , user needs to run indexing workflow as well.
If the indexing workflow didn't run then the entities that are ingested in OM will not show up in the UI. This is a bad UX.
This issue is to build indexing directly from OM and we will still keep the metadata indexing workflow to catch any issues and it will provide a way update the index in clean fashion.

### PR DESCRIPTION
**Pull request by harshach**
### Describe your changes :
see #1356 
#
### Type of change :

- [x] Improvement

#
### Frontend Preview (Screenshots) :
<p align="center">For frontend related change, please link screenshots of your changes preview! Optional for backend related changes.
</p>

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/open-source-community/developer) document.
- [ ] I have performed a self-review of my own. 
- [ ] I have tagged my reviewers below.
- [ ] I have commented on my code, particularly in hard-to-understand areas.
- [ ] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [x] All new and existing tests passed.

#

### CODE REVIEW

**Comment by harshach** [comment]
@sureshms Need your review on this. Made few changes
ElasticSearch index needs full body of the event when the entity is created. Example Table, we need its description, columns, followers, owners, usageSummary, database, **databaseService**
On updates we can use changeevents to get the updates we require to index

1. Added createFields in EntityRepository to return fields we need upon creation of new entity
2. added databaseService to Table Entity. This would make life easier on the creation of the table entity in ES index as we support filtering tables based on databaseService type.  This feels like logical extension to database so added databaseService as additional field.

Let me know if this makes sense, I'll add few more tests to cover new changes.

**Comment by harshach** [comment]
image

image

@sureshms 
1. For Table  we can handle the databaseService and that should be good enough
2. In case of dashboard, we are returning charts but it doesn't contain name, displayName and description populated.

If I keep the changes I made this works. But if there is a better way to handle this let me know.

**Comment by harshach** [comment]
@sureshms 
prepare is wrong place to populate these dependendant fields
1. prepare is getting called before we do update or create
2. database for a table will not be loaded as the relation is not created yet. So trying to populate databaseService for the table will results in database not found

The diff I've is following the putFields, patchFields. Added createFields and calls the setFields post creation of the entity. 
Let me know if I am missing something and if there is a better way to do this.

**Comment by harshach** [comment]
@darth-coder00 @Sachin-chaurasiya @ayush-shah @sureshms 
This PR handles the indexing of Table, Topic, Pipeline, Dashboard etc..
1. If the elastic search is not started, while ingestion is extracting entities and ingesting into OM, then these will not available in search
2. If the elastic search is not available or having stability issues during the ingestion of new entities into OM , the events will be missed
3. Event Handlers will run a Aysnc call and doesn't wait for success or failure and doesn't retry. As these are responses going back to the user. So any errors here means a missed update to ES index.

To resolve such issues, Users still need to run the metadata_to_es pipeline as a way of reconciling the overall index in case of any errors this pipeline will help fix the issues.

**Review by sureshms — APPROVED** [review]

**Pull request merged**
