### PR TITLE
Fix #6936: testPlatforms is required field in testSuite and createTes…

### LINKED ISSUE #6936: `testPlatforms` is required field in testSuite and createTestSuite schema
`testPlatforms` is required field in testSuite and createTestSuite schema, but field is not presten in the property

effect:-
Typescript file is not getting generated due to above issue

### PR DESCRIPTION
**Pull request by harshach**
…tSuite schema

### Describe your changes :

I worked on the ..... because ...

#
### Type of change :

- [x] Bug fix

#
### Frontend Preview (Screenshots) :
<p align="center">For frontend related change, please link screenshots of your changes preview! Optional for backend related changes.
</p>

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/developers/contribute) document.
- [ ] I have commented on my code, particularly in hard-to-understand areas.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [x] All new and existing tests passed.

#

### CODE REVIEW

**Comment by harshach** [comment]
@ShaileshParmar11 can you check why the UI unit tests are failing

**Comment by ShaileshParmar11** [comment]
> @ShaileshParmar11 can you check why the UI unit tests are failing

Yes, checking!

**Review by ShaileshParmar11 — APPROVED** [review]

**Review by TeddyCr — APPROVED** [review]

**Comment by ShaileshParmar11** [comment]
Hi @harshach Java check style is failing, is it fine to merge with it?

**Comment by harshach** [comment]
@ShaileshParmar11 checking

**Comment by harshach** [comment]
@ShaileshParmar11 pushed a fix. we can merge it after the build passes

**Comment by ShaileshParmar11** [comment]
> @ShaileshParmar11 pushed a fix. we can merge it after the build passes

Thanks, I'll merge once checks are pass!

**Pull request merged**
