### PR TITLE
fix(ui): entity selection for es re-indexing

### PR DESCRIPTION
**Pull request by chirag-madlani**
### Describe your changes:

Fix User expierence around selecting entities for Elasticsearch Re-Indexing

Screenshot 2023-03-29 at 5 34 26 PM

I worked on ... because ...

#
### Type of change:

- [x] Bug fix
- [x] Improvement
- [ ] New feature
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/developers/contribute) document.
- [ ] My PR title is `Fixes <issue-number>: <short explanation>`
- [ ] I have commented on my code, particularly in hard-to-understand areas. 
- [ ] For JSON Schema changes: I updated the migration scripts or explained why it is not needed.

### CODE REVIEW

**Comment by harshach** [comment]
@chirag-madlani do we have an option for "All"

**Comment by harshach** [comment]
@chirag-madlani can we do this similar to policies page 
image

Lets re-use this component

**Comment by chirag-madlani** [comment]
@harshach updated UI as per comments

**Review by nahuelverdugo — APPROVED** [review]
✅ from backend

**Review by harshach — APPROVED** [review]

**Pull request merged**
