### PR TITLE
Refactor ServiceConnectionDetails component

### PR DESCRIPTION
**Pull request by ayush-shah**
Custom Logic for the Pipeline scoped to Airflow

### Describe your changes:

Fixes an error where other pipeline connectors with `connection` attribute fails because of the custom logic for airflow connector

#
### Type of change:

- [ ] Bug fix
- [ ] Improvement
- [ ] New feature
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/developers/contribute) document.
- [ ] My PR title is `Fixes <issue-number>: <short explanation>`
- [ ] I have commented on my code, particularly in hard-to-understand areas. 
- [ ] For JSON Schema changes: I updated the migration scripts or explained why it is not needed.

### CODE REVIEW

**Comment by ayush-shah** [comment]
Screenshot 2024-10-07 at 2 41 42 PM
Screenshot 2024-10-07 at 2 41 50 PM
Screenshot 2024-10-07 at 3 01 33 PM

Tested on multiple dashboard connection settings to test out the changes

**Review by chirag-madlani — APPROVED** [review]

**Comment by chirag-madlani** [comment]
@ayush-shah py-tests are failing can you check?

**Comment by ayush-shah** [comment]
> @ayush-shah py-tests are failing can you check?

Failing Pytests are not related to the above PR, looks intermittent ( Lost connection to MySQL server during ), and some are already fixed in main.

**Comment by chirag-madlani** [comment]
@ayush-shah feel free to merge it 🚀

**Pull request merged**
