### PR TITLE
Issue 2727: Added Databricks Connector

### LINKED ISSUE #2727: Databricks Ingestion connector
**Describe the solution you'd like**
Add databricks ingestion connector using [databricks-dbapi](https://pypi.org/project/databricks-dbapi/) sqlalchemy package

### PR DESCRIPTION
**Pull request by ulixius9**
### Describe your changes :

Fix #2727: Added Databricks Connector

#
### Type of change :

- [x] New feature

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/open-source-community/developer) document.
- [x] I have performed a self-review of my own. 
- [x] I have tagged my reviewers below.
- [ ] I have commented on my code, particularly in hard-to-understand areas.
- [x] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [x] All new and existing tests passed.

#
### Reviewers

Ingestion: @harshach @ayush-shah @pmbrull

### CODE REVIEW

**Comment by pmbrull** [comment]
Hi @ulixius9, thanks for the PR! Just one question (apart from a similar comment that could apply here from your other [PR](https://github.com/open-metadata/OpenMetadata/pull/2747#issuecomment-1038963315)), why are we using https://github.com/crflynn/databricks-dbapi?

Looks like the package is not maintained anymore and there are other alternatives, we might want to take a look at them.

**Comment by harshach** [comment]
@pmbrull @ulixius9 looks like we have https://pypi.org/project/sqlalchemy-databricks/

**Comment by ulixius9** [comment]
@harshach This package also doesn't seem very active and it's in the first version

**Comment by pmbrull** [comment]
> @pmbrull @ulixius9 looks like we have https://pypi.org/project/sqlalchemy-databricks/

We could test this one as well https://pypi.org/project/databricks-sql-connector/, seems supported directly by databricks

**Comment by harshach** [comment]
@ulixius9 can you look into the above ^

**Comment by ulixius9** [comment]
ok @harshach @pmbrull, will try out databricks-sql-connector

**Review by ayush-shah — APPROVED** [review]

**Pull request merged**
