### PR TITLE
Issue-3234: Rename default in role_entity to defaultRole

### PR DESCRIPTION
**Pull request by harshach**
### Describe your changes :
see #3234 

#
### Type of change :

- [x] Improvement

#
### Frontend Preview (Screenshots) :
<p align="center">For frontend related change, please link screenshots of your changes preview! Optional for backend related changes.
</p>

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/open-source-community/developer) document.
- [ ] I have performed a self-review of my own. 
- [ ] I have tagged my reviewers below.
- [ ] I have commented on my code, particularly in hard-to-understand areas.
- [ ] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [x] All new and existing tests passed.

#

### CODE REVIEW

**Review by vivekratnavel — APPROVED** [review]

**Comment by mithmatt** [comment]
@harshach  This parameter is also used in UI codebase, we need to change that too. 
Besides that these changes look good from backend

**Comment by harshach** [comment]
@Sachin-chaurasiya check if we need to make any changes on the UI side

**Comment by mithmatt** [comment]
https://github.com/open-metadata/OpenMetadata/blob/main/openmetadata-ui/src/main/resources/ui/src/pages/RolesPage/RolesPage.component.tsx#L172

**Comment by Sachin-chaurasiya** [comment]
> @Sachin-chaurasiya check if we need to make any changes on the UI side

@harshach, Changes for UI is done.

**Pull request merged**
