### PR TITLE
UI : Added missing connector icons

### LINKED ISSUE #8712: Missing Connector Icons in UI
**Feature**
Below are the connectors for which icons are missing in UI

- [ ] Domo Database
- [ ] Kinesis
- [ ] Domo Dashboard
- [ ] QuickSight
- [ ] Domo Pipeline
- [ ] GluePipeline
- [ ] Nifi
- [ ] SageMaker

**Describe the task**

### PR DESCRIPTION
**Pull request by Ashish8689**
### Describe your changes :

- Issue : Closes #8712
- Added missing connector icons

#
### Type of change :

- [x] Bug fix

#
### Frontend Preview (Screenshots) :
image
image
image
image
image
image

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/developers/contribute) document.
- [ ] I have commented on my code, particularly in hard-to-understand areas.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [x] All new and existing tests passed.

#
### Reviewers
 @open-metadata/ui

### CODE REVIEW

**Comment by Sachin-chaurasiya** [comment]
@Ashish8689 Can we add icon for the custom ML model as well?

**Comment by Ashish8689** [comment]
> @Ashish8689 Can we add icon for the custom ML model as well?

@Sachin-chaurasiya  It's already having a custom icon.

**Comment by Sachin-chaurasiya** [comment]
> > @Ashish8689 Can we add icon for the custom ML model as well?
> 
> @Sachin-chaurasiya It's already having a custom icon.

image


Are these icons are same?

image

**Comment by Ashish8689** [comment]
@Sachin-chaurasiya  this is the approved icon for custom mlmodal services.

**Review by Sachin-chaurasiya — APPROVED** [review]

**Comment by Sachin-chaurasiya** [comment]
@Ashish8689 , Sonar cloud check if failing.

**Review by Sachin-chaurasiya — APPROVED** [review]

**Pull request merged**
