### PR TITLE
[Issue-1099] - Update MLModel Ingestion

### PR DESCRIPTION
**Pull request by pmbrull**
### Describe your changes :

This PR fixes https://github.com/open-metadata/OpenMetadata/issues/1099

After the refactor of the `Model` Entity to `MLModel` we had to update the tests of `OpenMetadata`.

Moreover, as we added some extra properties `MLFeatures` and `MLHyperParameters`, we have added a test exemplifying the usage in the Python code.

Updated the ML Model API descriptions as well

Thanks!

#
### Type of change :

- [ ] Bug fix
- [x] Improvement
- [ ] New feature
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/open-source-community/developer) document.
- [x] I have performed a self-review of my own. 
- [x] I have tagged my reviewers below.
- [x] I have commented on my code, particularly in hard-to-understand areas.
- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] All new and existing tests passed.

#
### Reviewers
@harshach @ayush-shah

### CODE REVIEW

**Review by harshach — APPROVED** [review]
Thanks for handling this. Missed during the refactoring.

**Comment by pmbrull** [comment]
@harshach no prob had to update the tests anyway for the properties!

I had a question regarding the refactor. Shall we also change the API tags from `models` to `mlModels`? I can do this in this same PR.

Thanks

**Comment by harshach** [comment]
@pmbrull yes we should mark them as mlModels. If you are going to update the same PR will wait or we can open another one.

**Comment by pmbrull** [comment]
> @pmbrull yes we should mark them as mlModels. If you are going to update the same PR will wait or we can open another one.

Thanks, @harshach, done! Changed some descriptions as well.

**Pull request merged**
