### PR TITLE
Update Chinese i18n locale

### PR DESCRIPTION
**Pull request by louie007**
### Describe your changes:

Improved Chinese translation, all texts have been reviewed carefully, I hope this helps.

openmetadata-i18n

#
### Type of change:

- [ ] Bug fix
- [x] Improvement
- [] New feature
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/developers/contribute) document.
- [ ] My PR title is `Fixes <issue-number>: <short explanation>`
- [ ] I have commented on my code, particularly in hard-to-understand areas. 
- [] For JSON Schema changes: I updated the migration scripts or explained why it is not needed.

### CODE REVIEW

**Comment by lutinglt** [comment]
@louie007 Hi, can you merge my PR? #17102

I have different opinions about the translation of domains, first of all, domains should be translated as “域” not “领域”, because people call subject domains “主题域” not “主题领域”.

Secondly, the domain here is the concept of data domains, rather than specifically referring to business domains, business domains and data domains are different perspectives, I personally believe that the concept of data domains include business domains, about this part of the content can refer to [Microsoft's documents](https://learn.microsoft.com/zh-cn/azure/cloud-adoption-framework/scenarios/cloud-scale-analytics/architectures/data-domains)

**Comment by louie007** [comment]
> @louie007 Hi, can you merge my PR? #17102
> 
> I have different opinions about the translation of domains, first of all, domains should be translated as “域” not “领域”, because people call subject domains “主题域” not “主题领域”.
> 
> Secondly, the domain here is the concept of data domains, rather than specifically referring to business domains, business domains and data domains are different perspectives, I personally believe that the concept of data domains include business domains, about this part of the content can refer to [Microsoft's documents](https://learn.microsoft.com/zh-cn/azure/cloud-adoption-framework/scenarios/cloud-scale-analytics/architectures/data-domains)

Thank you for sharing your perspective on the translation of "domains."

I understand your point about using “域” for subject domains, and I appreciate the distinction between data domains and business domains. However, I chose to translate "domains" as “领域” for a couple of reasons:

**Consistency and Clarity**: While "域" is concise, it can easily be mistaken for website domains, which might confuse users who are not familiar with the context. “领域” provides a clearer and more specific understanding in this context.

**Aesthetic Consideration**: Our goal is to keep the labels in the sidebar aesthetically pleasing and consistent, with each label being 4 characters long. “业务领域” fits this requirement and maintains a balanced appearance.

**Business Relevance**: All data domains ultimately serve business purposes. Using “业务领域” emphasizes the broader context and relevance to business activities, aligning with the holistic view of data and its applications.

I hope this clarifies my reasoning. I'm open to further discussion to ensure we achieve the best outcome for the project.

**Comment by lutinglt** [comment]
> > @louie007 Hi, can you merge my PR? #17102
> > I have different opinions about the translation of domains, first of all, domains should be translated as “域” not “领域”, because people call subject domains “主题域” not “主题领域”.
> > Secondly, the domain here is the concept of data domains, rather than specifically referring to business domains, business domains and data domains are different perspectives, I personally believe that the concept of data domains include business domains, about this part of the content can refer to [Microsoft's documents](https://learn.microsoft.com/zh-cn/azure/cloud-adoption-framework/scenarios/cloud-scale-analytics/architectures/data-domains)
> 
> Thank you for sharing your perspective on the translation of "domains."
> 
> I understand your point about using “域” for subject domains, and I appreciate the distinction between data domains and business domains. However, I chose to translate "domains" as “领域” for a couple of reasons:
> 
> **Consistency and Clarity**: While "域" is concise, it can easily be mistaken for website domains, which might confuse users who are not familiar with the context. “领域” provides a clearer and more specific understanding in this context.
> 
> **Aesthetic Consideration**: Our goal is to keep the labels in the sidebar aesthetically pleasing and consistent, with each label being 4 characters long. “业务领域” fits this requirement and maintains a balanced appearance.
> 
> **Business Relevance**: All data domains ultimately serve business purposes. Using “业务领域” emphasizes the broader context and relevance to business activities, aligning with the holistic view of data and its applications.
> 
> I hope this clarifies my reasoning. I'm open to further discussion to ensure we achieve the best outcome for the project.

Domain can be translated as either “域” or “领域”, I prefer “域” because that's what everyone says, it's more familiar, but it doesn't affect the meaning.

But the definition of a data domain is clear and unambiguous, and in this English description of a new domain 
> A data mesh is a decentralized data architecture that organizes data by a specific business domain following the concepts of domain-oriented design. Teams take ownership of both operational and analytical data that belongs to the domain. Based on the Data Contract, consumers are provided with Data as a Product. It is powered by Domain-agnostic self-serve data infrastructure. There are three types of domains: Consumer-aligned, Aggregate, and Source-aligned. Domains have Enabling Teams for consulting.

 it means that the subclasses of the domain are not divided according to business, and their parents are not supposed to be business domains.

But I prefer to translate the label into two characters, search and discovery are a parent-child relationship rather than a hierarchy, search first, then discovery, and observation and quality control, also observation first, then quality control.

My suggestion is to translate first-level labels into two characters, which is simple and clear, and as a metadata manager, the translation of fields into “领域” allows enough freedom for various users to understand and categorize their own data domains.

**Comment by harshach** [comment]
@chirag-madlani @karanh37 any reason we are not merging this?

**Comment by chirag-madlani** [comment]
@harshach already merged changes with [this PR](https://github.com/open-metadata/OpenMetadata/pull/13135)
We can close this one as it's outdated.

**Pull request closed without merging**
