### PR TITLE
fix: rendering of more complex pipelines tree view

### PR DESCRIPTION
**Pull request by mgorsk1**
### Describe your changes:

Fixes [14599](https://github.com/open-metadata/OpenMetadata/issues/14599)

I worked on fixing executionUtils getTreeData method because it's current implementation is not suitable for precise depicting parent > child relationships between pipeline tasks in Tree view of Executions tab.

**Before (notice lack of process_task_X in Tree view of Executions tab)**

https://github.com/open-metadata/OpenMetadata/assets/5680655/2b7ac602-2ac3-4609-93ea-426a7dd59da9

**After:**

https://github.com/open-metadata/OpenMetadata/assets/5680655/081dfdb4-d74d-4bd8-9bf3-ce188a021b06

#
### Type of change:

- [x] Bug fix
- [ ] Improvement
- [ ] New feature
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/developers/contribute) document.
- [x] My PR title is `Fixes <issue-number>: <short explanation>`
- [x] I have commented on my code, particularly in hard-to-understand areas. 
- [x] For JSON Schema changes: I updated the migration scripts or explained why it is not needed.

### CODE REVIEW

**Comment by harshach** [comment]
hi @mgorsk1 Thanks for the PR. We will review and merge it in 
cc @chirag-madlani

**Comment by harshach** [comment]
@ShaileshParmar11 did your DAG changes for this merged in? can you work with @mgorsk1 to get this PR in.

**Comment by ShaileshParmar11** [comment]
Yes my UI changes merged! @harshach

**Comment by mgorsk1** [comment]
so are we happy about this PR @ShaileshParmar11? I have fixed all the linting issues and ci seems to be satisfied.

**Review by chirag-madlani — APPROVED** [review]

**Comment by chirag-madlani** [comment]
Thank you @mgorsk1

**Comment by mgorsk1** [comment]
🤝🏼

**Pull request merged**
