### PR TITLE
ui: feedback 1.0 part-1

### PR DESCRIPTION
**Pull request by ShaileshParmar11**
### Describe your changes:

- [On databaseschemapage, Remove Scale, Precision, Ordinal Position & sort data based on Ordinal Position](https://github.com/open-metadata/OpenMetadata/issues/10543#issuecomment-1501904784)
- [Column count in summary does not match column count in profile](https://github.com/open-metadata/OpenMetadata/issues/10543#issuecomment-1490844283)
- [Cancel flow for creating test case is broken](https://github.com/open-metadata/OpenMetadata/issues/10543#issuecomment-1513407530)

image

https://user-images.githubusercontent.com/71748675/233264393-f723bb51-70e6-4add-8841-98ed89a2b5ae.mov

https://user-images.githubusercontent.com/71748675/233253039-78f67082-8e58-479c-9163-9b89d29c542f.mov

#
### Type of change:

- [ ] Bug fix
- [ ] Improvement
- [ ] New feature
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/developers/contribute) document.
- [ ] My PR title is `Fixes <issue-number>: <short explanation>`
- [ ] I have commented on my code, particularly in hard-to-understand areas. 
- [ ] For JSON Schema changes: I updated the migration scripts or explained why it is not needed.

### CODE REVIEW

**Review by chirag-madlani — DISMISSED** [review]
Can you attach video of updating description / tags on random index to make sure it's not breaking anything

**Comment by ShaileshParmar11** [comment]
Hi @chirag-madlani I have attached a video of updating the description of the column!

**Comment by harshach** [comment]
@ShaileshParmar11 when the user goes to column profile and clicks "Add Test" against a column and then cancel's it , the page should return to column profile. Where as In the video you attached its going to table profile

**Comment by ShaileshParmar11** [comment]
> @ShaileshParmar11 when the user goes to column profile and clicks "Add Test" against a column and then cancel's it , the page should return to column profile. Where as In the video you attached its going to table profile

updated code as well as video

**Review by chirag-madlani — APPROVED** [review]

**Pull request merged**
