### PR TITLE
Add googleformatter to auto-format Java classes

### PR DESCRIPTION
**Pull request by mithmatt**
- Add new mvn plugin dependency
- Format all Java classes

https://github.com/google/google-java-format
Google Java Style Guide: https://google.github.io/styleguide/javaguide.html

### Describe your changes :

I worked on the this because #1422 

#
### Type of change :

- [ ] Bug fix
- [ ] Improvement
- [ ] New feature
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation

#
### Frontend Preview (Screenshots) :
<p align="center">For frontend related change, please link screenshots of your changes preview! Optional for backend related changes.
</p>

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/open-source-community/developer) document.
- [x] I have performed a self-review of my own. 
- [x] I have tagged my reviewers below.
- [ ] I have commented on my code, particularly in hard-to-understand areas.
- [x] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [x] All new and existing tests passed.

#
### Reviewers

Backend: @sureshms @harshach

### CODE REVIEW

**Comment by amiorin** [comment]
Is there a way to ask the formatter to ignore a method? The original was more readable to me.
image

**Comment by pmbrull** [comment]
Hi @mithmatt thanks for this, I am in having automated and standardised formatting.

Could we have the goal though execute at compile? Or is this already happening and I missed it?

**Comment by mithmatt** [comment]
> Hi @mithmatt thanks for this, I am in having automated and standardised formatting.
> 
> Could we have the goal though execute at compile? Or is this already happening and I missed it?

@pmbrull 

I've configured it to be process-sources phase, which happens before compile phase in mvn lifecycle

**Comment by mithmatt** [comment]
> Is there a way to ask the formatter to ignore a method? The original was more readable to me. image


@amiorin 

Apparently Google's formatter designed not to be configurable
https://github.com/google/google-java-format/wiki/FAQ#i-just-need-to-configure-it-a-bit-differently-how

> The explicit goals of this tool are to bring consistency to the codebase, and to free developers from arguments over style choices. It is an explicit non-goal to support developers' individual preferences, and in fact this would work directly against our primary goals.


There are other configurable options like https://github.com/revelc/formatter-maven-plugin where we can provide an xml config on how the formatting should be. 


I'm fine with either one -- main motivation is to take away the cognitive load of formatting away from developers as much as possible.

@pmbrull @amiorin  What do you think?

**Comment by amiorin** [comment]
👍 for adopting the Google Java Format. We will change the String concatenation if readability is not good enough after formatting.

**Comment by pmbrull** [comment]
Thanks, @mithmatt for the changes, LGTM. I believe that the google format is the one we use during CI, so this will make our lives way easier.

**Comment by mithmatt** [comment]
> Thanks, @mithmatt for the changes, LGTM. I believe that the google format is the one we use during CI, so this will make our lives way easier.

I'm temporarily removing the checkstyle job from the CI ... will put it back in the future (we may also not need it, because code gets formatted as we compile)

**Comment by pmbrull** [comment]
> > Thanks, @mithmatt for the changes, LGTM. I believe that the google format is the one we use during CI, so this will make our lives way easier.
> 
> I'm temporarily removing the checkstyle job from the CI ... will put it back in the future (we may also not need it, because code gets formatted as we compile)

Do we want that removed? IMO we should still have the quality gate to make sure the code is properly compiled (and therefore formatted) before opening a PR. WDYT?

**Comment by mithmatt** [comment]
> > > Thanks, @mithmatt for the changes, LGTM. I believe that the google format is the one we use during CI, so this will make our lives way easier.
> > 
> > 
> > I'm temporarily removing the checkstyle job from the CI ... will put it back in the future (we may also not need it, because code gets formatted as we compile)
> 
> Do we want that removed? IMO we should still have the quality gate to make sure the code is properly compiled (and therefore formatted) before opening a PR. WDYT?

In the current PR, I'm removing it since the style is not an exact match of google formatter being introduced in this PR.
Which means, the CI job would fail and block this PR. 

My strategy:
- Get the formatter plugin in as first PR within a window where not many changes are happening among other contributors (minimize merge conflicts for everyone who has in-flight changes/PRs)
- Come back and add the CI that uses the same formatting style

**Comment by amiorin** [comment]
I would use an incremental approach. The Google Java Format is checking only the java files changed in the PR. If you update all the files once the users working on their branches will have a hard time rebasing their code. After some weeks I would apply on the full project to catch the files we don't change often. WDYT?

**Comment by amiorin** [comment]
**We will adopt the Google Java Format. 🎉** 

I was trying the CLI on CollectionDAO and we need to use [phantom comments](https://stackoverflow.com/a/44315907) to preserve the formatting of SQL statements.

If someone is working on a PR @sureshms suggested running the CLI on the PR before rebasing so that the new style will not get in the way if there are conflicts.

We could do a big bang approach or slowly update the files using PRs to look out for SQL comments and toString methods. 

WDYT?

image
image

**Comment by harshach** [comment]
@amiorin @mithmatt lets hold until the 0.7 release. We can merge this after. 
@amiorin we can address the toString and sql in another patch after we merge this.

**Comment by amiorin** [comment]
👍

**Comment by mithmatt** [comment]
> @amiorin @mithmatt lets hold until the 0.7 release. We can merge this after. @amiorin we can address the toString and sql in another patch after we merge this.

+1 to holding until after the 0.7 release.

**Review by amiorin — APPROVED** [review]

**Pull request merged**
