### PR TITLE
feat(ui): supported charts in assets

### PR DESCRIPTION
**Pull request by Ashish8689**
### Describe your changes:

- I worked on supported charts in assets

image
image
image

#
### Type of change:

- [ ] Bug fix
- [ ] Improvement
- [ ] New feature
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/developers/contribute) document.
- [ ] My PR title is `Fixes <issue-number>: <short explanation>`
- [ ] I have commented on my code, particularly in hard-to-understand areas. 
- [ ] For JSON Schema changes: I updated the migration scripts or explained why it is not needed.

### CODE REVIEW

**Comment by harshach** [comment]
@Ashish8689 is this still relevant? can we close this out

**Comment by Ashish8689** [comment]
@harshach I think we were planning to support chart as separate entity in release 1.3, in that case we need to have it, and if not  then we can close this out.

**Comment by harshach** [comment]
@Ashish8689 let's add separate page and update this PR.

**Comment by Ashish8689** [comment]
Yes @harshach will do it.

**Comment by chirag-madlani** [comment]
@Ashish8689 Let's work on it in a new PR

**Pull request closed without merging**
