### PR TITLE
Fixes #6133 - Add support for Team Hiearchy

### LINKED ISSUE #6133: Add support for team hiearchy
Currently, the only people hierarchy supported in OpenMetadata is `teams` and each team is a group of `users`. This issue adds support for a more comprehensive team hierarchy.

# Why?
1. In OpenMetadata, an admin is an admin for the entire organization. There is no delegated admin model where an admin can be scoped to a specific team or parts of the organization.
2. When authoring policies, having a team hierarchy can help in authoring hierarchical policies. For example, a policy at an organizational level applies to everyone. A policy at a business unit level or department level applies to the users and resources belonging to that team.
3. In the future, we can use this hierarchy to help users set the scope of OpenMetadata UI to a business unit, division, or department to limit their focus on the part of the organization they are interested in instead of the entire metadata of an organization.

# How?
- We are adding `teamType` that can be `Organization`, `Business Unit`, `Division`, and `Department` (default team type).
- `Organization` is the root team in the hierarchy. It can't have a parent. It can have children of type `Business Unit`, `Division`, or `Department` along with `Users` directly as children (who are without teams).
- `BusinessUnit` is the next level of the team in the hierarchy. It can have `Business Unit`, `Division`, and `Department` as children. It can only have ** one parent ** either of type `Organization`, or `Business Unit`.
- `Division` is the next level of the team in the hierarchy below `Business Unit`. It can have `Division`, and `Department` as children. It can only have ** one parent ** of type `Organization`, `Business Unit`, or `Division`.
- `Department` is the next level of the team in the hierarchy below `Division`. It can have `Department` as children. It can have all the types of teams as parents. ** It can have multiple parents **.

# How does this affect existing OpenMetadata deployments
1. No change is necessary to existing deployments. All the teams start with a flat hierarchy and are directly the children of `Organization`. A default `Organization` is created during OpenMetadata startup and the existing teams are made children of the org.
2. New teams can be added to this hierarchy based on the needs of an organization. A large organization can choose the entire hierarchy - Org -> Business Unit -> Division -> Department. A small organization can just choose Org -> Department -> Department to model a simpler flat organization.

### PR DESCRIPTION
**Pull request by sureshms**
### Describe your changes :

See #6133 for details

#
### Type of change :

- [x] New feature

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/open-source-community/developer) document.
- [x] I have commented on my code, particularly in hard-to-understand areas.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by sureshms** [comment]
@vivekratnavel and @pmbrull, need help with the test failures. Not able to figure it out from the logs.

**Comment by harshach** [comment]
@sureshms teams api changed and sample-data cannot be ingested 
```
File "/Users/harsha/Code/OpenMetadata/ingestion/src/metadata/ingestion/sink/metadata_rest.py", line 547, in write_users
    raise APIError(
metadata.ingestion.ometa.client.APIError: Creating a new team Cloud_Infra

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/harsha/Code/OpenMetadata/ingestion/env/bin/metadata", line 33, in <module>
    sys.exit(load_entry_point('openmetadata-ingestion', 'console_scripts', 'metadata')())
  File "/Users/harsha/Code/OpenMetadata/ingestion/env/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/harsha/Code/OpenMetadata/ingestion/env/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
```

**Comment by harshach** [comment]
@pmbrull this is only happening on the python side. When a field is used by "$ref" , referenced type defaults are not getting applied. This method works in Java

**Comment by harshach** [comment]
@ShaileshParmar11 to fix the above test we need to display TeamType filed from createTeamRequest

**Comment by sureshms** [comment]
> @ShaileshParmar11 to fix the above test we need to display TeamType filed from createTeamRequest

@harshach, TeamType is defaulted to Department. So that should not be the issue...

**Comment by harshach** [comment]
@sureshms so python code generation running into issues, its not generating the teamType default value which in turn causing the sample data to fail. I've to pass it manually until we figure out python issue

**Comment by pmbrull** [comment]
> @pmbrull this is only happening on the python side. When a field is used by "$ref" , referenced type defaults are not getting applied. This method works in Java

Thanks for the fix @harshach . Opened https://github.com/open-metadata/OpenMetadata/issues/6173 to track this. It would be interesting to have these defaults properly propagated

**Comment by harshach** [comment]
> > @pmbrull this is only happening on the python side. When a field is used by "$ref" , referenced type defaults are not getting applied. This method works in Java
> 
> Thanks for the fix @harshach . Opened #6173 to track this. It would be interesting to have these defaults properly propagated

we may need to look into the lib and patch it https://github.com/koxudaxi/datamodel-code-generator

**Comment by sureshms** [comment]
@harshach and @pmbrull, I am setting the default value where the type is defined. Perhaps the default value where the type is "$ref" referenced might work for Python?

**Review by harshach — APPROVED** [review]

**Pull request merged**
