### PR TITLE
Data Governance Docs

### PR DESCRIPTION
**Pull request by ShilpaVernekar**
### Describe your changes:
A section on the Pillars of OpenMetadata has been added.
All the docs around Governance (Glossary) have been added.

1. The Six Pillars of OpenMetadata (Intro)
2. Data Governance (Overview)
3. Glossary and Classification (Overview)
4. What is a Glossary
5. What is Classification
6. What are Tiers
7. How to Setup a Glossary
8. How to Create Glossary Terms
9. How to Bulk Import a Glossary
10. How to Add Assets to Glossary Terms
11. How to Classify Data Assets
12. Best Practices for Glossary and Classification

image

Fixes <issue-number>

I worked on ... because ...

#
### Type of change:

- [ ] Bug fix
- [ ] Improvement
- [ ] New feature
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/developers/contribute) document.
- [ ] My PR title is `Fixes <issue-number>: <short explanation>`
- [ ] I have commented on my code, particularly in hard-to-understand areas. 
- [ ] For JSON Schema changes: I updated the migration scripts or explained why it is not needed.

### CODE REVIEW

**Comment by ShilpaVernekar** [comment]
@harshach - In the article on "How to Classify Data Assets", the last section on "Tag Mapping" needs to be reviewed

**Comment by harshach** [comment]
Thanks @ShilpaVernekar will take a look

**Comment by ShilpaVernekar** [comment]
Looks like the images are not showing up. Will check with @aniketkatkar97

**Comment by ShilpaVernekar** [comment]
Images are appearing now

**Pull request merged**
