### PR TITLE
Fixes #17441: Fixing LDAP Authentication

### LINKED ISSUE #17441: LDAP User Authenticator Issue
**Affected module**
New users are not able login in OM using LDAP authentication.

**Describe the bug**

> DEBUG [2024-08-09 13:48:26,488] [dw-127 - GET /api/v1/users/loggedInUser?fields=profile%2Cteams%2Croles%2Cpersonas%2CdefaultPersona] o.o.s.e.CatalogGenericExceptionMapper - user instance for [myuser@corp.com](mailto:myuser@corp.com) not found

**To Reproduce**

Screenshots or steps to reproduce

**Expected behavior**

**Version:**
 - Python version:
 - OpenMetadata version: OM v.1.4.7
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**
image

### PR DESCRIPTION
**Pull request by m4x1202**
### Describe your changes:

Fixes https://github.com/open-metadata/OpenMetadata/issues/17441

#
### Type of change:
- [x] Bug fix

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/developers/contribute) document.
- [x] My PR title is `Fixes <issue-number>: <short explanation>`
- [ ] I have commented on my code, particularly in hard-to-understand areas. 
- [ ] For JSON Schema changes: I updated the migration scripts or explained why it is not needed.
- [ ] I have added a test that covers the exact scenario we are fixing. For complex issues, comment the issue number in the test for future reference.

### CODE REVIEW

**Comment by harshach** [comment]
Thanks @m4x1202 for the PR.

**Comment by m4x1202** [comment]
@harshach Thanks for looking into this PR. Unfortunately my Java days date a while back 😀 so please let me know if my changes are incorrect/incomplete. Additionally, I don't have much time to continue working on this.
Would it be possible to get this approved in its current state?

**Comment by mohityadav766** [comment]
> @harshach Thanks for looking into this PR. Unfortunately my Java days date a while back 😀 so please let me know if my changes are incorrect/incomplete. Additionally, I don't have much time to continue working on this.
> Would it be possible to get this approved in its current state?

Hi @m4x1202 , Thank you so much for looking into this. We are actively working on the issue, this Pr is addressing, but we have identified a few more scenarios that might need handling for LDAP related to the issue raised.
So for now we are holding this PR , once we have the changes ready we'll be notifying on the issue itself. :)

**Comment by m4x1202** [comment]
@mohityadav766 @harshach with the new version 1.4.8 my users are still not able to log-in. I the merged fix did not work.
May I suggest to please reopen this PR and you have another look at how I tried to fix the issue. I believe this should work.
The linked issue should most likely also be reopened.

**Comment by mohityadav766** [comment]
hi @m4x1202 , can you join the OM slack, let's connect there to take it forward

**Comment by jgrocha** [comment]
Can this be backported to 1.5.x?

**Pull request closed without merging**
