### PR TITLE
Fix #11312: Deprecate ES Reindex on Ingestion and use reindex APIs instead

### LINKED ISSUE #11312: Search Pipeline deployment should show the configuration related to search re-index
**Affected module**
Ingestion,UI

**Describe the bug**
We are not showing any configuration during the pipeline deployment. We should at least make the default recreate indexes to false and allow users to configure this and batch size etc.. options

**To Reproduce**

Screenshots or steps to reproduce

**Expected behavior**

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

### PR DESCRIPTION
**Pull request by ulixius9**
### Describe your changes:

Fix #11312: Deprecate ES Reindex on Ingestion and use ingestion APIs instead

image

#
### Type of change:

- [ ] Bug fix
- [ ] Improvement
- [ ] New feature
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/developers/contribute) document.
- [ ] My PR title is `Fixes <issue-number>: <short explanation>`
- [ ] I have commented on my code, particularly in hard-to-understand areas. 
- [ ] For JSON Schema changes: I updated the migration scripts or explained why it is not needed.

### CODE REVIEW

**Review by mohityadav766 — DISMISSED** [review]

**Review by OnkarVO7 — DISMISSED** [review]

**Review by pmbrull — COMMENTED** [review]
Such a satisfying PR.

I believe we should be able to also remove these files right? https://github.com/open-metadata/OpenMetadata/tree/main/ingestion/src/metadata/ingestion/sink/elasticsearch_mapping

**Comment by harshach** [comment]
@ulixius9 will the Recreate Indexes option turn into select box?

**Comment by harshach** [comment]
@ulixius9 we can't depend on the latest job to monitor the indexing status. User can trigger one as well, this will run into the issue. Instead we should get a job id in response back and use that to monitor cc @mohityadav766

**Comment by ulixius9** [comment]
@pmbrull we cannot remove it because [here](https://github.com/open-metadata/OpenMetadata/blob/8ad8001da1c3ba73264901c576767623e1ca35d4/ingestion/src/metadata/data_insight/api/workflow.py#L121) within data insights workflow we are still using the ES sink which uses these mapping, I had a chat with @TeddyCr regarding this and we do not have any API to do it on the backend yet so until we have that we can not delete these mappings.

**Comment by ulixius9** [comment]
@harshach sure let me take a look into that!

**Comment by Sachin-chaurasiya** [comment]
It's fixed on Main.

Glossary


https://github.com/open-metadata/OpenMetadata/assets/59080942/6886f365-4276-4761-8a0f-bd22fd05700e

Glossary Term


https://github.com/open-metadata/OpenMetadata/assets/59080942/09a97ee4-41ec-4060-8630-d0dfe5cd10f0

**Review by mohityadav766 — APPROVED** [review]
Backend Looks good

**Review by TeddyCr — APPROVED** [review]
LGTM on the ingestion side

**Comment by mohityadav766** [comment]
> @pmbrull we cannot remove it because [here](https://github.com/open-metadata/OpenMetadata/blob/8ad8001da1c3ba73264901c576767623e1ca35d4/ingestion/src/metadata/data_insight/api/workflow.py#L121) within data insights workflow we are still using the ES sink which uses these mapping, I had a chat with @TeddyCr regarding this and we do not have any API to do it on the backend yet so until we have that we can not delete these mappings.

@ulixius9 #12020 for this

**Review by chirag-madlani — APPROVED** [review]

**Pull request merged**
