### PR TITLE
MINOR - Go client documentation

### PR DESCRIPTION
**Pull request by TeddyCr**
### Describe your changes:
- Added documentation for Go SDK

#
### Type of change:

- [ ] Bug fix
- [ ] Improvement
- [ ] New feature
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Documentation

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/developers/contribute) document.
- [x] My PR title is `Fixes <issue-number>: <short explanation>`
- [x] I have commented on my code, particularly in hard-to-understand areas. 
- [x] For JSON Schema changes: I updated the migration scripts or explained why it is not needed.

New feature
- [x] The issue properly describes why the new feature is needed, what's the goal, and how we are building it. Any discussion
    or decision-making process is reflected in the issue.
- [x] I have updated the documentation.
- [x] I have added tests around the new logic.

### CODE REVIEW

**Comment by harshach** [comment]
@TeddyCr This is cool!! Do we have any customers/users interested in it?
To keep the core of OpenMetadata intact, we should move this into OpenMetadata SDK and add languages other than python and Java based on community contributions. wdyt?

**Comment by TeddyCr** [comment]
> @TeddyCr This is cool!! Do we have any customers/users interested in it?
> 
> To keep the core of OpenMetadata intact, we should move this into OpenMetadata SDK and add languages other than python and Java based on community contributions. wdyt? 

I don't believe so. Ah yes that makes sense. You mean an OpenMetadata SDK repo right?

**Comment by harshach** [comment]
@TeddyCr yes openmetadata-sdk

**Comment by TeddyCr** [comment]
> NASA's Collin wanted to develop golang client. We can share it with them to contribute

Sounds good. I'll create a new repo open a PR there.

**Comment by TeddyCr** [comment]
> NASA's Collin wanted to develop golang client. We can share it with them to contribute

@harshach opened a new PR @ https://github.com/open-metadata/openmetadata-sdk/pull/1. This one has the doc changes

**Pull request merged**
