### PR TITLE
[issue-2239] - Update core publish to push

### PR DESCRIPTION
**Pull request by pmbrull**
### Describe your changes :

This PR fixes https://github.com/open-metadata/OpenMetadata/issues/2239.

We are trying to publish a new version of openmetadata-core during the PR phase when it should actually happen during a push to main after the changes have been approved.

Happy to discuss this further. If we agree, I am going to test it by merging https://github.com/open-metadata/OpenMetadata/pull/2134, where we updated the MlModel schema.

Thanks!

#
### Type of change :

- [x] Bug fix
- [ ] Improvement
- [ ] New feature
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation

#
### Frontend Preview (Screenshots) :
<p align="center">For frontend related change, please link screenshots of your changes preview! Optional for backend related changes.
</p>

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/open-source-community/developer) document.
- [ ] I have performed a self-review of my own. 
- [ ] I have tagged my reviewers below.
- [ ] I have commented on my code, particularly in hard-to-understand areas.
- [ ] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [x] All new and existing tests passed.

#
### Reviewers

<@harshach @ayush-shah

### CODE REVIEW

**Comment by pmbrull** [comment]
Thanks @mithmatt for the discussion on this!

**Review by mithmatt — APPROVED** [review]
Thanks for addressing this. 

cc: @akash-jain-10

**Comment by akash-jain-10** [comment]
@pmbrull - Thanks for looking into this.

This will break our commit and push step in CI as we are locked down on security for `main` branch.

This was the sole reason I had to use `pull_request` as the trigger. So that the CI will automatically bump version, build the wheels and upload dev versions to PyPi. Once done, make a commit and push new version to the current PR that Triggered it.

Let me know if I'm missing anything here.

**Comment by pmbrull** [comment]
> @pmbrull - Thanks for looking into this.
> 
> This will break our commit and push step in CI as we are locked down on security for `main` branch.
> 
> This was the sole reason I had to use `pull_request` as the trigger. So that the CI will automatically bump version, build the wheels and upload dev versions to PyPi. Once done, make a commit and push new version to the current PR that Triggered it.
> 
> Let me know if I'm missing anything here.

That's a good point @akash-jain-10 🤔  How would you feel about breaking this down into two steps?

- PR event increments the version and commits to the PR branch (we'd need to test this both with a fork and an internal branch.
- Push event just runs the`make publish`. As that will run internally in the repo we won't have any issues with accessing the secrets.

With this approach, we get a bit more control and just publish changes that have been approved.

WDYT?

**Comment by akash-jain-10** [comment]
> > @pmbrull - Thanks for looking into this.
> > This will break our commit and push step in CI as we are locked down on security for `main` branch.
> > This was the sole reason I had to use `pull_request` as the trigger. So that the CI will automatically bump version, build the wheels and upload dev versions to PyPi. Once done, make a commit and push new version to the current PR that Triggered it.
> > Let me know if I'm missing anything here.
> 
> That's a good point @akash-jain-10 🤔 How would you feel about breaking this down into two steps?
> 
> * PR event increments the version and commits to the PR branch (we'd need to test this both with a fork and an internal branch)
> * Push event just runs the`make publish`. As that will run internally in the repo we won't have any issues with accessing the secrets.
> 
> With this approach, we get a bit more control and just publish changes that have been approved.
> 
> WDYT?

Yes. That is the plan to trigger builds and pushes from forked repositories as well.
Plus to add on, we will use [Test PyPi](https://test.pypi.org/) for publishing our dev packages via automation and have it available. cc @harshach @shahsank3t @ayush-shah

User Creates PR -> Bumps Version (Manual/automate) -> Merges PR to Main -> CI Publishes dev package to Test PyPi

User Creates Forked PR -> Bumps Version (Manual) -> Merges PR to Main -> CI Publishes dev package to Test PyPi

Production Release is still manual which we plan to automate on new Release creations.

Let me know what you guys think of this plan ?

**Comment by pmbrull** [comment]
> > > @pmbrull - Thanks for looking into this.
> > > This will break our commit and push step in CI as we are locked down on security for `main` branch.
> > > This was the sole reason I had to use `pull_request` as the trigger. So that the CI will automatically bump version, build the wheels and upload dev versions to PyPi. Once done, make a commit and push new version to the current PR that Triggered it.
> > > Let me know if I'm missing anything here.
> > 
> > 
> > That's a good point @akash-jain-10 🤔 How would you feel about breaking this down into two steps?
> > 
> > * PR event increments the version and commits to the PR branch (we'd need to test this both with a fork and an internal branch)
> > * Push event just runs the`make publish`. As that will run internally in the repo we won't have any issues with accessing the secrets.
> > 
> > With this approach, we get a bit more control and just publish changes that have been approved.
> > WDYT?
> 
> Yes. That is the plan to trigger builds and pushes from forked repositories as well. Plus to add on, we will use [Test PyPi](https://test.pypi.org/) for publishing our dev packages via automation and have it available. cc @harshach @shahsank3t @ayush-shah
> 
> User Creates PR -> Bumps Version (Manual/automate) -> Merges PR to Main -> CI Publishes dev package to Test PyPi
> 
> User Creates Forked PR -> Bumps Version (Manual) -> Merges PR to Main -> CI Publishes dev package to Test PyPi
> 
> Production Release is still manual which we plan to automate on new Release creations.
> 
> Let me know what you guys think of this plan ?

Hi, mostly LGTM. I like the approach of starting with Test PyPi before jumping to the prod release cycle, a good point in there.

Maybe one comment would be that mainly contributors are working with forks (as they don't have enough permissions to the repo). It might be worth it to not rely on manual intervention to make sure that the process is as easy as possible and we are always following the same convention (in this case the `increment` package).

Hopefully opening a PR internally and externally should have the same effect so that we can also avoid bumping into random issues. Would it make sense to try to unify the bump version behavior by updating the CI to a `pull_request_target`? We should then bear in mind issues like https://github.com/open-metadata/OpenMetadata/issues/2185

Thanks!

**Comment by akash-jain-10** [comment]
Thanks @pmbrull . 

Will keep this PR opened and this will be part - 2 of pypi publish for ingestion-core. 
A couple of updates will need to take care of here - 
- Remove step to bump dev version
- Update makefile to publish onto test.pypi.org

Part 1 PR will contain a workflow which will comment on the PR to bump up version when it detects schema changes (very similar to java checkstyle). I will raise a PR soon for this.

**Comment by pmbrull** [comment]
> Thanks @pmbrull .
> 
> Will keep this PR opened and this will be part - 2 of pypi publish for ingestion-core. A couple of updates will need to take care of here -
> 
> * Remove step to bump dev version
> * Update makefile to publish onto test.pypi.org
> 
> Part 1 PR will contain a workflow which will comment on the PR to bump up version when it detects schema changes (very similar to java checkstyle). I will raise a PR soon for this.

Great thanks @akash-jain-10. Are the secrets `TWINE_*` already pointing to the test index? Or should we change them as well

**Comment by akash-jain-10** [comment]
> > Thanks @pmbrull .
> > Will keep this PR opened and this will be part - 2 of pypi publish for ingestion-core. A couple of updates will need to take care of here -
> > 
> > * Remove step to bump dev version
> > * Update makefile to publish onto test.pypi.org
> > 
> > Part 1 PR will contain a workflow which will comment on the PR to bump up version when it detects schema changes (very similar to java checkstyle). I will raise a PR soon for this.
> 
> Great thanks @akash-jain-10. Are the secrets `TWINE_*` already pointing to the test index? Or should we change them as well

We need to change those. I will update those once we have this PR ready for merge :)

**Comment by pmbrull** [comment]
Hi @akash-jain-10 let me know if that was what you were thinking.

I changed the names of the secrets with `_TEST` to avoid confusion and make the change clear when we move to the prod release.

Thanks

**Comment by akash-jain-10** [comment]
LGTM. I have added secrets as per the names here - `TWINE_USERNAME_TEST` and `TWINE_PASSWORD_TEST`.

**Review by akash-jain-10 — APPROVED** [review]

**Review by harshach — APPROVED** [review]

**Pull request merged**
