### PR TITLE
[issue-2322] - Backup CLI

### PR DESCRIPTION
**Pull request by pmbrull**
### Describe your changes :

This PR fixes https://github.com/open-metadata/OpenMetadata/issues/2322

We are adding new functionality to the `metadata` CLI to run backups using `mysqldump`. For now, we are providing a wrapper around the tool to create the output file and optionally upload it to S3.

An example run of the CLI looks like this:
```
metadata backup -u openmetadata_user -p openmetadata_password -h localhost -d openmetadata_db --output=backup/random/hello --upload http://localhost:9000 backup backup1/random
```

And we get the following output
```
Creating OpenMetadata backup for localhost:3306/openmetadata_db...
mysqldump: [Warning] Using a password on the command line interface can be insecure.
Backup stored locally under backup/random/hello/openmetadata_202201221719_backup.sql
Uploading backup/random/hello/openmetadata_202201221719_backup.sql to http://localhost:9000/backup/backup1/random/openmetadata_202201221719_backup.sql...
```

It has been tested against the local docker-compose and the default `options` are the ones necessary to run the process against the container DB with the default user & pwd provided. However, we allow any number of options that might be required by mysqldump in other scenarios via `-o <opt1> -o <opt2> [...]`.

The upload has been tested with a containerized minio server.

At some point, we might want to move away from `mysqldump` and have a pure python implementation, but so far it seems to be the most powerful tool for our purposes.

Please, let me know your thoughts! Thanks!

> OBS: I also had a go on the python CI workflow to run it not only when we update the src ingestion code, but also when there are changes in the schemas

#
### Type of change :

- [ ] Bug fix
- [ ] Improvement
- [x] New feature
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation

#
### Frontend Preview (Screenshots) :
<p align="center">For frontend related change, please link screenshots of your changes preview! Optional for backend related changes.
</p>

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/open-source-community/developer) document.
- [ ] I have performed a self-review of my own. 
- [ ] I have tagged my reviewers below.
- [ ] I have commented on my code, particularly in hard-to-understand areas.
- [ ] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [x] All new and existing tests passed.

#
### Reviewers

@harshach @ayush-shah

### CODE REVIEW

**Comment by pmbrull** [comment]
checking pydantic model errors 👀

**Comment by pmbrull** [comment]
Sorry for the noise, I had to update the python CI when moving the sample data DAG out from the `DockerOperator` and missed the correct order of installing the deps. It should be all good now!

**Comment by pmbrull** [comment]
Most of the sonar issues appeared here as I moved some files around. If you agree we can open a separate issue to tackle them

**Comment by harshach** [comment]
Thanks a lot @pmbrull . This looks great. We can handle sonar warnings in another PR.

**Review by harshach — APPROVED** [review]

**Pull request merged**
